---
- name: Remove output folders
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    root_dir: "{{ playbook_dir }}"
  tasks:
    - name: Delete local folders
      ansible.builtin.file:
        path: "{{ root_dir }}/{{ item }}"
        state: absent
      with_items:
        - documentation
        - reports
        - config_backup
        - intended
        - anta/avd_catalogs
        - anta/reports
