---
### Traffic Policies to cover IPv6 field and none policy case
traffic_policies:
  field_sets:
    ipv6:
      - name: IPv6-DEMO-1
        prefixes:
          - 11:22:33:44:55:66:77:88
        except:
          - 22:33:44:55:66:77:88:11
      - name: IPv6-DEMO-2
