# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: arista/arista_portal.v1/arista_portal.proto, arista/arista_portal.v1/services.gen.proto
# plugin: python-aristaproto
# This file has been @generated

__all__ = (
    "ApiProxy",
    "ApiProxyConfig",
    "ApiProxyConfigDeleteRequest",
    "ApiProxyConfigDeleteResponse",
    "ApiProxyConfigRequest",
    "ApiProxyConfigResponse",
    "ApiProxyConfigServiceStub",
    "ApiProxyConfigSetRequest",
    "ApiProxyConfigSetResponse",
    "ApiProxyConfigStreamRequest",
    "ApiProxyConfigStreamResponse",
    "ApiProxyRequest",
    "ApiProxyResponse",
    "ApiProxyServiceStub",
    "ApiProxyStreamRequest",
    "ApiProxyStreamResponse",
    "ApiToken",
    "ApiTokenConfig",
    "ApiTokenConfigDeleteRequest",
    "ApiTokenConfigDeleteResponse",
    "ApiTokenConfigRequest",
    "ApiTokenConfigResponse",
    "ApiTokenConfigServiceStub",
    "ApiTokenConfigSetRequest",
    "ApiTokenConfigSetResponse",
    "ApiTokenConfigStreamRequest",
    "ApiTokenConfigStreamResponse",
    "ApiTokenRequest",
    "ApiTokenResponse",
    "ApiTokenServiceStub",
    "ApiTokenStreamRequest",
    "ApiTokenStreamResponse",
    "MetaResponse",
)

import datetime
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import TYPE_CHECKING

import aristaproto
import grpc
from aristaproto import grpcio as aristaproto_grpcio

from ....message_pool import default_message_pool

if TYPE_CHECKING:
    from aristaproto.grpcio.grpcio_async_client import MetadataLike

_COMPILER_VERSION = "2.0.0.dev1"
aristaproto.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ApiProxy(aristaproto.Message):
    """
    APIProxy is the state model that displays the proxy url string value set and found on
    the CloudVision instance.

    APIProxy Methods:

    The `GetOne` method is used to return a proxy with username and password obscured
    that has been set within CloudVision.

    Retrieving a proxy:

    The proxy can be retrieved from CloudVision by calling the `GetOne` method.

    Here is an example of a proxy being retrieved

    ```
    GetOne(APIProxy{
    })
    ```

    NOTE: Proxy configuration is not applicable to CloudVision-as-a-Service.
    - If a proxy contains a username and/or password, it will be returned with the credentials
    censored.
    """

    url: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    url is the proxy URL string
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxy", ApiProxy)


@dataclass(eq=False, repr=False)
class ApiProxyConfig(aristaproto.Message):
    """
    APIProxyConfig is the config model allowing users to set and delete the proxy value which
    is used in retrieving resources from arista.com.

    APIProxyConfig Methods:

    The `Set` method is used to add and/or modify a proxy stored in CloudVision.
    The `Delete` method is used to remove said proxy.
    The `GetOne` method is used to return a proxy with username and password obscured
    that has been set within CloudVision.

    Adding a proxy to CloudVision:

    When a `Set` is called, the rAPI will first ensure this proxy is valid after which it will
    stored within CloudVision.

    Here is an example of a proxy value being set

    ```
    Set(APIProxyConfig{
       Url: “http://10.0.0.0:0”
    })
    ```

    Deleting a proxy:

    The proxy configuration can be removed from CloudVision by calling `Delete`.

    Here is an example of a proxy being deleted

    ```
    Delete(APIProxyConfig{
    })
    ```

    Retrieving a proxy:

    The proxy can be retrieved from CloudVision by calling the `GetOne` method.

    Here is an example of a proxy being retrieved

    ```
    GetOne(APIProxyConfig{
    })
    ```

    NOTE: Proxy configuration is not applicable to CloudVision-as-a-Service.
    - If a proxy contains a username and/or password, it will be returned with the credentials
    censored.
    """

    url: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    url is the proxy URL string
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfig", ApiProxyConfig)


@dataclass(eq=False, repr=False)
class ApiProxyConfigDeleteRequest(aristaproto.Message):
    pass


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigDeleteRequest", ApiProxyConfigDeleteRequest)


@dataclass(eq=False, repr=False)
class ApiProxyConfigDeleteResponse(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the (UTC) timestamp at which the system recognizes the
    deletion. The only guarantees made about this timestamp are:

       - it is after the time the request was received
       - a time-ranged query with StartTime==DeletedAt will not include this instance.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigDeleteResponse", ApiProxyConfigDeleteResponse)


@dataclass(eq=False, repr=False)
class ApiProxyConfigRequest(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigRequest", ApiProxyConfigRequest)


@dataclass(eq=False, repr=False)
class ApiProxyConfigResponse(aristaproto.Message):
    value: "ApiProxyConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    APIProxyConfig instance in this response.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigResponse", ApiProxyConfigResponse)


@dataclass(eq=False, repr=False)
class ApiProxyConfigSetRequest(aristaproto.Message):
    value: "ApiProxyConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    APIProxyConfig carries the value to set into the datastore.
    See the documentation on the APIProxyConfig struct for which fields are required.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigSetRequest", ApiProxyConfigSetRequest)


@dataclass(eq=False, repr=False)
class ApiProxyConfigSetResponse(aristaproto.Message):
    value: "ApiProxyConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value carries all the values given in the APIProxyConfigSetRequest as well
    as any server-generated values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the (UTC) timestamp at which the system recognizes the
    creation. The only guarantees made about this timestamp are:

       - it is after the time the request was received
       - a time-ranged query with StartTime==CreatedAt will include this instance.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigSetResponse", ApiProxyConfigSetResponse)


@dataclass(eq=False, repr=False)
class ApiProxyConfigStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[ApiProxyConfig]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each APIProxyConfig at end.
        * Each APIProxyConfig response is fully-specified (all fields set).
      * start: Returns the state of each APIProxyConfig at start, followed by updates until now.
        * Each APIProxyConfig response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each APIProxyConfig at start, followed by updates
        until end.
        * Each APIProxyConfig response at start is fully-specified, but updates until end may
          be partial.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigStreamRequest", ApiProxyConfigStreamRequest)


@dataclass(eq=False, repr=False)
class ApiProxyConfigStreamResponse(aristaproto.Message):
    value: "ApiProxyConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is a value deemed relevant to the initiating request.
    This structure will always have its key-field populated. Which other fields are
    populated, and why, depends on the value of Operation and what triggered this notification.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of this APIProxyConfig's last modification.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the APIProxyConfig value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyConfigStreamResponse", ApiProxyConfigStreamResponse)


@dataclass(eq=False, repr=False)
class ApiProxyRequest(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyRequest", ApiProxyRequest)


@dataclass(eq=False, repr=False)
class ApiProxyResponse(aristaproto.Message):
    value: "ApiProxy | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    APIProxy instance in this response.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyResponse", ApiProxyResponse)


@dataclass(eq=False, repr=False)
class ApiProxyStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[ApiProxy]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each APIProxy at end.
        * Each APIProxy response is fully-specified (all fields set).
      * start: Returns the state of each APIProxy at start, followed by updates until now.
        * Each APIProxy response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each APIProxy at start, followed by updates
        until end.
        * Each APIProxy response at start is fully-specified, but updates until end may
          be partial.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyStreamRequest", ApiProxyStreamRequest)


@dataclass(eq=False, repr=False)
class ApiProxyStreamResponse(aristaproto.Message):
    value: "ApiProxy | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is a value deemed relevant to the initiating request.
    This structure will always have its key-field populated. Which other fields are
    populated, and why, depends on the value of Operation and what triggered this notification.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of this APIProxy's last modification.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the APIProxy value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIProxyStreamResponse", ApiProxyStreamResponse)


@dataclass(eq=False, repr=False)
class ApiToken(aristaproto.Message):
    """
    APIToken is the state model that indicates whether a token is set or not.

    APIToken Methods:

    The `GetOne` method is used to determine whether a token is set or not within CloudVision.

    Retrieving a token:

    The token can be retrieved from CloudVision by calling the `GetOne` method.

    Here is an example of a token being retrieved

    ```
    GetOne(APIToken{
    })
    ```

    NOTE: `GetOne` functionality for APIToken will only display whether a token is
    currently present or not. No secret values will be returned.
    The two valid responses are;
    * "Token is set"
    * "Token not set"
    """

    token: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    token is the token string
    """


default_message_pool.register_message("arista.arista_portal.v1", "APIToken", ApiToken)


@dataclass(eq=False, repr=False)
class ApiTokenConfig(aristaproto.Message):
    """
    APITokenConfig is the config model allowing users to modify the token value which
    is used for a multitude of functionalities, mainly in retrieving resources from arista.com e.g.
    the AlertBase.json or software images.
    Without a token set, a user can not retrieve any resources from arista.com
    NOTE: A user configured token is not required on CloudVision-as-a-Service for AlertBase updates.

    APITokenConfig Methods:

    The `Set` method is used to add and/or modify a token stored in CloudVision.
    The `Delete` method is used to remove the token.
    The `GetOne` method is used to determine whether a token is set or not on CloudVision.

    Adding a token to CloudVision:

    When a `Set` is called, the rAPI will first ensure the token is valid and in the correct format
    after which it will stored within CloudVision.

    Here is an example of a token value being set

    ```
    Set(APITokenConfig{
       Token: "f7f898e3860f618301c01f2de1ao1482"
    })
    ```

    Deleting a token:

    The token can be removed from CloudVision by calling `Delete`.

    Here is an example of a token being deleted

    ```
    Delete(APITokenConfig{
    })
    ```

    Retrieving a token:

    The token can be retrieved from CloudVision by calling the `GetOne` method.

    Here is an example of a token being retrieved

    ```
    GetOne(APITokenConfig{
    })
    ```

    NOTE: `GetOne` functionality for APITokenConfig will only display whether a token is
    currently present or not. No secret values will be returned.
    The two valid responses are;
    * "Token is set"
    * "Token not set"
    """

    token: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    token is the token string
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfig", ApiTokenConfig)


@dataclass(eq=False, repr=False)
class ApiTokenConfigDeleteRequest(aristaproto.Message):
    pass


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigDeleteRequest", ApiTokenConfigDeleteRequest)


@dataclass(eq=False, repr=False)
class ApiTokenConfigDeleteResponse(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the (UTC) timestamp at which the system recognizes the
    deletion. The only guarantees made about this timestamp are:

       - it is after the time the request was received
       - a time-ranged query with StartTime==DeletedAt will not include this instance.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigDeleteResponse", ApiTokenConfigDeleteResponse)


@dataclass(eq=False, repr=False)
class ApiTokenConfigRequest(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigRequest", ApiTokenConfigRequest)


@dataclass(eq=False, repr=False)
class ApiTokenConfigResponse(aristaproto.Message):
    value: "ApiTokenConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    APITokenConfig instance in this response.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigResponse", ApiTokenConfigResponse)


@dataclass(eq=False, repr=False)
class ApiTokenConfigSetRequest(aristaproto.Message):
    value: "ApiTokenConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    APITokenConfig carries the value to set into the datastore.
    See the documentation on the APITokenConfig struct for which fields are required.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigSetRequest", ApiTokenConfigSetRequest)


@dataclass(eq=False, repr=False)
class ApiTokenConfigSetResponse(aristaproto.Message):
    value: "ApiTokenConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value carries all the values given in the APITokenConfigSetRequest as well
    as any server-generated values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the (UTC) timestamp at which the system recognizes the
    creation. The only guarantees made about this timestamp are:

       - it is after the time the request was received
       - a time-ranged query with StartTime==CreatedAt will include this instance.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigSetResponse", ApiTokenConfigSetResponse)


@dataclass(eq=False, repr=False)
class ApiTokenConfigStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[ApiTokenConfig]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each APITokenConfig at end.
        * Each APITokenConfig response is fully-specified (all fields set).
      * start: Returns the state of each APITokenConfig at start, followed by updates until now.
        * Each APITokenConfig response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each APITokenConfig at start, followed by updates
        until end.
        * Each APITokenConfig response at start is fully-specified, but updates until end may
          be partial.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigStreamRequest", ApiTokenConfigStreamRequest)


@dataclass(eq=False, repr=False)
class ApiTokenConfigStreamResponse(aristaproto.Message):
    value: "ApiTokenConfig | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is a value deemed relevant to the initiating request.
    This structure will always have its key-field populated. Which other fields are
    populated, and why, depends on the value of Operation and what triggered this notification.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of this APITokenConfig's last modification.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the APITokenConfig value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenConfigStreamResponse", ApiTokenConfigStreamResponse)


@dataclass(eq=False, repr=False)
class ApiTokenRequest(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenRequest", ApiTokenRequest)


@dataclass(eq=False, repr=False)
class ApiTokenResponse(aristaproto.Message):
    value: "ApiToken | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    APIToken instance in this response.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenResponse", ApiTokenResponse)


@dataclass(eq=False, repr=False)
class ApiTokenStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[ApiToken]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each APIToken at end.
        * Each APIToken response is fully-specified (all fields set).
      * start: Returns the state of each APIToken at start, followed by updates until now.
        * Each APIToken response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each APIToken at start, followed by updates
        until end.
        * Each APIToken response at start is fully-specified, but updates until end may
          be partial.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenStreamRequest", ApiTokenStreamRequest)


@dataclass(eq=False, repr=False)
class ApiTokenStreamResponse(aristaproto.Message):
    value: "ApiToken | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is a value deemed relevant to the initiating request.
    This structure will always have its key-field populated. Which other fields are
    populated, and why, depends on the value of Operation and what triggered this notification.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of this APIToken's last modification.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the APIToken value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """


default_message_pool.register_message("arista.arista_portal.v1", "APITokenStreamResponse", ApiTokenStreamResponse)


@dataclass(eq=False, repr=False)
class MetaResponse(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of the last item included in the metadata calculation.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """

    count: "int | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.UInt32Value, optional=True)
    """
    Count is the number of items present under the conditions of the request.
    """


default_message_pool.register_message("arista.arista_portal.v1", "MetaResponse", MetaResponse)


class ApiProxyConfigServiceStub(aristaproto_grpcio.ServiceStub):
    async def get_one(
        self,
        message: "ApiProxyConfigRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiProxyConfigResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APIProxyConfigService/GetOne",
            message,
            ApiProxyConfigResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def get_all(
        self,
        message: "ApiProxyConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiProxyConfigStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyConfigService/GetAll",
            message,
            ApiProxyConfigStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe(
        self,
        message: "ApiProxyConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiProxyConfigStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyConfigService/Subscribe",
            message,
            ApiProxyConfigStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe_meta(
        self,
        message: "ApiProxyConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[MetaResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyConfigService/SubscribeMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def set(
        self,
        message: "ApiProxyConfigSetRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiProxyConfigSetResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APIProxyConfigService/Set",
            message,
            ApiProxyConfigSetResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def delete(
        self,
        message: "ApiProxyConfigDeleteRequest | None" = None,
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiProxyConfigDeleteResponse":

        if message is None:
            message = ApiProxyConfigDeleteRequest()

        return await self._unary_unary(
            "/arista.arista_portal.v1.APIProxyConfigService/Delete",
            message,
            ApiProxyConfigDeleteResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )


class ApiProxyServiceStub(aristaproto_grpcio.ServiceStub):
    async def get_one(
        self,
        message: "ApiProxyRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiProxyResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APIProxyService/GetOne",
            message,
            ApiProxyResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def get_all(
        self,
        message: "ApiProxyStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiProxyStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyService/GetAll",
            message,
            ApiProxyStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe(
        self,
        message: "ApiProxyStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiProxyStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyService/Subscribe",
            message,
            ApiProxyStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe_meta(
        self,
        message: "ApiProxyStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[MetaResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APIProxyService/SubscribeMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response


class ApiTokenConfigServiceStub(aristaproto_grpcio.ServiceStub):
    async def get_one(
        self,
        message: "ApiTokenConfigRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiTokenConfigResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APITokenConfigService/GetOne",
            message,
            ApiTokenConfigResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def get_all(
        self,
        message: "ApiTokenConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiTokenConfigStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenConfigService/GetAll",
            message,
            ApiTokenConfigStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe(
        self,
        message: "ApiTokenConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiTokenConfigStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenConfigService/Subscribe",
            message,
            ApiTokenConfigStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe_meta(
        self,
        message: "ApiTokenConfigStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[MetaResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenConfigService/SubscribeMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def set(
        self,
        message: "ApiTokenConfigSetRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiTokenConfigSetResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APITokenConfigService/Set",
            message,
            ApiTokenConfigSetResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def delete(
        self,
        message: "ApiTokenConfigDeleteRequest | None" = None,
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiTokenConfigDeleteResponse":

        if message is None:
            message = ApiTokenConfigDeleteRequest()

        return await self._unary_unary(
            "/arista.arista_portal.v1.APITokenConfigService/Delete",
            message,
            ApiTokenConfigDeleteResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )


class ApiTokenServiceStub(aristaproto_grpcio.ServiceStub):
    async def get_one(
        self,
        message: "ApiTokenRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "ApiTokenResponse":

        return await self._unary_unary(
            "/arista.arista_portal.v1.APITokenService/GetOne",
            message,
            ApiTokenResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def get_all(
        self,
        message: "ApiTokenStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiTokenStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenService/GetAll",
            message,
            ApiTokenStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe(
        self,
        message: "ApiTokenStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[ApiTokenStreamResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenService/Subscribe",
            message,
            ApiTokenStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe_meta(
        self,
        message: "ApiTokenStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[MetaResponse]":

        async for response in self._unary_stream(
            "/arista.arista_portal.v1.APITokenService/SubscribeMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response


from ....google import protobuf as ___google__protobuf__
from ... import subscriptions as __subscriptions__
from ... import time as __time__
