aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_dc1-leaf2a_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: dc1-leaf2a
  peer_interface: Ethernet8
  peer_type: l3leaf
- name: Ethernet2
  description: L2_dc1-leaf2b_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  peer: dc1-leaf2b
  peer_interface: Ethernet8
  peer_type: l3leaf
- name: Ethernet12
  description: SERVER_DC1-LEAF2-SERVER1_iLO
  shutdown: false
  peer: DC1-LEAF2-SERVER1
  peer_interface: iLO
  peer_type: server
  switchport:
    enabled: true
- name: Ethernet32
  shutdown: false
  peer_type: network_port
  switchport:
    enabled: true
- name: Ethernet34
  shutdown: false
  peer_type: network_port
  switchport:
    enabled: true
hostname: dc1-leaf2c
ip_igmp_snooping:
  globally_enabled: true
is_deployed: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.1.152/24
  type: oob
metadata:
  platform: vEOS-lab
  fabric_name: FABRIC
  digital_twin:
    environment: act
    node_type: veos
    ip_addr: 172.16.1.152/24
    version: 4.33.2F
    username: act_user
    password: act_pass
port_channel_interfaces:
- name: Port-Channel1
  description: L2_DC1_L3_LEAF2_Port-Channel8
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
prompt: virtual_friendly_prompt
service_routing_protocols_model: multi-agent
terminal:
  length: 100
  width: 100
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
