---
# test for underlay_ipv6_numbered: true
underlay_ipv6_numbered: true
underlay_ipv6: true

bgp_peer_groups:
  ipv4_underlay_peers:
    name: IPV6-UNDERLAY-PEERS
    # Testing BFD
    bfd: true
    # Custom structured config added under router_bgp.peer_groups.<name> for eos_cli_config_gen
    structured_config:
      description: Description for ipv4_underlay_peers via structured_config for IPv6 underlay numbered

fabric_ip_addressing:
  p2p_uplinks:
    ipv6_prefix_length: 127
