---
# Testing errdisable_settings with only recovery

type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: errdisable-settings-2
      id: 42

errdisable_settings:
  recovery:
    causes:
      - name: acl
        interval: 60
      - name: arp-inspection
        interval: 90
      - name: bpduguard
        interval: 300
      - name: dot1x
        interval: 60
      - name: link-flap
        interval: 60
      - name: storm-control
        interval: 120
    interval: 300
