---
# Test for management settings
type: l2leaf
l2leaf:
  nodes:
    - name: management-settings-login-banner
      mgmt_ip: 192.168.0.2/24

management_settings:
  banners:
    login: |
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      !***!!!Unauthorized access prohibited!!!***!
      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
