# Minimum config to only test the specific feature.
mgmt_interface: MY_INTERFACE_FABRIC
mgmt_interface_vrf: MGMT
mgmt_gateway: 1.1.1.1
l2leaf:
  nodes:
    - name: mgmt-interface-fabric
      mgmt_ip: 1.1.1.2
      id: 103
      filter:
        deny_vrfs: [ MULTI_TENANT_VRF_TEST ]
