---
# Tests OSPFv3

type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.66.0/24
    vtep_loopback_ipv4_pool: 192.168.142.0/24
    virtual_router_mac_address: 00:11:22:33:44:55
    bgp_as: 666
  nodes:
    - name: network-services-ospf-v3
      id: 142
      mgmt_ip: 192.168.42.142/24

tenants:
  # Test OSPFv3 Redistribution
  - name: Tenant_OSPFv3_Redistribute
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 20000
    redistribute_mlag_ibgp_peering_vrfs: true
    vrfs:
      - name: Tenant_OSPFv3_Redistribute_VRF
        vrf_vni: 100
        vrf_id: 42
        ipv6_ospf:
          enabled: true
          router_id: ipv6_ospf_router
          auto_cost_reference_bandwidth: 10
          redistribute_bgp:
            enabled: true
          redistribute_connected:
            enabled: true
          nodes: [network-services-ospf-v3]
        svis:
          - id: 201
            name: Tenant_OSPFv3_Redistribute_201
            description: "Tenant_OSPFv3_Redistribute_201 description"
            enabled: true
            ipv6_address: cafe::cafe/64
            ipv6_enable: true
            ipv6_ospf:
              enabled: true
              point_to_point: true
  # Test OSPFv3 Redistribution with route map
  - name: Tenant_OSPFv3_Redistribute_Route_Map
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 20000
    redistribute_mlag_ibgp_peering_vrfs: true
    vrfs:
      - name: Tenant_OSPFv3_Redistribute_Route_Map_VRF
        vrf_vni: 101
        vrf_id: 43
        ipv6_ospf:
          enabled: true
          router_id: ipv6_ospf_router_route_map
          auto_cost_reference_bandwidth: 10
          redistribute_bgp:
            enabled: true
            route_map: ipv6_ospf_rm
          redistribute_connected:
            enabled: true
            route_map: ipv6_ospf_rm
          nodes: [network-services-ospf-v3]
        svis:
          - id: 202
            name: Tenant_OSPFv3_Redistribute_Route_Map_202
            description: "Tenant_OSPFv3_Redistribute_Route_Map_202 description"
            enabled: true
            ipv6_address: cafe::/64
            ipv6_enable: true
            ipv6_ospf:
              enabled: true
              point_to_point: true
  # Test OSPFv3 Redistribution with leaked route
  - name: Tenant_OSPFv3_Redistribute_Include_Leaked
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 20000
    redistribute_mlag_ibgp_peering_vrfs: true
    vrfs:
      - name: Tenant_OSPFv3_Redistribute_Include_Leaked_VRF
        vrf_vni: 102
        vrf_id: 44
        ipv6_ospf:
          enabled: true
          router_id: ipv6_ospf_router_include_leaked
          redistribute_bgp:
            enabled: true
            route_map: ipv6_ospf_rm
            include_leaked: true
          redistribute_connected:
            enabled: true
            route_map: ipv6_ospf_rm
            include_leaked: true
          nodes: [network-services-ospf-v3]
        svis:
          - id: 203
            name: Tenant_OSPFv3_Redistribute_Include_Leaked_203
            description: "Tenant_OSPFv3_Redistribute_Include_Leaked_203 description"
            enabled: true
            ipv6_address: cafe::ca/64
            ipv6_enable: true
            ipv6_ospf:
              enabled: true
              point_to_point: true
