type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: ntp-settings-2
      # mgmt_ip: 192.168.0.2/24
      inband_mgmt_ip: 192.168.1.2/24
      inband_mgmt_ipv6_address: 2001:db8:200::2/64
      inband_mgmt_vrf: INBAND_MGMT

ntp_settings:
  server_vrf: use_inband_mgmt_vrf
  set_first_ntp_server_as_preferred: false
  servers:
    - name: 10.10.10.1
      source_address: use_inband_mgmt_interface_ipv4
    - name: 10.10.10.2
      source_address: 198.51.100.10
    - name: 2001:db8:200::10
      source_address: use_inband_mgmt_interface_ipv6
