# Testing source_address as use_mgmt_interface_ipv4/use_mgmt_interface_ipv6
type: l2leaf

default_mgmt_method: inband

l2leaf:
  defaults:
    platform: vEOS-lab
    inband_mgmt_subnet: "10.254.254.0/24"

  nodes:
    - name: ntp-settings-3
      id: 3
      mgmt_ip: 192.168.0.204/24
      ipv6_mgmt_ip: 2001:db8:100::2/64

ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: 192.168.200.5
      source_address: use_mgmt_interface_ipv4
    - name: 2001:db8:200::2
      source_address: use_mgmt_interface_ipv6
