---
# Verifying bgp-wait-install is rendered for this platform
type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
  nodes:
    - name: platform-7358x4
      bgp_as: 925
      id: 1
