---
# Minimum config to only test the specific feature.
# This tests the SNMP auto engine ID for rfc3411_type3
type: l2leaf

l2leaf:
  nodes:
    - name: snmp-autogen-engineid-rfc3411-type3
      id: 43
      system_mac_address: "42:42:42:42:42:42"

snmp_settings:
  compute_local_engineid: true
  compute_local_engineid_source: rfc3411_type3
  compute_v3_user_localized_key: true
  users:
    - name: usertest-auth-priv
      group: usergroup
      version: v3
      auth: sha
      auth_passphrase: clearauth # to get from vault in real life
      priv: aes192
      priv_passphrase: clearpriv # to get from vault in real life
