---
# Minimum config to only test the specific feature.
# This tests the SNMP engineID using system MAC
# As well as the fact that default_engineid_from_system_mac has precedence over compute_local_engineid
# Setting system_mac_address as a host variable

type: l2leaf

# Adding dc_name and pod_name to test location_template
dc_name: Test_dc_2
pod_name: Test_pod_2

l2leaf:
  nodes:
    - name: snmp-system-mac-engineid-2
      id: 42
      # no topology system_mac_address
system_mac_address: "12:34:56:78:90:AB"

snmp_settings:
  contact: example@example.com
  location: true
  # To test location_template other than default
  location_template: "CUSTOM LOCATION STRING {fabric_name} {hostname}"
  compute_local_engineid: true
  compute_local_engineid_source: system_mac
  compute_v3_user_localized_key: true
  local_users:
    - name: usertest-auth-priv
      group: usergroup
      version: v3
      auth: sha
      auth_passphrase: clearauth # to get from vault in real life
      priv: aes192
      priv_passphrase: clearpriv # to get from vault in real life
