---
type: spine

spine:
  nodes:
    - bgp_as: 65000
      name: standard-acls
      id: 1
      loopback_ipv4_pool: 192.168.0.0/24

standard_acls:
  - name: TEST-STANDARD-ACL-PLAIN
    entries:
      - sequence: 10
        action: permit
        source: 10.0.0.0/8
      - sequence: 20
        action: deny
        source: any

  - name: TEST-STANDARD-ACL-WITH-COUNTERS
    counters_per_entry: true
    entries:
      - sequence: 10
        action: permit
        source: 192.168.1.1
      - sequence: 20
        action: deny
        source: any
        log: true

  - name: TEST-STANDARD-ACL-WITH-REMARK-AND-VLAN
    entries:
      - sequence: 10
        remark: Allow management subnet
      - sequence: 20
        action: permit
        source: 172.16.0.0/12
        vlan: 100
        vlan_mask: "0xFFF"
      - sequence: 30
        action: permit
        source: 172.20.0.0/16
        inner_vlan: 200
        inner_vlan_mask: "0xFFF"
        mirror_session: SESSION1
