---
# pvst_border does not render as mode is not mstp
type: l2leaf

l2leaf:
  nodes:
    - name: stp-settings-3
      id: 43
      mgmt_ip: 10.10.10.43/26
      spanning_tree_mode: rstp
      spanning_tree_priority: 4096
      spanning_tree_port_id_allocation_port_channel_range:
        minimum: 401
        maximum: 2002
      spanning_tree_mst_pvst_boundary: true
      spanning_tree_root_super: true

spanning_tree_settings:
  mode: rstp
  priority: 8192
  port_id_allocation_port_channel_range:
    minimum: 201
    maximum: 2001
  loop_guard_default: false

# Enable pvst_border when STP mode is mstp
avd_design_future:
  render_pvst_border_when_mode_is_mstp: true
