---
# Test case 4: custom profile - check additional profile configured and custom profile configured ONLY ONCE
# Expected output:
# hardware tcam
#    profile additional-profile
#       source flash:/additional-profile.conf
#    !
#    profile custom-profile
#       source flash:/custom-profile.conf
#    !
#    system profile custom-profile
type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: tcam-profile-4
      mgmt_ip: 192.168.0.2/24
      platform: test-platform

tcam_profiles:
  - name: custom-profile
    source: flash:/custom-profile.conf
  - name: additional-profile
    source: flash:/additional-profile.conf

platform_settings:
  - platforms: ["test-platform"]
    tcam_profile: custom-profile
    additional_tcam_profiles:
      - additional-profile
      - custom-profile
