# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
- name: Role Removal Notice
  ansible.builtin.fail:
    msg: |-
      The 'dhcp_provisioner' role has been removed. The role is not compatible with modern DHCP servers
      and should not be used for production. The 'arista.avd.dhcp_provisioner' role is released as open
      source, so it can be copied and reused according to the license and copyright.
      Please refer to https://avd.arista.com/6.x/docs/porting-guides/6.x.x.html for more information.
  run_once: true
