---
# IPv6-numbered MLAG iBGP peering without overlay_mlag_rfc5549, using the shared MLAG peer group.
underlay_ipv6: true
underlay_ipv6_numbered: true

l3leaf:
  defaults:
    platform: vEOS-lab
    mlag_interfaces: [Ethernet11, Ethernet12]
    virtual_router_mac_address: 00:1c:73:00:00:99
    router_id_pool: 10.255.1.0/24
    loopback_ipv6_pool: 2001:db8:1::/48
    vtep_loopback_ipv6_pool: 2001:db8:5::/48
    mlag_peer_address_family: ipv6
    mlag_peer_ipv6_pool: 2001:db8:3::/48
    mlag_peer_l3_ipv6_pool: 2001:db8:4::/48
  node_groups:
    - group: MLAG_VRF_PG_AF_IPV6_NUMBERED_NO_OVERLAY_SHARED
      bgp_as: 65125
      nodes:
        - name: mlag-vrf-pg-af-ipv6-numbered-no-overlay-shared-leaf1a
          id: 29
          mgmt_ip: 192.168.201.129/24
        - name: mlag-vrf-pg-af-ipv6-numbered-no-overlay-shared-leaf1b
          id: 30
          mgmt_ip: 192.168.201.130/24
