list = [
    {"tag": "Role", "avd_var": "type", "type": None},
    {"tag": "DC_Name", "avd_var": "dc_name", "type": None},
    {"tag": "ID", "avd_var": "node_type_keys\\.key.defaults.id", "type": "int"},
    {"tag": "BGP_AS", "avd_var": "node_type_keys\\.key.defaults.bgp_as", "type": None},
    {"tag": "Uplink_Switch_Interfaces", "avd_var": "node_type_keys\\.key.defaults.uplink_switch_interfaces", "type": "list"},
    {"tag": "Node_Group", "avd_var": "node_type_keys\\.key.node_groups", "type": "node_group"},
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-platform", "avd_var": "node_type_keys\\.key.defaults.platform"},
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-loopback_ipv4_pool", "avd_var": "node_type_keys\\.key.defaults.loopback_ipv4_pool"},
    {
        "input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-loopback_ipv4_offset",
        "avd_var": "node_type_keys\\.key.defaults.loopback_ipv4_offset",
    },
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-bgp_defaults", "avd_var": "node_type_keys\\.key.defaults.bgp_defaults"},
    {
        "input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-virtual_router_mac_address",
        "avd_var": "node_type_keys\\.key.defaults.virtual_router_mac_address",
    },
    {
        "input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-vtep_loopback_ipv4_pool",
        "avd_var": "node_type_keys\\.key.defaults.vtep_loopback_ipv4_pool",
    },
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-uplink_ipv4_pool", "avd_var": "node_type_keys\\.key.defaults.uplink_ipv4_pool"},
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-uplink_switches", "avd_var": "node_type_keys\\.key.defaults.uplink_switches"},
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-uplink_interfaces", "avd_var": "node_type_keys\\.key.defaults.uplink_interfaces"},
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-mlag_interfaces", "avd_var": "node_type_keys\\.key.defaults.mlag_interfaces"},
    {
        "input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-mlag_peer_l3_ipv4_pool",
        "avd_var": "node_type_keys\\.key.defaults.mlag_peer_l3_ipv4_pool",
    },
    {"input": "root-resolver_dc_vars-dc_vars-resolver_role_vars-role_vars-mlag_peer_ipv4_pool", "avd_var": "node_type_keys\\.key.defaults.mlag_peer_ipv4_pool"},
    {"input": "root-resolver_dc_vars-dc_vars-mgmt_gateway", "avd_var": "mgmt_gateway"},
    {"input": "root-collection_port_profiles-item-profile", "avd_var": "port_profiles.profile"},
    {"input": "root-collection_port_profiles-item-mode", "avd_var": "port_profiles.mode"},
    {"input": "root-collection_port_profiles-item-vlans", "avd_var": "port_profiles.vlans"},
    {"input": "root-collection_servers-item-name", "avd_var": "connected_endpoints_keys\\.key.name"},
    {"input": "root-collection_servers-item-collection_adapters-item-type", "avd_var": "connected_endpoints_keys\\.key.adapters.type"},
    {"input": "root-collection_servers-item-collection_adapters-item-endpoint_ports", "avd_var": "connected_endpoints_keys\\.key.adapters.endpoint_ports"},
    {"input": "root-collection_servers-item-collection_adapters-item-switch_ports", "avd_var": "connected_endpoints_keys\\.key.adapters.switch_ports"},
    {"input": "root-collection_servers-item-collection_adapters-item-switches", "avd_var": "connected_endpoints_keys\\.key.adapters.switches"},
    {"input": "root-collection_servers-item-collection_adapters-item-profile", "avd_var": "connected_endpoints_keys\\.key.adapters.profile"},
    {"input": "root-collection_servers-item-collection_adapters-item-port_channel", "avd_var": "connected_endpoints_keys\\.key.adapters.port_channel"},
    {"input": "root-network_services_keys__name", "avd_var": "tenants"},
]
