---
# Verifying we can encrypt passwords
encrypt_passwords: true

# bgp peer groups passwords - password in clear will be auto encrypted
bgp_peer_groups:
  ipv4_underlay_peers:
    name: UNDERLAY-PEERS
    password: arista
  evpn_overlay_peers:
    password: arista
  mlag_ipv4_underlay_peer:
    name: MLAG-PEERS
    password: arista
