---
# Verifying we don'tencrypt passwords
encrypt_passwords: false

# bgp peer groups passwords
bgp_peer_groups:
  ipv4_underlay_peers:
    name: UNDERLAY-PEERS
    password: "0nsCUm70mvSTxVO0ldytrg=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  mlag_ipv4_underlay_peer:
    name: MLAG-PEERS
    password: "15AwQNBEJ1nyF/kBEtoAGw=="
---
# The group is composed of two nodes, one where encrypt_passwords is enabled
# and one where it is disabled to see the interactions.

type: l3leaf

# The next key is defined in the host_vars because
# bgp_peer_groups:

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.66.0/24
    vtep_loopback_ipv4_pool: 192.168.142.0/24
    virtual_router_mac_address: 00:11:22:33:44:55
    bgp_as: 666
  node_groups:
    - group: MLAG-GROUP-FUN
      mlag_interfaces: [Ethernet42]
      mlag_peer_ipv4_pool: 192.168.43.0/24
      mlag_peer_l3_ipv4_pool: 192.168.44.0/24
      nodes:
        - name: bgp-encryption-password-encrypt-true
          id: 42
          mgmt_ip: 192.168.42.42/24
        - name: bgp-encryption-password-encrypt-false
          id: 43
          mgmt_ip: 192.168.42.43/24

tenants:
  - name: Tenant_BGP
    mac_vrf_vni_base: 10000
    mac_vrf_id_base: 20000
    redistribute_mlag_ibgp_peering_vrfs: true
    bgp_peer_groups:
      - name: PG-TENANT-LEVEL-TRUE
        password: arista
      - name: PG-TENANT-LEVEL-FALSE
        password: IQ1xyukPoIcBKZmUUQWyGA==
    vrfs:
      - name: Tenant_bgp
        vrf_vni: 100
        vrf_id: 42
        bgp_peer_groups:
          - name: PG-VRF-LEVEL-TRUE
            password: arista
          - name: PG-VRF-LEVEL-FALSE
            password: +8KX3tMSiFtObNqjE03nkw==
        bgp_peers:
          - ip_address: 10.10.10.10
            password: arista
            nodes: [bgp-encryption-password-encrypt-true]
          - ip_address: 10.10.10.20
            peer_group: PG-VRF-LEVEL-TRUE
            nodes: [bgp-encryption-password-encrypt-true]
          - ip_address: 10.10.10.30
            peer_group: PG-TENANT-LEVEL-TRUE
            nodes: [bgp-encryption-password-encrypt-true]
          - ip_address: 10.10.10.10
            password: ND+/7TkHZESMzFun3TyuxA==
            nodes: [bgp-encryption-password-encrypt-false]
          - ip_address: 10.10.10.20
            peer_group: PG-VRF-LEVEL-FALSE
            nodes: [bgp-encryption-password-encrypt-false]
          - ip_address: 10.10.10.30
            peer_group: PG-TENANT-LEVEL-FALSE
            nodes: [bgp-encryption-password-encrypt-false]
        svis:
          - id: 10
            name: Tenant_bgp_201
            enabled: true
