---
# Test that having underlay_ipv6 will not require
# loopback_ipv6_pool for devices that are not underlay_router
underlay_ipv6: true

# Test that having "overlay_routing_protocol_address_family: ipv6"
# will not raise an error for devices that are not underlay_router (issue/2954)
overlay_routing_protocol_address_family: ipv6

# Expicitely disabling management api-http commands
management_eapi:
  enabled: false

# Testing enable_password_settings
enable_password_settings:
  disabled: false
  hash_algorithm: md5
  key: "$6$nXycSRhVPaxRINPL$tM1MNjjRCbFD5di4XWsj8CPkm8Pdwmf9fVqRV015y3DXD4t1vi8CAWQpFP8Vbi9Y2i7.JuFey5UaafXvI6quD1"
