type: wan_router

# fabric_evpn_encapsulation: vxlan
# overlay_routing_protocol: ebgp
# evpn_overlay_bgp_rtc: true

# l3leaf:
#   defaults:
#     loopback_ipv4_pool: 169.254.112.0/24
#     vtep_loopback_ipv4_pool: 169.253.103.0/24
#     virtual_router_mac_address: 00:1c:73:00:00:99
#     bgp_as: 65233
#   nodes:
#     - name: overlay_evpn_ebgp
#       id: 11
#       platform: vEOS
#       mlag: false
#       mgmt_ip: 192.168.0.205/24
#       evpn_role: none
#       overlay_address_families: [ evpn ]

# enabling EVPN on LAN
overlay_routing_protocol: ebgp
wan_use_evpn_node_settings_for_lan: true

bgp_as: 65000

cv_pathfinder_regions:
  - name: AVD_Land_West
    id: 42
    description: AVD Region
    sites:
      - name: Site422
        id: 422
        location: Somewhere

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.255.0/24

wan_ipsec_profiles:
  control_plane:
    shared_key: ABCDEF1234567890
  data_plane:
    shared_key: ABCDEF1234567890666

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 192.168.255.0/24
    wan_role: client
  nodes:
    - name: ebgp_overlay_evpn_false
      cv_pathfinder_region: AVD_Land_West
      cv_pathfinder_site: Site422
      evpn_role: none
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: ATT
          ip_address: dhcp

wan_path_groups:
  - name: INET
    id: 101

wan_carriers:
  - name: ATT
    path_group: INET
    trusted: true
