---
type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.253.0/24
    loopback_ipv4_offset: 8
    vtep_loopback_ipv4_pool: 192.168.252.0/24
  nodes:
    - name: network-services-l2vlan-svi-address-locking
      id: 10
      bgp_as: 11

tenants:
  - name: TENANT1
    mac_vrf_vni_base: 10000
    l2vlans:
      - id: 10
        name: test-address-locking-1
        address_locking:
          address_family:
            ipv4: true
          ipv4_enforcement_disabled: true
  - name: TENANT2
    mac_vrf_vni_base: 10001
    vrfs:
      - name: TEST_VRF
        vrf_vni: 789654
        svis:
          - id: 2
            name: test-address-locking-2
            enabled: true
            address_locking:
              address_family:
                ipv6: true
