---
# This tests the SNMP auto engine ID calculation for the method specified
# as the default mgmt method.
# This also test support for other interfaces, like loopback being specified
# as the inband mgmt interface.
type: l2leaf

l2leaf:
  nodes:
    - name: SNMP_AUTOGEN_ENGINEID_RFC3411_HOSTNAME_DEFAULT_MGMT
      id: 43
      inband_mgmt_ip: 192.168.0.10/24

default_mgmt_method: inband
inband_mgmt_interface_vrf: MGMT
inband_mgmt_gateway: 192.168.0.10/24

snmp_settings:
  contact: example@example.com
  location: true
  compute_local_engineid: true
  compute_local_engineid_rfc3411: true
  # The default value is hostname_and_ip
  # Since inband_mgmt_method is set to inband, it should
  # automatically try to use hostname_inband_ip
  # compute_local_engineid_source: hostname_and_ip
  compute_v3_user_localized_key: true
  users:
    - name: usertest-auth-priv
      group: usergroup
      version: v3
      auth: sha
      auth_passphrase: clearauth # to get from vault in real life
      priv: aes192
      priv_passphrase: clearpriv # to get from vault in real life
