---
all:
  children:
    IGNORE_IN_PYTEST:
      hosts:
        host_inline_jinja:
    EOS_DESIGNS_DEPRECATED_VARS:
      hosts:
        host_inline_jinja:
        host1:
        host2:
    TENANTS:
      children:
        EOS_DESIGNS_DEPRECATED_VARS:
