#!/bin/sh

# Create a link to this file at .git/hooks/pre-commit to
# force YAML validation prior to committing:
#
# $ ln -s -f ../../.github/lint-yaml .git/hooks/pre-commit

exec 1>&2

echo "Validating YAML for tasks in roles..."
find ansible_collections/arista/avd/roles/*/tasks -type f -name '*.yml' -exec yamllint -c .github/yamllintrc {} \;

echo "Validating YAML for defaults var in roles..."
find ansible_collections/arista/avd/roles/*/defaults/ -type f -name '*.yml' -exec yamllint -c .github/yamllintrc {} \;

echo "Validating YAML for Ansible Galaxy file..."
find ansible_collections/arista/avd/galaxy.yml -type f -name '*.yml' -exec yamllint -c .github/yamllintrc {} \;