#!/bin/sh

# Create a link to this file at .git/hooks/pre-commit to
# force YAML validation prior to committing:
#
# $ ln -s -f ../../.github/lint-yaml .git/hooks/pre-commit

exec 1>&2

echo "------------------------------------------------------------------------------------------------------------"
echo "Validating YAML files in AVD collection ..."
echo "------------------------------------------------------------------------------------------------------------"
yamllint --strict -c .github/yamllintrc \
    ansible_collections/arista/avd/roles/*/tasks \
    ansible_collections/arista/avd/roles/*/defaults/ \
    ansible_collections/arista/avd/roles/*/handlers/ \
    ansible_collections/arista/avd/galaxy.yml \
    ansible_collections/arista/avd/molecule/*

echo "------------------------------------------------------------------------------------------------------------"

