---
## AAA Accounting with logging-only methods and without command groups
aaa_accounting:
  exec:
    console:
      type: start-stop
      methods:
        - method: logging
  system:
    default:
      type: start-stop
      methods:
        - method: logging
  commands:
    console:
      - commands: all
        type: none
      - commands: 0
        type: none
      - commands: 1
        type: start-stop
        methods:
          - method: logging
    default:
      - commands: all
        type: none
      - commands: 0
        type: none
