# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  flow_tracking_settings:
    description: |-
      Define the flow tracking parameters for this topology.
    type: dict
    $ref: eos_cli_config_gen#/keys/flow_tracking
    keys:
      hardware:
        type: dict
        keys:
          trackers:
            type: list
            default:
              - name: FLOW-TRACKER
                record_export:
                  on_inactive_timeout: 70000
                  on_interval: 300000
                exporters:
                  - name: CV-TELEMETRY
                    collector:
                      host: 127.0.0.1
                    local_interface: Loopback0
                    template_interval: 3600000
