---
# CodeCov Configuration for AVD
# Reference: https://docs.codecov.com/docs/codecov-yaml

flags:
  pyavd_tests:
    paths:
      - "python-avd/"
    carryforward: true
  e2e_tests:
    paths:
      - "python-avd/pyavd/"
    carryforward: true
  ansible_tests:
    paths:
      - "ansible_collections/arista/avd/plugins/"
    carryforward: false

coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default: false
      pyavd:
        target: auto
        threshold: 0.5%
        paths:
          - "python-avd/pyavd/"
        flags:
          - pyavd_tests
          - e2e_tests
      schema_tools:
        target: auto
        threshold: 0.5%
        paths:
          - "python-avd/schema_tools/"
        flags:
          - pyavd_tests
      ansible_plugins:
        target: auto
        threshold: 0.5%
        paths:
          - "ansible_collections/arista/avd/plugins/"
        flags:
          - ansible_tests
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "reach,diff,components,flags,files"
  behavior: default
  require_changes: true

component_management:
  individual_components:
    - component_id: pyavd
      name: pyavd
      paths:
        - "python-avd/pyavd/"
    - component_id: schema_tools
      name: schema_tools
      paths:
        - "python-avd/schema_tools/"
    - component_id: ansible_plugins
      name: Ansible plugins
      paths:
        - "ansible_collections/arista/avd/plugins/"

ignore:
  # Test directories
  - "python-avd/tests/**/*"
  - "ansible_collections/arista/avd/tests/**/*"
  - "ansible_collections/arista/avd/extensions/molecule/**/*"

  # Documentation
  - "docs/**/*"
  - "ansible_collections/arista/avd/docs/**/*"

  # Examples
  - "ansible_collections/arista/avd/examples/**/*"

  # Ignore checked-in generated code
  # Unchecked files are not supported by codecov
  - "python-avd/pyavd/_eos_cli_config_gen/schema/__init__.py"
  - "python-avd/pyavd/_eos_designs/schema/__init__.py"
  - "python-avd/pyavd/_eos_designs/eos_designs_facts/schema/protocol.py"
  - "python-avd/pyavd/_cv/api/**/*"
  # This utils module use an integration with CV and is ignored for now
  - "python-avd/pyavd/_eos_designs/structured_config/network_services/utils_zscaler.py"

  # Coverage report files
  - "python-avd/**/coverage.xml"
