sonar.projectKey=aristanetworks_avd
sonar.organization=aristanetworks-1

# Path to sources
sonar.sources=\
    python-avd/,\
    ansible_collections/arista/avd/plugins/

# Exclude generated code
sonar.exclusions=\
    python-avd/tests/**,\
    python-avd/pyavd/_eos_cli_config_gen/schema/__init__.py,\
    python-avd/pyavd/_eos_designs/schema/__init__.py,\
    python-avd/pyavd/_eos_designs/eos_designs_facts/schema/protocol.py,\
    python-avd/pyavd/_cv/schema/__init__.py,\
    python-avd/pyavd/_cv/api/**,\
    python-avd/**/coverage.xml,\

# disable SCM exclusions to get the compiled templates
sonar.scm.exclusions.disabled=true

# Exclude compiled templates from duplication detection
sonar.cpd.exclusions=\
    python-avd/pyavd/_eos_cli_config_gen/j2templates/compiled_templates/**,\
    python-avd/pyavd/_eos_designs/j2templates/compiled_templates/**

# Path to tests
sonar.tests=\
    python-avd/tests/,\

# Python version
sonar.python.version=\
    3.10,\
    3.11,\
    3.12,\
    3.13,\
    3.14

sonar.python.coverage.reportPaths=\
    coverage.xml,\
    ansible_collections/arista/avd/*coverage.xml

sonar.coverage.exclusions=\
    ansible_collections/arista/avd/plugins/**

# Ignore issues on all compiled templates using regex match
sonar.issue.ignore.allfile=e1
sonar.issue.ignore.allfile.e1.fileRegexp=^name = .*\.j2\'$

# Ignore the requirements to check in lock file for pyproject.toml
sonar.issue.ignore.multicriteria=ignore_s8565_pyproject
sonar.issue.ignore.multicriteria.ignore_s8565_pyproject.ruleKey=text:S8565
sonar.issue.ignore.multicriteria.ignore_s8565_pyproject.resourceKey=**/pyproject.toml
