[tox]
# env_list defines which environments are run by default skipping the pyavd-utils one on purpose.
env_list =
    py310
    py311
    py312
    coverage
    report

depends =
    report: coverage

[gh-actions]
python =
  3.10: py310
  3.11: coverage
  3.12: py312
  3.13: py313

[testenv]
# We have multiple packages so we skip installing them and install them as editables in deps instead
skip_install=true
description= Running pyavd & pyavd-utils tests
deps=
    # Forcing pyavd-utils to be built from Rust by installing from source
    -epyavd-utils
    # Forcing pyavd dependencies to be installed by installing pyavd from source
    -epython-avd
dependency_groups =
    pytest
commands =
    # posargs allows to run only a specific test using
    # tox -e <env> -- path/to/my/test::test
    pytest {posargs}

[testenv:coverage]
description= Running coverage
dependency_groups =
    pytest
    coverage
commands =
    coverage erase
    # posargs allows to run only a specific test using
    # tox -e <env> -- path/to/my/test::test
    coverage run -m pytest {posargs}
    # Since we run coverage with the parallel option, it may create multiple files which should be combined before reporting.
    coverage combine

[testenv:report]
description= Generate coverage report
dependency_groups =
    coverage
commands =
    coverage report
    coverage xml

[testenv:pyavd-utils-wheel]
# Used as the package environment
package_glob=pyavd-utils/dist/*

[testenv:pyavd-utils]
# The purpose of this environment is to have smaller footprint one for pyavd-utils only.
description= Running pyavd-utils tests against the pre-built wheel
# overwrite from default
skip_install=false
dependency_groups=

# Configure tox to use the external wheel found by the 'pyavd-utils-wheel' env
package=external
package_env=pyavd-utils-wheel

deps=
    pytest
    # Adding unused pytest-asyncio to avoid warning because
    # of centralized pytest configuration for AVD repo.
    pytest-asyncio
commands =
    # posargs allows to run only a specific test using
    # tox -e <env> -- path/to/my/test::test
    # Need to overwrite the pythonpath from pyproject.toml otherwise the wrong pyavd-utils is used..
    pytest pyavd-utils/tests -o pythonpath="python-avd" {posargs}
