[tox]
skipsdist = True  # since there's no top-level package
env_list =
    py310
    py311
    py312
    coverage
    report

depends =
    report: coverage

[gh-actions]
python =
  3.10: py310
  3.11: coverage
  3.12: py312
  3.13: py313

[testenv]
deps=
    # Forcing pyavd-utils to be built from Rust by installing from source
    -epyavd-utils
    # Forcing pyavd dependencies to be installed by installing pyavd from source
    -epython-avd
dependency_groups =
    pytest
commands =
    # posargs allows to run only a specific test using
    # tox -e <env> -- path/to/my/test::test
    pytest {posargs}

[testenv:coverage]
dependency_groups =
    pytest
    coverage
commands =
    coverage erase
    # posargs allows to run only a specific test using
    # tox -e <env> -- path/to/my/test::test
    coverage run -m pytest {posargs}
    # Since we run coverage with the parallel option, it may create multiple files which should be combined before reporting.
    coverage combine

[testenv:report]
skip_install = true
dependency_groups =
    coverage
commands =
    coverage report
    coverage xml
