[tox]
env_list =
    py310
    py311
    py312
    py313
    py314
    coverage
    report

depends =
    report: coverage

[gh-actions]
python =
  3.10: py310
  3.11: coverage
  3.12: py312
  3.13: py313
  3.14: py314

[testenv]
# We have multiple packages so we skip installing them and install them as editables in deps instead
# Really we should move the file now that pyavd-utils is gone
skip_install=true
deps=
    # Forcing pyavd dependencies to be installed by installing pyavd from source
    -epython-avd
description= Running pyavd tests
dependency_groups =
    pytest
commands =
    # posargs allows to run only a specific test using
    # tox run -e <env> -- path/to/my/test::test
    pytest {posargs}

[testenv:coverage]
description= Running coverage
dependency_groups =
    pytest
    coverage
commands =
    coverage erase
    # posargs allows to run only a specific test using
    # tox run -e <env> -- path/to/my/test::test
    coverage run -m pytest {posargs}
    # Since we run coverage with the parallel option, it may create multiple files which should be combined before reporting.
    coverage combine

[testenv:report]
description= Generate coverage report
dependency_groups =
    coverage
commands =
    coverage report
    coverage xml
