---
fabric_name: FABRIC_MLAG_INTERFACES_COUNT_MISMATCH
underlay_routing_protocol: isis

type: l2leaf

l2leaf:
  defaults:
    mlag_peer_vlan: 4094
    mlag_peer_l3_vlan: 4094
    mlag_peer_ipv4_pool: 10.10.255.0/24
    uplink_ipv4_pool: 10.10.101.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    platform: vEOS-LAB
  node_groups:
    - group: mlag-interfaces-count-mismatch
      nodes:
        - name: mlag-interfaces-count-mismatch1
          id: 51
          mgmt_ip: 192.168.201.251/24
          uplink_switch_interfaces: [Ethernet61]
          mlag_interfaces: [Ethernet5, Ethernet6]
        - name: mlag-interfaces-count-mismatch2
          id: 52
          mgmt_ip: 192.168.201.252/24
          uplink_switch_interfaces: [Ethernet62]
          mlag_interfaces: [Ethernet5]

expected_error_message: >-
  Inconsistent number of 'mlag_interfaces' defined for MLAG peer 'mlag-interfaces-count-mismatch2' for host 'mlag-interfaces-count-mismatch1'.
