---
fabric_name: FABRIC_MLAG_L3_VLAN_MISMATCH
underlay_routing_protocol: isis

type: l3leaf

l3leaf:
  defaults:
    mlag_peer_vlan: 4094
    mlag_peer_l3_vlan: 4094
    mlag_peer_l3_ipv4_pool: 10.10.254.0/24
    mlag_peer_ipv4_pool: 10.10.255.0/24
    uplink_ipv4_pool: 10.10.101.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    platform: vEOS-LAB
  node_groups:
    - group: mlag-l3-vlan-mismatch
      nodes:
        - name: mlag-l3-vlan-mismatch1
          id: 61
          bgp_as: 65161
          mgmt_ip: 192.168.201.261/24
          uplink_switch_interfaces: [Ethernet71]
          mlag_interfaces: [Ethernet5, Ethernet6]
        - name: mlag-l3-vlan-mismatch2
          id: 62
          bgp_as: 65161
          mgmt_ip: 192.168.201.262/24
          uplink_switch_interfaces: [Ethernet72]
          mlag_interfaces: [Ethernet5, Ethernet6]
          mlag_peer_l3_vlan: 4093

expected_error_message: >-
  Inconsistent MLAG L3 VLAN with MLAG peer 'mlag-l3-vlan-mismatch2'.
  Local 'mlag_peer_l3_vlan' resolves to 'None' while peer resolves to '4093' for host 'mlag-l3-vlan-mismatch1'.
