---
fabric_name: DIGITAL_TWIN_CONTAINERLAB

management_eapi:
  enabled: true

eos_designs_documentation:
  enable: false
  topology_csv: false
  p2p_links_csv: false

digital_twin:
  environment: containerlab
  fabric: {}
