---
type: l3leaf

mgmt_gateway: 192.168.200.1

# bgp peer groups
bgp_peer_groups:
  ipv4_underlay_peers:
    name: IPv4-UNDERLAY-PEERS
  mlag_ipv4_underlay_peer:
    name: MLAG-PEERS
    password: "15AwQNBEJ1nyF/kBEtoAGw=="
  mlag_ipv4_vrfs_peer:
    name: MLAG-PEERS
    bfd: false
    structured_config:
      description: Description for mlag_ipv4_vrfs_peer via structured_config
