---
tenants:
  - name: TEST
    vrfs:
      - name: default
        vrf_id: 100
        address_families: []
        l3_port_channels:
          - name: Port-Channel11
            node: host1
            flow_tracking:
              enabled: true
              name: FT_Test
