---
tenants:
  - name: TEST
    vrfs:
      - name: default
        vrf_id: 100
        address_families: []
        l3_interfaces:
          - interfaces:
              - Ethernet47
            ip_addresses:
              - 10.10.1.1/30
            nodes:
              - host1
        l3_port_channels:
          - name: Port-Channel11
            node: host1
            flow_tracking:
              enabled: true
              name: FT_Test
