---
# Inventory Organisation How-To Guide
# Fabric-wide settings that apply to all devices in this topology.
# In a Medium or larger topology this file lives in its own group folder.

fabric_name: FABRIC  # (1)!

underlay_routing_protocol: ebgp  # (2)!
overlay_routing_protocol: ebgp  # (3)!

bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
