---
# deploy.yml
- name: Deploy Configurations via CVaaS
  hosts: WAN
  gather_facts: false
  tasks:
    - name: Deploy Configurations to Devices
      vars:
        # Automatically execute the Change Control
        cv_run_change_control: true
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
