---

pod_name: L2LS_BGP

underlay_routing_protocol: ebgp

tenants:
  - name: L2LS_BGP
    vrfs:
      - name: default
        svis:
          - id: 1
            name: SVI_1
            ip_address_virtual: 10.1.1.1/24
            enabled: true
          - id: 100
            name: SVI_100
            ip_address_virtual: 10.1.100.1/24
            enabled: true
          - id: 200
            name: SVI_200
            ip_address_virtual: 10.1.200.1/24
            enabled: true
          - id: 220
            name: SVI_220
            ip_address_virtual: 10.1.220.1/24
            enabled: true
        static_routes: # Testing creation of static route in default VRF including redistribute static under the underlay protocol
          - prefix: 10.0.0.0/8
            next_hop: 10.1.100.100
            nodes: [ BGP-SPINE2 ]
        l3_interfaces:
          - interfaces:
              - Ethernet6
              - Ethernet6
            ip_addresses:
              - "10.0.1.0/31"
              - "10.0.1.2/31"
            nodes:
              - BGP-SPINE1
              - BGP-SPINE2

network_ports:
  - switches:
      - "BGP-LEAF[1-3]"
    switch_ports:
      - "Ethernet10-11"
    vlans: 100
    mode: access
    description: Endpoint
  - switches:
      - "BGP-LEAF1"
    switch_ports:
      - "Ethernet12-13"
    native_vlan: 100
    phone_vlan: 200
    phone_trunk_mode: untagged
    mode: trunk phone
    description: IP Phone
  - switches:
      - "BGP-LEAF1"
    switch_ports:
      - "Ethernet14"
    phone_vlan: 200
    phone_trunk_mode: untagged
    mode: trunk phone
    description: IP Phone with no native VLAN
  - switches:
      - "BGP-SPINE[1-2]"
    switch_ports:
      - "Ethernet10"
    campus_egress: true
  - switches:
      - "BGP-SPINE[1-2]"
    switch_ports:
      - "Ethernet11"
core_interfaces:
  p2p_links:
    - subnet: 192.168.253.4/31
      nodes: [ BGP-SPINE1, DUMMY-CORE ]
      interfaces: [ Ethernet5, Ethernet1/3 ]
      as: [ 65001, 65000 ]
    - subnet: 192.168.253.6/31
      nodes: [ BGP-SPINE2, DUMMY-CORE ]
      interfaces: [ Ethernet5, Ethernet1/4 ]
      as: [ 65001, 65000 ]

firewalls:
  - name: CAMPUS_EGRESS_FW_1
    adapters:
      - endpoint_ports: [ Eth0, Eth1 ]
        switch_ports: [Ethernet7, Ethernet7]
        switches: [BGP-SPINE1, BGP-SPINE2]
        port_channel:
          mode: active
        campus_egress: true
      - endpoint_ports: [ Eth2, Eth3 ]
        switch_ports: [Ethernet8, Ethernet8]
        switches: [BGP-SPINE1, BGP-SPINE2]
        port_channel:
          mode: active
      - endpoint_ports: [ Eth4 ]
        switch_ports: [Ethernet9]
        switches: [BGP-SPINE1]
        campus_egress: true
      - endpoint_ports: [ Eth5 ]
        switch_ports: [Ethernet9]
        switches: [BGP-SPINE2]

generate_cv_tags:
  topology_hints: true
  campus_fabric: true

campus: City_A
