# Copyright (c) 2023-2025 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class AvdDeviceTag:
    """Input device tag generated by AVD."""

    label: str
    value: str


@dataclass(frozen=True)
class AvdInterfaceTag:
    """Input interface tag generated by AVD for a particular device."""

    label: str
    value: str
    interface: str


@dataclass(frozen=True)
class AvdPathfinderMetadata:
    """Input Pathfinder metadata generated by AVD."""

    metadata: dict[str, Any]


@dataclass(frozen=True)
class AvdEosConfig:
    """Input EOS config generated by AVD for a particular device."""

    file: str
    """Path to file containing EOS Config"""
    configlet_name: str | None = None
    """By default "AVD_<hostname>"""


# TODO: Migrate rest of the input models such as AvdWorkspace, AvdStudioInputs
