---
- name: Converge
  hosts: TWODC_5STAGE_CLOS
  gather_facts: false
  connection: local
  tasks:

    - name: Generate intended variables
      delegate_to: 127.0.0.1
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

- name: Converge
  hosts: TWODC_5STAGE_CLOS
  gather_facts: false
  connection: local
  vars:
    output_dir_name: "digital_twin/intended"
    documentation_dir_name: "digital_twin/documentation"
    avd_digital_twin_mode: true
    # Test automatic adjustment of the OOB mgmt interface for the ACT Digital Twin
    mgmt_interface: "Management0"
  tasks:

    - name: Generate intended variables in ACT Digital Twin mode
      delegate_to: 127.0.0.1
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
