---
# Inventory Organisation How-To Guide
# Spine node configuration.

spine:
  defaults:
    platform: cEOSLab  # (1)!
    loopback_ipv4_pool: 10.255.6.0/27  # (2)!
    bgp_as: 65100  # (3)!

  nodes:  # (4)!
    - name: htio-spine1
      id: 1
      mgmt_ip: 172.16.3.11/24
    - name: htio-spine2
      id: 2
      mgmt_ip: 172.16.3.12/24
