---
type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    virtual_router_mac_address: 00:dc:00:00:00:0a
  nodes:
    - name: address-locking-local-interface-and-dhcp-server-interfaces
      id: 101
      bgp_as: 101

address_locking_settings:
  dhcp_server_interfaces:
    - Ethernet1
  local_interface: Management1

expected_error_message: >-
  'address_locking_settings.local_interface' and 'address_locking_settings.dhcp_server_interfaces' are mutually exclusive.
