loopback_ipv4_pool: 192.168.1.0/24

type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: connected-endpoints-monitor-session-network-port-subinterface-destination

network_ports:
  - switches:
      - connected-endpoints-monitor-session-network-port-subinterface-destination
    switch_ports:
      - Ethernet1.100
    monitor_sessions:
      - name: SESSION-ON-SUBINTERFACE-WITH-DESTINATION-ROLE
        role: destination

expected_error_message: >-
  Port mirroring destination on sub-interface is not supported.
  Got 'role: destination' for monitor session 'SESSION-ON-SUBINTERFACE-WITH-DESTINATION-ROLE' on interface 'Ethernet1.100'
  under network_ports[0].
