type: l2leaf

l2leaf:
  nodes:
    - name: custom-system-mac-address-no-device-id
      mgmt_ip: 192.168.0.2/24

custom_system_mac_address: 021c.7300.{device_id:04x}

expected_error_message: >-
  'device_id'
