type: l2leaf

l2leaf:
  nodes:
    - name: custom-system-mac-address-multicast
      id: 1234
      mgmt_ip: 192.168.0.2/24

custom_system_mac_address: 011c.7300.{device_id:04x}

expected_error_message: >-
  custom_system_mac_address rendered '011c.7300.04d2' which is not a valid unicast EOS system MAC address.
  The value must be a unicast MAC address in hhhh.hhhh.hhhh, hh:hh:hh:hh:hh:hh or hh-hh-hh-hh-hh-hh format.
