---
# This host is present in the fabric only to provide peer facts for dhcp-mgmt-ip-cvx-server-1.
# It is excluded from structured config testing via EOS_DESIGNS_FAILURES_EXCLUDED.
type: cvxserver

overlay_routing_protocol: CVX
overlay_cvx_servers: [dhcp-mgmt-ip-cvx-server-1, dhcp-mgmt-ip-cvx-server-2]

node_type_keys:
  - key: cvxserver
    type: cvxserver
    underlay_router: false

cvxserver:
  nodes:
    - name: dhcp-mgmt-ip-cvx-server-2
      id: 4
      mgmt_ip: dhcp
