---
type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: dot1x-aaa-authentication-missing-radius-groups
      mgmt_ip: 192.168.0.2/24

dot1x_settings:
  enabled: true

expected_error_message: >-
  'dot1x_settings.authentication.radius_groups' is required when 802.1X is enabled globally.
