---
# Testing duplicate exporters entry
type: l2leaf

default_mgmt_method: none

cv_settings:
  cvaas:
    enabled: true
    clusters:
      - name: cvaas
        vrf: use_mgmt_interface_vrf

fabric_flow_tracking:
  uplinks:
    enabled: true
    name: FLOW-TRACKER-11

flow_tracking_settings:
  cloudvision_exporter:
    name: Exporter1
    vrf: exporter_vrf
  trackers:
    - name: FLOW-TRACKER-11
      export_to_cloudvision: true
      exporters:
        - name: Exporter1
          collectors:
            - host: 127.0.2.1

l2leaf:
  defaults:
    platform: vEOS-lab
    uplink_interfaces: ['Ethernet1']
    uplink_switches: ['duplicate-neighbors-l3-edge']

  nodes:
    - name: duplicate-cloudvision-exporter
      id: 1
      mgmt_ip: 192.168.0.201/24
      uplink_switch_interfaces:
        - Ethernet15

expected_error_message: >-
  Found conflicting data while generating configuration for cloudvision exporter with name 'Exporter1'. Please check your exporters configuration for tracker
  'FLOW-TRACKER-11' is not conflicting with 'export_to_cv' configuration.
