---
type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    bgp_as: 65101
  nodes:
    - name: evpn-gateway-core-password-missing-peer
      id: 2
      evpn_role: client
      evpn_route_servers: [evpn-gateway-core-password-missing]
      evpn_gateway:
        remote_peers:
          - hostname: evpn-gateway-core-password-missing
