---
type: l3leaf

bgp_peer_groups:
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    bgp_as: 65001
  nodes:
    - name: evpn-gateway-core-password-missing
      id: 1
      evpn_role: server

expected_error_message: >-
  EVPN peer 'evpn-gateway-core-password-missing-peer' uses a same-address CORE session towards this node, while this node returns a regular PEERS
  session. Since PEERS uses authentication, configure 'bgp_peer_groups.evpn_overlay_core.password'. AVD will apply it to the returning PEERS neighbor.
