type: l3leaf

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
  nodes:
    - name: failure-svi-igmp-snooping-querier-source-address-for-diagnostic-loopback
      bgp_as: 65101
      id: 1
      mgmt_ip: 192.168.200.101/24

tenants:
  - name: Tenant_A
    mac_vrf_vni_base: 10000
    igmp_snooping:
      querier:
        enabled: true
        source_address: diagnostic_loopback
    vrfs:
      - name: IGMP_QUERIER_TEST_3
        description: "IGMP_QUERIER_TEST_3"
        vrf_vni: 41
        svis:
          - id: 21
            name: "VLAN_21"
            tags: ['test_l3']

expected_error_message: >-
  Invalid configuration on VRF 'IGMP_QUERIER_TEST_3' in Tenant 'Tenant_A'.
  'vtep_diagnostic.loopback' along with either 'vtep_diagnostic.loopback_ip_pools' or
  'vtep_diagnostic.loopback_ip_range' must be defined when 'igmp_snooping_querier.source_address' is set to 'diagnostic_loopback' on the VRF
  for host 'failure-svi-igmp-snooping-querier-source-address-for-diagnostic-loopback'.
