---
fabric_name: FABRIC_FAILURE_DEVICES_AND_NODE_KEY_1

type: l2leaf

devices:
  - name: failure-devices-and-node-key-1

l2leaf:
  node_groups:
    - group: test
      nodes:
        - name: failure-devices-and-node-key-1

expected_error_message: >-
  Found the device 'failure-devices-and-node-key-1' under both 'l2leaf' and 'devices'.
  Remove the device from one of the models.
