type: l2leaf
l2leaf:
  nodes:
    - name: flow-tracking-missing-tracker
      id: 1
      # Could as well be hardware
      flow_tracker_type: sampled
      uplink_interfaces: [Ethernet2, Ethernet3]
      uplink_switch_interfaces: [Ethernet1, Ethernet2]
      inband_mgmt_vlan: 100
      inband_mgmt_subnet: 192.168.101.0/24
      inband_mgmt_vrf: INBANDMGMT
      # Set to create inband mgmt config for network-services-ip-helpers-leaf1.
      uplink_switches: [network-services-ip-helpers-leaf1, network-services-ip-helpers-leaf1]

fabric_flow_tracking:
  endpoints:
    enabled: true
    name: I-DO-NOT-EXIST

servers:
  - name: test
    adapters:
      - switches: [flow-tracking-missing-tracker]
        switch_ports: [Ethernet1]
        flow_tracking:
          enabled: true

expected_error_message: >-
  The flow tracker 'I-DO-NOT-EXIST' is being used for at least one interface,
  but is not configured in 'self.inputs.flow_tracking_settings'.
