---
mac_acls:
  - name: acl1
    entries:
      - sequence: 10
        action: deny
        source: 01:80:c2:00:00:00
        source_wildcard: 00:01:00:00:00:00
        destination: any
        destination_wildcard: 00:01:00:00:00:00

type: l2leaf

l2leaf:
  nodes:
    - name: invalid-mac-acl-destination-wildcard

servers:
  - name: server1
    rack: RackB
    adapters:
      - endpoint_ports: [E0]
        switch_ports: [Ethernet2]
        switches: [invalid-mac-acl-destination-wildcard]
        mac_acl_in: acl1

expected_error_message: >-
  Can not set 'mac_acls[name=acl1].entries[0].destination_wildcard' when destination is 'any' for host invalid-mac-acl-destination-wildcard.
