type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_ipv4_pool: 10.10.101.0/24
    uplink_switches: [missing-evpn-underlay-l3-multicast-group-ipv4-pool]
    uplink_interfaces: [ Ethernet1 ]
    link_tracking:
      enabled: true
    filter:
      tags: [opzone]
  nodes:
    - name: missing-downlink-group-in-link-tracking-group
      id: 1
      mgmt_ip: 192.168.201.201/24
      uplink_switch_interfaces: [ Ethernet2 ]
      link_tracking:
        downlinks:
          enabled: true
          group: l2leaf-server01

tenants:
  - name: Tenant_X
    mac_vrf_vni_base: 11000
    vrfs:
      - name: Tenant_X_OP_Zone
        vrf_id: 20
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
          loopback_ipv6_range: 2001:db8:1::/48
        svis:
          - id: 310
            name: Tenant_X_OP_Zone_1
            tags: [opzone]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
        bgp:
          router_id: diagnostic_loopback
