---
type: l2leaf

aaa_settings:
  local_users:
    - name: missing-password-username
      privilege: 15
      role: network-admin
      # notice that neither sha512_password, nor cleartext_password nor no_password: true is set.

l2leaf:
  nodes:
    - name: missing-local-user-password-or-no-password-true
      id: 4
expected_error_message: >-
  Either 'sha512_password', 'cleartext_password' or 'no_password: true' must be set for username 'missing-password-username'.
