type: l3leaf
l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    bgp_as: 65101
  nodes:
    - name: missing-validation-parent-profile
      id: 1
      mgmt_ip: 192.168.200.105/24
      validation_profile: profile1

validation_profiles:
  - name: profile1
    parent_profile: profile2
    hardware:
      min_power_supplies: 2

expected_error_message: >-
  Parent validation profile 'profile2' referenced by validation profile 'profile1' is not defined under 'validation_profiles'
  for host 'missing-validation-parent-profile'.
