---
type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: missing-ipv4-address-locking-mode-with-global-disabled

avd_design_future:
  only_configure_address_locking_when_used: true

address_locking_settings:
  disabled: true

servers:
  - name: server
    adapters:
      - switches: [missing-ipv4-address-locking-mode-with-global-disabled]
        switch_ports: [Ethernet1]
        mode: access
        vlans: 10
        address_locking:
          ipv4: true

expected_error_message: >-
  IPv4 address locking is enabled under 'servers[name=server].adapters[0]' but one of the following is required:
  `address_locking_settings.locked_address.ipv4_enforcement_disabled: true`, `address_locking_settings.dhcp_servers_ipv4`
  with `address_locking_settings.local_interface`, or `address_locking_settings.dhcp_server_interfaces` with
  `avd_design_future.fix_address_locking_dhcp_server_interfaces: true`.
