---
type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 8
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    bgp_as: 65101
  nodes:
    - name: overlapping-evpn-route-server-and-gateway-remote-peer
      id: 1
      bgp_as: 65104
      mgmt_ip: 192.168.200.110/24
      evpn_route_servers:
        - explicit-evpn-route-server
      evpn_gateway:
        remote_peers:
          - hostname: explicit-evpn-route-server
            ip_address: 192.168.42.42

expected_error_message: >-
  Cannot configure EVPN Gateway remote peer 'explicit-evpn-route-server' under both 'evpn_gateway.remote_peers' and
  'evpn_route_servers'. Use each inventory hostname in only one of these inputs.
