---
type: l2leaf

l2leaf:
  nodes:
    - name: snmp-settings-missing-system-mac-address-rfc3411-type3
      id: 42

snmp_settings:
  compute_local_engineid: true
  compute_local_engineid_source: rfc3411_type3
  compute_v3_user_localized_key: true
expected_error_message: >-
  'compute_local_engineid_source: rfc3411_type3' requires 'system_mac_address' to be set.
