type: l2leaf
l2leaf:
  nodes:
    - name: ssh-settings-client-duplicate-non-default-vrf
      id: 2
      mgmt_ip: 192.168.0.2/24
      inband_mgmt_ip: 10.20.30.40/24
      inband_mgmt_gateway: 10.20.30.1
      inband_mgmt_vrf: VRF1

mgmt_interface_vrf: VRF1

ssh_settings:
  client_vrfs:
    - name: use_mgmt_interface_vrf
    - name: use_inband_mgmt_vrf

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for Vrfs.
  {'name': 'VRF1', 'source_interface': 'Vlan4092'} conflicts with {'name': 'VRF1', 'source_interface': 'Management1'}.
