aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_LINK_TO_CORE-7-EBGP_Ethernet1
  shutdown: false
  mtu: 1600
  ip_address: 172.16.2.0/31
  ipv6_address: 2001:db8:64:48::/127
  mpls:
    ip: true
  metadata:
    peer: core-7-ebgp
    peer_interface: Ethernet1
    peer_type: core_router
  switchport:
    enabled: false
- name: Ethernet2
  description: P2P_LINK_TO_CORE-7-EBGP_Ethernet2
  shutdown: false
  mtu: 1600
  ip_address: 172.16.3.0/31
  ipv6_address: 2001:db8:64:1234::/127
  mpls:
    ip: true
  metadata:
    peer: core-7-ebgp
    peer_interface: Ethernet2
    peer_type: core_router
  switchport:
    enabled: false
- name: Ethernet3
  description: P2P_LINK_TO_CORE-7-EBGP_Ethernet3
  shutdown: false
  mtu: 1600
  ip_address: 172.16.3.2/31
  ipv6_address: 2001:db8:64:1234::2/127
  mpls:
    ip: true
  metadata:
    peer: core-7-ebgp
    peer_interface: Ethernet3
    peer_type: core_router
  switchport:
    enabled: false
- name: Ethernet4
  description: P2P_LINK_TO_CORE-7-EBGP_Ethernet4
  shutdown: false
  mtu: 1600
  ipv6_address: 2001:db8:64:ff::/127
  mpls:
    ip: true
  metadata:
    peer: core-7-ebgp
    peer_interface: Ethernet4
    peer_type: core_router
  switchport:
    enabled: false
- name: Ethernet5
  description: P2P_LINK_TO_CORE-7-EBGP_Ethernet5
  shutdown: false
  mtu: 1600
  ipv6_address: 2001:db8:64:5000::0/127
  mpls:
    ip: true
  metadata:
    peer: core-7-ebgp
    peer_interface: Ethernet5
    peer_type: core_router
  switchport:
    enabled: false
hostname: core-6-ebgp
ip_routing: true
ipv6_prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY-V6
  sequence_numbers:
  - sequence: 10
    action: permit 2000:1234:ffff:ffff::/64 eq 128
ipv6_unicast_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.0.0.7/32
  ipv6_address: 2000:1234:ffff:ffff::7/128
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.0.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 30
    type: permit
    match:
    - ipv6 address prefix-list PL-LOOPBACKS-EVPN-OVERLAY-V6
router_bgp:
  as: '65000'
  router_id: 10.0.0.7
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    metadata:
      type: ipv4
    send_community: all
    maximum_routes: 256000
  neighbors:
  - ip_address: 172.16.2.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65107'
    local_as: '65106'
    metadata:
      peer: core-7-ebgp
    description: core-7-ebgp
  - ip_address: 172.16.3.1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65107'
    local_as: '65106'
    metadata:
      peer: core-7-ebgp
    description: core-7-ebgp
  - ip_address: 172.16.3.3
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65107'
    local_as: '65106'
    metadata:
      peer: core-7-ebgp
    description: core-7-ebgp
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  address_family_ipv6:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 192.168.0.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
