aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: custom-system-mac-address-with-snmp
ip_igmp_snooping:
  globally_enabled: true
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.4/24
  type: oob
metadata:
  is_deployed: true
  system_mac_address: 021c.7300.0004
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: f5717f021c7300000400
system:
  mac_address: 021c.7300.0004
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
