aaa_root:
  disabled: true
config_end: true
dhcp_relay:
  tunnel_requests_disabled: true
enable_password:
  disabled: true
hostname: dhcp-relay-vtep
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.101/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.101/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '101'
  router_id: 192.168.255.101
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 101
    metadata:
      tenants:
      - TENANT1
    rd: 192.168.255.101:10101
    route_targets:
      both:
      - 10101:10101
    redistribute_routes:
    - learned
  - id: 102
    metadata:
      tenants:
      - TENANT1
    rd: 192.168.255.101:10102
    route_targets:
      both:
      - 10102:10102
    redistribute_routes:
    - learned
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 101
  name: dhcp-relay-1
  metadata:
    tenants:
    - TENANT1
- id: 102
  name: dhcp-relay-2
  metadata:
    tenants:
    - TENANT1
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: dhcp-relay-vtep_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 101
        vni: 10101
      - id: 102
        vni: 10102
