aaa_root:
  disabled: true
config_end: true
dns_domain: testfabric.local
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet5
  description: L2_cv-settings_Ethernet1
  shutdown: false
  channel_group:
    id: 5
    mode: active
  metadata:
    peer: cv-settings
    peer_interface: Ethernet1
    peer_type: l2leaf
hostname: dns-settings-1
ip_domain_lookup:
  source_interfaces:
  - name: Vlan123
  - name: Management1
    vrf: MGMT
ip_igmp_snooping:
  globally_enabled: true
ip_name_server:
  vrfs:
  - name: default
    servers:
    - ip_address: 10.10.10.1
      priority: 1
  - name: MGMT
    servers:
    - ip_address: 10.10.10.1
      priority: 1
    - ip_address: 10.10.10.2
    - ip_address: 10.10.10.3
  - name: other_vrf
    servers:
    - ip_address: 10.10.10.2
ip_routing: false
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.2/24
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
port_channel_interfaces:
- name: Port-Channel5
  description: L2_cv-settings_Port-Channel1
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: '4092'
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
