aaa_accounting:
  dot1x:
    default:
      type: start-stop
      methods:
      - multicast: false
        method: group
        group: agni-server-group
      - multicast: false
        method: group
        group: radius
aaa_authentication:
  dot1x:
    default: group agni-server-group group radius
aaa_root:
  disabled: true
aaa_server_groups:
- name: agni-server-group
  type: radius
  servers:
  - server: agni.arista.com
    vrf: MGMT
config_end: true
dot1x:
  system_auth_control: true
  protocol_lldp_bypass: true
  protocol_bpdu_bypass: true
  dynamic_authorization: true
  radius_av_pair:
    dhcp:
      hostname:
        enabled: true
        auth_only: false
      parameter_request_list:
        enabled: true
        auth_only: true
      vendor_class_id:
        enabled: true
        auth_only: true
enable_password:
  disabled: true
hostname: dot1x-settings-4
ip_igmp_snooping:
  globally_enabled: true
ip_radius:
  vrfs:
  - name: MGMT
    source_interface: Management1
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.2/24
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
radius_server:
  vrfs:
  - name: MGMT
    servers:
    - host: agni.arista.com
      key: 1404071B09166738212B2130365E0C131A
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
