aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: evpn-gateway-remote-peer-without-evpn-ignored
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:00:99
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.8/32
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.211/24
  type: oob
metadata:
  is_deployed: true
  platform: vEOS
  fabric_name: EOS_DESIGNS_UNIT_TESTS
  validate_hardware:
    enabled: false
router_bgp:
  as: '65233'
  router_id: 192.168.255.8
  maximum_paths:
    paths: 4
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
