aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  shutdown: false
  ip_address: 2001:db8:172:16::2/127
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet1
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet1
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet2
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet2
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet2
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet3
  shutdown: false
  ip_address: dhcp
  dhcp_client_accept_default_route: true
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-NO-FIELDS-IN
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-NO-FIELDS-OUT
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet4
  shutdown: false
  ip_address: 2001:db8:172:19::/127
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-NO-FIELDS-IN
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-NO-FIELDS-OUT
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet5/1
  shutdown: false
  ip_address: 2001:db8:172:20::/127
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet5_1
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet6/6.6
  shutdown: false
  encapsulation_dot1q:
    vlan: 6
  ip_address: 2001:db8:172:21::/127
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet6_6.6
  metadata:
    peer_type: l3_interface
- name: Ethernet6/6
  shutdown: false
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
hostname: ipv6-acls
ip_routing: true
ipv6_access_lists:
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet1
  entries:
  - protocol: ip
    source: any
    destination: 2001:db8:172:16::2
    sequence: 15
    action: deny
  - protocol: ip
    source: 2001:db8:172:16::1/127
    destination: 2001:db8:172:16::2
    action: permit
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet1
  entries:
  - remark: Some remark will not require source and destination fields.
  - protocol: ip
    source: 2001:db8:172:16::2
    destination: any
    action: permit
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet2
  entries:
  - protocol: ip
    source: any
    destination: 2001:db8:1::1
    sequence: 15
    action: deny
  - protocol: ip
    source: 2001:db8:1::2
    destination: 2001:db8:1::1
    action: permit
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet2
  entries:
  - remark: Some remark will not require source and destination fields.
  - protocol: ip
    source: 2001:db8:1::1
    destination: any
    action: permit
- name: TEST-IPV6-ACL-WITH-NO-FIELDS-IN
  entries:
  - protocol: ip
    source: 172.18.18.18
    destination: any
    action: permit
- name: TEST-IPV6-ACL-WITH-NO-FIELDS-OUT
  entries:
  - protocol: ip
    source: 172.18.18.18
    destination: any
    action: permit
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-IN_Ethernet5_1
  entries:
  - protocol: ip
    source: any
    destination: '2001:db8:172:20::'
    sequence: 15
    action: deny
  - protocol: ip
    source: 2001:db8:172:20::1/127
    destination: '2001:db8:172:20::'
    action: permit
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet6_6.6
  entries:
  - remark: Some remark will not require source and destination fields.
  - protocol: ip
    source: '2001:db8:172:21::'
    destination: any
    action: permit
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.0.1/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.0.1
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
