aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: P2P_IPV6_DOWNLINK_POOLS_LEAF1a_Ethernet1
  shutdown: false
  mtu: 9214
  ipv6_addresses:
  - 2001:db8:12::1/64
  metadata:
    peer: IPV6_DOWNLINK_POOLS_LEAF1a
    peer_interface: Ethernet1
    peer_type: l3leaf
  switchport:
    enabled: false
hostname: IPV6_DOWNLINK_POOLS_SPINE
ip_routing: true
ipv6_prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY-V6
  sequence_numbers:
  - sequence: 10
    action: permit 2001:db8::/48 eq 128
ipv6_unicast_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ipv6_address: 2001:db8::1/128
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.35/24
  type: oob
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: EOS_DESIGNS_UNIT_TESTS
  validate_hardware:
    enabled: false
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 30
    type: permit
    match:
    - ipv6 address prefix-list PL-LOOPBACKS-EVPN-OVERLAY-V6
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65100'
  router_id: 10.255.0.1
  maximum_paths:
    paths: 4
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    metadata:
      type: ipv6
    send_community: all
    maximum_routes: 256000
  - name: EVPN-OVERLAY-PEERS
    metadata:
      type: evpn
    next_hop_unchanged: true
    update_source: Loopback0
    bfd: true
    ebgp_multihop: 3
    send_community: all
    maximum_routes: 0
  neighbors:
  - ip_address: 2001:db8:12::2
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    metadata:
      peer: IPV6_DOWNLINK_POOLS_LEAF1a
    description: IPV6_DOWNLINK_POOLS_LEAF1a_Ethernet1
  - ip_address: 2001:db8:13::1
    peer_group: EVPN-OVERLAY-PEERS
    remote_as: '65101'
    metadata:
      peer: IPV6_DOWNLINK_POOLS_LEAF1a
    description: IPV6_DOWNLINK_POOLS_LEAF1a_Loopback0
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_evpn:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: EVPN-OVERLAY-PEERS
      activate: false
  address_family_ipv6:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
