aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  shutdown: false
  ip_address: 172.16.0.2/30
  ipv6_access_group_in: TEST-IPV6-ACL-IN
  ipv6_access_group_out: TEST-IPV6-ACL-OUT
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet4
  shutdown: false
  ip_address: 172.19.19.0/31
  ipv6_access_group_in: TEST-IPV6-ACL-IN
  ipv6_access_group_out: TEST-IPV6-ACL-OUT
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
hostname: ipv6-acls
ip_routing: true
ipv6_access_lists:
- name: TEST-IPV6-ACL-IN
  sequence_numbers:
  - sequence: 15
    action: allow
- name: TEST-IPV6-ACL-OUT
  sequence_numbers:
  - sequence: 15
    action: deny
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.0.1/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.0.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 192.168.0.1
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
