aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: ipv6-router-ospf-default-vrf
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ipv6_router_ospf:
  process_ids:
  - id: 101
    router_id: 192.168.255.110
    redistribute:
      bgp:
        enabled: true
      connected:
        enabled: true
        route_map: ipv6_ospf_rm
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.110/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.110/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '102'
  router_id: 192.168.255.110
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 201
    metadata:
      tenants:
      - Tenant_A
    rd: 192.168.255.110:10201
    route_targets:
      both:
      - 10201:10201
    redistribute_routes:
    - learned
  vrfs:
  - name: default
    rd: 192.168.255.110:2
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '2:2'
      export:
      - address_family: evpn
        route_targets:
        - '2:2'
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan201
  description: default_201 description
  shutdown: false
  ipv6_enable: true
  ipv6_addresses:
  - cafe::cafe/64
  ipv6_ospf:
    process:
      id: 101
      area: 0.0.0.0
    network_point_to_point: false
  metadata:
    tenants:
    - Tenant_A
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 201
  name: default_201
  metadata:
    tenants:
    - Tenant_A
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: ipv6-router-ospf-default-vrf_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 201
        vni: 10201
      vrfs:
      - name: default
        vni: 2
