aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: logging-settings-local-interface
ip_routing: true
logging:
  vrfs:
  - name: MGMT
    local_interface: Management0
    hosts:
    - name: 30.30.30.7
      protocol: tcp
      ports:
      - 100
      - 200
  - name: default
    local_interface: Ethernet42
    hosts:
    - name: 192.168.0.42
      protocol: udp
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 1.2.3.2/32
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.66.23/24
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 1.2.3.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65000'
  router_id: 1.2.3.2
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
