aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: mgmt-interface-ipv6-address-auto-config
ip_igmp_snooping:
  globally_enabled: true
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ipv6_enable: true
  ipv6_address_auto_config: true
  ipv6_nd:
    ra:
      rx_accept:
        default_route: true
        route_preference: true
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
  ipv6_routing: false
