aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet51
  description: L2_mlag-shared-node-groups-implicit-2_Ethernet52
  shutdown: false
  metadata:
    peer: mlag-shared-node-groups-implicit-2
    peer_interface: Ethernet52
    peer_type: l2leaf
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
- name: Ethernet52
  description: L2_mlag-shared-node-groups-implicit-4_Ethernet51
  shutdown: false
  metadata:
    peer: mlag-shared-node-groups-implicit-4
    peer_interface: Ethernet51
    peer_type: l2leaf
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: none
hostname: mlag-shared-node-groups-implicit-3
ip_igmp_snooping:
  globally_enabled: true
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.202.223/24
  type: oob
metadata:
  is_deployed: true
  platform: vEOS-LAB
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 8192
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
