aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: network-services-ip-helpers-leaf2
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.0.255.2/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.255.2.2/32
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 10.1.1.2/24
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.0.255.0/24 eq 32
  - sequence: 20
    action: permit 10.255.2.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65001'
  router_id: 192.0.255.2
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 10
    metadata:
      tenants:
      - TEST1
    rd: 192.0.255.2:1010
    route_targets:
      both:
      - 1010:1010
    redistribute_routes:
    - learned
  vrfs:
  - name: IP_HELPERS1
    rd: 192.0.255.2:100
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 100:100
      export:
      - address_family: evpn
        route_targets:
        - 100:100
    router_id: 192.0.255.2
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: none
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan10
  description: SVI1
  shutdown: true
  vrf: IP_HELPERS1
  ip_helpers:
  - ip_helper: 1.1.1.1
    source_interface: Management1
    vrf: MGMT
  - ip_helper: 1.1.1.2
    source_interface: Management1
    vrf: MGMT
  - ip_helper: 1.1.1.3
    source_interface: Management1
    vrf: MGMT
  metadata:
    tenants:
    - TEST1
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 10
  name: SVI1
  metadata:
    tenants:
    - TEST1
vrfs:
- name: MGMT
  ip_routing: false
- name: IP_HELPERS1
  ip_routing: true
  metadata:
    tenants:
    - TEST1
vxlan_interface:
  vxlan1:
    description: network-services-ip-helpers-leaf2_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 10
        vni: 1010
      vrfs:
      - name: IP_HELPERS1
        vni: 100
