aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet10
  description: ipv6-only-default-vrf
  shutdown: false
  ipv6_addresses:
  - 2001:db8:10::1/64
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet11
  description: dual-stack-default-vrf
  shutdown: false
  ip_address: 10.0.11.1/31
  ipv6_addresses:
  - 2001:db8:11::1/64
  ipv6_access_group_in: TEST-IPV6-ACL-STATIC-IN
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet12
  description: ipv6-only-non-default-vrf
  shutdown: false
  vrf: L3INTF_TEST
  ipv6_addresses:
  - 2001:db8:12::1/64
  ipv6_access_group_out: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet12
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet13
  description: peer-ipv6-acl-test
  shutdown: false
  vrf: L3INTF_TEST
  ipv6_addresses:
  - 2001:db8:13::1/64
  ipv6_access_group_in: TEST-IPV6-ACL-WITH-PEER-IPV6-IN_Ethernet13
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
- name: Ethernet14
  description: ipv6-acl-on-ipv4-only-interface
  shutdown: false
  vrf: L3INTF_TEST
  ip_address: 10.0.14.1/31
  ipv6_access_group_in: TEST-IPV6-ACL-STATIC-IN
  metadata:
    peer_type: l3_interface
  switchport:
    enabled: false
hostname: network-services-l3-interfaces
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0b
ipv6_access_lists:
- name: TEST-IPV6-ACL-STATIC-IN
  entries:
  - protocol: ipv6
    source: any
    destination: any
    sequence: 10
    action: deny
- name: TEST-IPV6-ACL-WITH-IP-FIELDS-OUT_Ethernet12
  entries:
  - protocol: ipv6
    source: 2001:db8:12::1
    destination: any
    sequence: 10
    action: permit
- name: TEST-IPV6-ACL-WITH-PEER-IPV6-IN_Ethernet13
  entries:
  - protocol: ipv6
    source: 2001:db8:13::2
    destination: any
    sequence: 10
    action: permit
ipv6_unicast_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.200.1/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.201.1/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.200.0/24 eq 32
  - sequence: 20
    action: permit 192.168.201.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '200'
  router_id: 192.168.200.1
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vrfs:
  - name: L3INTF_TEST
    rd: 192.168.200.1:2
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '2:2'
      export:
      - address_family: evpn
        route_targets:
        - '2:2'
    router_id: 192.168.200.1
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: L3INTF_TEST
  ip_routing: true
  ipv6_routing: true
  metadata:
    tenants:
    - L3INTF
vxlan_interface:
  vxlan1:
    description: network-services-l3-interfaces_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vrfs:
      - name: default
        vni: 1
      - name: L3INTF_TEST
        vni: 2
