aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: SNMP_AUTOGEN_ENGINEID_LEGACY_HOSTNAME_AND_IP_OOB
ip_igmp_snooping:
  globally_enabled: true
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: d50deab4a211a6276f4a4fcb6f97da85e31d1ca9
  contact: example@example.com
  location: EOS_DESIGNS_UNIT_TESTS SNMP_AUTOGEN_ENGINEID_LEGACY_HOSTNAME_AND_IP_OOB
  users:
  - name: usertest-auth-priv
    group: usergroup
    version: v3
    localized: d50deab4a211a6276f4a4fcb6f97da85e31d1ca9
    auth: sha
    auth_passphrase: bd297e25a81643f97f4d0ecac159642ad5cebaa1
    priv: aes192
    priv_passphrase: 82434fd769bc0debbdc216a325f851de3a7f6c305659c660
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 1.1.1.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
