aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: SNMP_AUTOGEN_ENGINEID_RFC3411_HOSTNAME_DEFAULT_MGMT
ip_igmp_snooping:
  globally_enabled: true
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: 8000757104a78fd1153a14f76bee5d7468f95309ed38866a10
  contact: example@example.com
  location: EOS_DESIGNS_UNIT_TESTS SNMP_AUTOGEN_ENGINEID_RFC3411_HOSTNAME_DEFAULT_MGMT
  users:
  - name: usertest-auth-priv
    group: usergroup
    version: v3
    localized: 8000757104a78fd1153a14f76bee5d7468f95309ed38866a10
    auth: sha
    auth_passphrase: 5fbdabf97d46e5c6ad032f5006217a2857ff9baa
    priv: aes192
    priv_passphrase: b54d01f2bcf6cf9ed10040321a4bc81cfd7decd66475b592
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 192.168.0.10/24
  mtu: 1500
  metadata:
    type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4092
  name: INBAND_MGMT
  metadata:
    tenant: system
vrfs:
- name: MGMT
  ip_routing: false
