aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: snmp-autogen-engineid-rfc3411-hostname-specific-ip
ip_igmp_snooping:
  globally_enabled: true
ip_routing: false
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: 8000757105031afc850e1e7d5bfbdeacc98b866404a0526c03
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
