aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: snmp-autogen-engineid-hostname-and-ip-inband
ip_igmp_snooping:
  globally_enabled: true
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: 07459749db8910d2ea1447c20595b70729534f97
  contact: example@example.com
  location: EOS_DESIGNS_UNIT_TESTS snmp-autogen-engineid-hostname-and-ip-inband
  local_users:
  - name: usertest-auth-priv
    group: usergroup
    version: v3
    localized: 07459749db8910d2ea1447c20595b70729534f97
    auth: sha
    auth_passphrase: d035999725c2ae5776a5c5b685853ecc6503739d
    priv: aes192
    priv_passphrase: 7a3e71ab96695ec38d1f1019163797d44bd8f80aa53be88a
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
