aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: snmp-autogen-engineid-rfc3411-type3-custom-system-mac
ip_igmp_snooping:
  globally_enabled: true
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.44/24
  type: oob
metadata:
  is_deployed: true
  system_mac_address: 02:1c:73:00:00:2c
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: 8000757103021c7300002c
system:
  mac_address: 02:1c:73:00:00:2c
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
