aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: snmp-autogen-engineid-rfc3411-hostname-inband-ip
ip_igmp_snooping:
  globally_enabled: true
ip_routing: false
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
service_routing_protocols_model: multi-agent
snmp_server:
  engine_ids:
    local: 8000757105bf484a8e614d2fb8a4e95d01d7b08dbf14ea7b11
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  ip_address: 192.168.0.10/24
  mtu: 1500
  metadata:
    type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4092
  name: INBAND_MGMT
  metadata:
    tenants:
    - system
vrfs:
- name: MGMT
  ip_routing: false
