aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: underlay-filter-redistribute-connected-to-bgp-without-route-map-preserve-order
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.10.0.4/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.11.0.4/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-SVI-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    action: permit 10.10.10.0/24
  - sequence: 20
    action: permit 10.10.30.0/24
  - sequence: 30
    action: permit 10.10.20.0/24
route_maps:
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 10.10.0.4
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
  vlans:
  - id: 111
    metadata:
      tenants:
      - TEST
    rd: 10.10.0.4:10111
    route_targets:
      both:
      - 10111:10111
    redistribute_routes:
    - learned
  - id: 112
    metadata:
      tenants:
      - TEST
    rd: 10.10.0.4:10112
    route_targets:
      both:
      - 10112:10112
    redistribute_routes:
    - learned
  - id: 113
    metadata:
      tenants:
      - TEST
    rd: 10.10.0.4:10113
    route_targets:
      both:
      - 10113:10113
    redistribute_routes:
    - learned
  vrfs:
  - name: default
    rd: 10.10.0.4:111
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 111:111
      export:
      - address_family: evpn
        route_targets:
        - 111:111
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan111
  description: svi_with_default_vrf
  shutdown: true
  ip_address: 10.10.10.111/24
  metadata:
    tenants:
    - TEST
    tags:
    - fabric
- name: Vlan112
  description: svi_with_default_vrf_2
  shutdown: true
  ip_address: 10.10.30.111/24
  metadata:
    tenants:
    - TEST
    tags:
    - fabric
- name: Vlan113
  description: svi_with_default_vrf_3
  shutdown: true
  ip_address: 10.10.20.111/24
  metadata:
    tenants:
    - TEST
    tags:
    - fabric
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 111
  name: svi_with_default_vrf
  metadata:
    tenants:
    - TEST
- id: 112
  name: svi_with_default_vrf_2
  metadata:
    tenants:
    - TEST
- id: 113
  name: svi_with_default_vrf_3
  metadata:
    tenants:
    - TEST
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: underlay-filter-redistribute-connected-to-bgp-without-route-map-preserve-order_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 111
        vni: 10111
      - id: 112
        vni: 10112
      - id: 113
        vni: 10113
      vrfs:
      - name: default
        vni: 111
