aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: vrfs-rt-import-and-export
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:dc:00:00:00:0a
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.10.0.20/32
- name: Loopback1
  description: MY_VTEP_LOOPBACK
  shutdown: false
  ip_address: 10.11.0.20/32
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_UNIT_TESTS
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.10.0.0/24 eq 32
  - sequence: 20
    action: permit 10.11.0.0/24 eq 32
- name: PL-SVI-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    action: permit 10.0.201.0/24
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-SVI-VRF-DEFAULT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 10.10.0.20
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 201
    metadata:
      tenants:
      - TENANT1
    rd: 10.10.0.20:10201
    route_targets:
      both:
      - 10201:10201
    redistribute_routes:
    - learned
  - id: 100
    metadata:
      tenants:
      - TENANT1
    rd: 10.10.0.20:10100
    route_targets:
      both:
      - 10100:10100
    redistribute_routes:
    - learned
  - id: 200
    metadata:
      tenants:
      - TENANT1
    rd: 10.10.0.20:10200
    route_targets:
      both:
      - 10200:10200
    redistribute_routes:
    - learned
  vrfs:
  - name: default
    rd: 10.10.0.20:3
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '3:3'
      export:
      - address_family: evpn
        route_targets:
        - '3:3'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
  - name: VRF1
    rd: 111:222
    route_targets:
      export:
      - address_family: evpn
        route_targets:
        - 333:444
    router_id: 10.10.0.20
    redistribute:
      connected:
        enabled: true
  - name: VRF2
    rd: 10.10.0.20:999
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 2:999
    router_id: 10.10.0.20
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan201
  description: VLAN201
  shutdown: false
  ip_address_virtual: 10.0.201.1/24
  metadata:
    tenants:
    - TENANT1
- name: Vlan100
  description: VLAN100
  shutdown: false
  vrf: VRF1
  ip_address_virtual: 10.0.100.1/24
  metadata:
    tenants:
    - TENANT1
- name: Vlan200
  description: VLAN200
  shutdown: false
  vrf: VRF2
  ip_address_virtual: 10.0.200.1/24
  metadata:
    tenants:
    - TENANT1
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 201
  name: VLAN201
  metadata:
    tenants:
    - TENANT1
- id: 100
  name: VLAN100
  metadata:
    tenants:
    - TENANT1
- id: 200
  name: VLAN200
  metadata:
    tenants:
    - TENANT1
vrfs:
- name: MGMT
  ip_routing: false
- name: VRF1
  ip_routing: true
  metadata:
    tenants:
    - TENANT1
- name: VRF2
  ip_routing: true
  metadata:
    tenants:
    - TENANT1
vxlan_interface:
  vxlan1:
    description: vrfs-rt-import-and-export_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 201
        vni: 10201
      - id: 100
        vni: 10100
      - id: 200
        vni: 10200
      vrfs:
      - name: default
        vni: 3
      - name: VRF1
        vni: 1
      - name: VRF2
        vni: 2
