aaa_root:
  disabled: true
aaa_server_groups:
- name: RADIUS1
  type: radius
  servers:
  - server: 11.10.10.11
    vrf: default
  - server: 11.10.10.5
    vrf: MGMT1
  - server: 11.10.10.3
    vrf: MGMT
- name: TACACS1
  type: tacacs+
  servers:
  - server: 10.10.10.11
    vrf: default
  - server: 10.10.10.1
    vrf: default
  - server: 10.10.10.2
    vrf: MGMT
  - server: 10.10.10.3
    vrf: default
  - server: 10.10.10.2
    vrf: MGMT1
  - server: nodomain.co
    vrf: default
  - server: '1:1:1:1:1:1:1:1'
    vrf: MGMT
- name: TACACS2
  type: tacacs+
  servers:
  - server: 10.10.10.1
    vrf: default
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet41
  description: P2P_host1_Ethernet42
  shutdown: false
  mtu: 9214
  ip_address: 192.168.42.200/31
  pim:
    ipv4:
      sparse_mode: true
  metadata:
    peer: host1
    peer_interface: Ethernet42
    peer_type: l3leaf
  switchport:
    enabled: false
- name: Ethernet42
  description: P2P_host1_Ethernet41
  shutdown: false
  mtu: 9214
  ip_address: 192.168.42.201/31
  pim:
    ipv4:
      sparse_mode: true
  metadata:
    peer: host1
    peer_interface: Ethernet41
    peer_type: l3leaf
  switchport:
    enabled: false
hostname: host1
ip_igmp_snooping:
  globally_enabled: true
  vlans:
  - id: 252
    querier:
      enabled: true
      address: 192.168.255.101
    fast_leave: true
ip_radius:
  source_interface: Vlan123
  vrfs:
  - name: MGMT1
    source_interface: Vlan125
  - name: MGMT
    source_interface: Vlan125
ip_routing: true
ip_tacacs:
  source_interface: Vlan123
  vrfs:
  - name: MGMT
    source_interface: Vlan125
  - name: MGMT1
    source_interface: Vlan125
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.255.101/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.254.101/32
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: default
  ip_address: 192.168.0.103/24
  type: oob
  gateway: 192.168.200.1
metadata:
  is_deployed: true
  platform: vEOS
  fabric_name: EOS_DESIGNS_DEPRECATED_VARS
  validate_hardware:
    enabled: false
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.255.0/24 eq 32
  - sequence: 20
    action: permit 192.168.254.0/24 eq 32
radius_server:
  servers:
  - host: 11.10.10.11
    key: 071B245F5A
  vrfs:
  - name: MGMT1
    servers:
    - host: 11.10.10.5
      tls:
        enabled: true
        ssl_profile: HOST_SSL_PROFILE
        port: 2080
  - name: MGMT
    servers:
    - host: 11.10.10.3
      key: 0112140D481F07
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '101'
  router_id: 192.168.255.101
  maximum_paths:
    paths: 4
  bgp:
    default:
      ipv4_unicast: false
    bestpath:
      d_path: true
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    metadata:
      type: ipv4
    send_community: all
    maximum_routes: 256000
  neighbors:
  - ip_address: 192.168.42.201
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '101'
    metadata:
      peer: host1
    description: host1_Ethernet42
  - ip_address: 192.168.42.200
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '101'
    metadata:
      peer: host1
    description: host1_Ethernet41
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  vlans:
  - id: 251
    metadata:
      tenants:
      - Tenant_F
    rd: 192.168.255.101:10251
    route_targets:
      both:
      - 10251:10251
    redistribute_routes:
    - learned
  - id: 252
    metadata:
      tenants:
      - Tenant_F
    rd: 192.168.255.101:10252
    route_targets:
      both:
      - 10252:10252
    redistribute_routes:
    - learned
    - igmp
  address_family_evpn:
    domain_identifier: '65200:2'
    domain_identifier_remote: '65100:1'
    neighbor_default:
      next_hop_self_received_evpn_routes:
        enable: true
        inter_domain: true
    evpn_ethernet_segment:
    - domain: all
      identifier: 0000:0001:0001:0000:0509
      route_target_import: 00:00:00:00:07:09
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
router_multicast:
  ipv4:
    routing: true
    software_forwarding: sfe
service_routing_protocols_model: multi-agent
static_routes:
- vrf: default
  prefix: 0.0.0.0/0
  next_hop: 192.168.200.1
tacacs_servers:
  hosts:
  - host: 10.10.10.11
    vrf: default
    key: 071B245F5A
  - host: 10.10.10.1
    vrf: default
    key: 071B245F5A
  - host: 10.10.10.2
    vrf: MGMT
    key: 071B245F5A
  - host: 10.10.10.3
    vrf: default
    key: 071B245F5A
  - host: 10.10.10.2
    vrf: MGMT1
    key: 15131905173E2A
  - host: nodomain.co
    vrf: default
    key: 071B245F5A
  - host: '1:1:1:1:1:1:1:1'
    vrf: MGMT
    key: 071B245F5A
  - host: 10.10.10.42
    vrf: default
    key: 071B245F5A
  policy_unknown_mandatory_attribute_ignore: false
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 251
  name: MULTICAST_DISABLED_251
  metadata:
    tenants:
    - Tenant_F
- id: 252
  name: MULTICAST_ENABLED_252
  metadata:
    tenants:
    - Tenant_F
vrfs:
- name: default
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: host1_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vlans:
      - id: 251
        vni: 10251
      - id: 252
        vni: 10252
        multicast_group: 232.0.0.251
