---
- file: inventory/intended/configs/dc1-leaf1a.cfg
  sections:
    - header: "interface Ethernet1"
  artifact: "WEB-SERVER-01.cfg"

- file: inventory/intended/configs/dc1-leaf1a.cfg
  sections:
    - header: "interface Port-Channel11"
    - header: "interface Ethernet11"
  artifact: "ESXI-HOST-03.cfg"
