---
type: l2leaf

l2leaf:
  nodes:
    - name: digital-twin-hardware-identity-tests-veos
      id: 1
      mgmt_ip: 192.168.10.11/32
      serial_number: PROD-VEOS-SERIAL
      system_mac_address: 02:1c:73:00:00:11

digital_twin:
  fabric:
    hardware_identity:
      serial_number: true
      system_mac_address: true
    ztp: true
