[package]
name = "validation"
version.workspace = true
edition = "2024"
license.workspace = true

[build-dependencies]
pyo3-build-config = { workspace = true }

[dependencies]
avdschema = { path = "../avdschema" }
derive_more = { workspace = true, features = ["display", "from"] }
ordermap = { workspace = true, features = ["serde"] }
pyo3 = { workspace = true, features = ["abi3-py310"], optional = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision", # To support very big numbers
    "preserve_order",
] }
serde_yaml = { workspace = true }

[features]
python_bindings = ["dep:pyo3"]

[lib]
crate-type = ["cdylib", "lib"]
