# Roles Defaults - directories

# Output directory for temporary files.
# Contains templated and validated inputs used by the 'cv_deploy' role.
cv_deploy_tmp_dir: '{{ cv_deploy_internal_output_dir }}/tmp_cv_deploy'
