---
type: l2leaf

l2leaf:
  nodes:
    - name: digital-twin-adjust-oob-mgmt-3
      id: 3
      digital_twin:
        mgmt_ip: 192.168.1.3/32
      inband_mgmt_ip: 192.168.1.3/32
      inband_mgmt_vrf: INBAND_MGMT
