---
# CloudVision Deployment How-To Guide
# Fabric-wide settings

fabric_name: FABRIC

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# --8<-- [start:cv_settings]
cv_settings: # (1)!
  cvaas:
    enabled: true # (2)!
    clusters:
      - name: cvaas
        region: us-central1-a # (3)!
  terminattr:
    smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata" # (4)!
    disable_aaa: false # (5)!
# --8<-- [end:cv_settings]
