---
# CloudVision Deployment How-To Guide
# Fabric-wide settings

fabric_name: FABRIC

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# CloudVision settings - configures TerminAttr on all devices
cv_settings: # (1)!
  cvaas:
    enabled: true # (2)!
    clusters:
      - name: cvaas # (3)!
        region: us-central1-a # (4)!
  terminattr:
    smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata" # (5)!
    disable_aaa: false # (6)!
