# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: arista/imagestatus.v1/imagestatus.proto, arista/imagestatus.v1/services.gen.proto
# plugin: python-aristaproto
# This file has been @generated

__all__ = (
    "ComplianceStatus",
    "ComplianceStatusBySup",
    "DiffOp",
    "ErrorCode",
    "Extension",
    "ExtensionDiff",
    "ExtensionDiffs",
    "ExtensionDiffsBySup",
    "ExtensionInstallStatus",
    "Extensions",
    "ImageError",
    "ImageErrors",
    "ImageInfo",
    "ImageInfos",
    "ImageMetadata",
    "ImageSource",
    "ImageSummary",
    "ImageWarning",
    "ImageWarnings",
    "InfoCode",
    "MetaResponse",
    "RebootRequired",
    "SoftwareComplianceCode",
    "SoftwareImage",
    "SoftwareImageDiff",
    "SoftwareImageDiffsBySup",
    "Summary",
    "SummaryBatchedStreamRequest",
    "SummaryBatchedStreamResponse",
    "SummaryKey",
    "SummaryRequest",
    "SummaryResponse",
    "SummaryServiceStub",
    "SummarySomeRequest",
    "SummarySomeResponse",
    "SummaryStreamRequest",
    "SummaryStreamResponse",
    "TerminAttrDiffsBySup",
    "WarningCode",
)

import datetime
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import TYPE_CHECKING

import aristaproto
import grpc
from aristaproto import grpcio as aristaproto_grpcio

from ....message_pool import default_message_pool

if TYPE_CHECKING:
    from aristaproto.grpcio.grpcio_async_client import MetadataLike

_COMPILER_VERSION = "2.0.0.dev1"
aristaproto.check_compiler_version(_COMPILER_VERSION)


class DiffOp(aristaproto.Enum):
    """
    DiffOp represents the operation performed to get from one side of the diff
    to the other.
    """

    UNSPECIFIED = 0
    """
    DIFF_OP_UNSPECIFIED indicates op code is unspecified.
    """

    NOP = 1
    """
    DIFF_OP_NOP indicates no change.
    """

    ADD = 2
    """
    DIFF_OP_ADD is an addition of a software.
    """

    DELETE = 3
    """
    DIFF_OP_DELETE is deletion of a software.
    """

    CHANGE = 4
    """
    DIFF_OP_CHANGE is an update to the software.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "DIFF_OP_UNSPECIFIED",
            1: "DIFF_OP_NOP",
            2: "DIFF_OP_ADD",
            3: "DIFF_OP_DELETE",
            4: "DIFF_OP_CHANGE",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "DIFF_OP_UNSPECIFIED": 0,
            "DIFF_OP_NOP": 1,
            "DIFF_OP_ADD": 2,
            "DIFF_OP_DELETE": 3,
            "DIFF_OP_CHANGE": 4,
        }


class ErrorCode(aristaproto.Enum):
    """
    ErrorCode indicates errors produced during image validations.
    """

    UNSPECIFIED = 0
    """
    ERROR_CODE_UNSPECIFIED indicates error code is unspecified.
    """

    SUPPORT_NOT_INTRODUCED = 1
    """
    ERROR_CODE_SUPPORT_NOT_INTRODUCED represents case where the given EOS version does
    not support the SKU.
    Deprecated - use ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED
    """

    SUPPORT_REMOVED = 2
    """
    ERROR_CODE_SUPPORT_REMOVED represents case where the given EOS version no longer
    supports the SKU.
    Deprecated - use ERROR_CODE_EOS_SUPPORT_REMOVED
    """

    DEVICE_UNREACHABLE = 3
    """
    ERROR_CODE_DEVICE_UNREACHABLE represents the case where the device
    is unreachable during a compliance computation.
    """

    VALIDATION_FAILED = 4
    """
    ERROR_CODE_VALIDATION_FAILED represents case where the validations checks
    failed.
    """

    GET_PROPOSED_IMAGE_INFO_FAILED = 5
    """
    ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED represents case where we are
    unable to get proposed image information for a device.
    """

    GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED = 6
    """
    ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED represents case where we
    fail to get running image information from an active supervisor.
    """

    GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED = 7
    """
    ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED represents case when we
    fail to get information from peer supervisor.
    """

    EOS_TA_ARCHITECTURE_INCOMPATIBLE = 8
    """
    ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE represents the case where EOS architecture and
    TerminAttr architecture are incompatible.
    """

    TA_CV_INCOMPATIBLE = 9
    """
    ERROR_CODE_TA_CV_INCOMPATIBLE represents the case where TerminAttr is too low for CV to
    support or manage the device.
    """

    EOS_CV_INCOMPATIBLE = 10
    """
    ERROR_CODE_EOS_CV_INCOMPATIBLE represents the case where EOS is too low for CV to support
    or manage the device.
    """

    EOS_SUPPORT_NOT_INTRODUCED = 11
    """
    ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED represents the case where the given EOS version does
    not support the SKU.
    """

    EOS_SUPPORT_REMOVED = 12
    """
    ERROR_CODE_EOS_SUPPORT_REMOVED represents the case where the given EOS version no longer
    supports the SKU.
    """

    PHYSICAL_DEVICE_EOS_INCOMPATIBLE = 13
    """
    ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE represents the case where the physical device
    does not support the given EOS type.
    """

    TA_EMBEDDEDEXT_INCOMPATIBLE = 14
    """
    ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE represents the case where the extension TerminAttr
    version is lower than the embedded TerminAttr version in SWI.
    """

    DEVICE_EOS_2GB_INCOMPATIBLE = 15
    """
    ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE represents the case where a 2GB-device is incompatible
    with a non-2GB EOS or a non-2GB device is incompatible with a 2GB-EOS.
    """

    EOS_EXTENSION_VERSION_INCOMPATIBLE = 16
    """
    ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE represents the case where the given extension
    version doesn't support the given EOS version.
    """

    ARCH_UNSUPPORTED = 17
    """
    ERROR_CODE_ARCH_UNSUPPORTED represents the case where the given image architecture is not
    supported by CloudVision.
    """

    EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE = 18
    """
    ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE represents the case where EOS architecture
    and Extension architecture are incompatible.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "ERROR_CODE_UNSPECIFIED",
            1: "ERROR_CODE_SUPPORT_NOT_INTRODUCED",
            2: "ERROR_CODE_SUPPORT_REMOVED",
            3: "ERROR_CODE_DEVICE_UNREACHABLE",
            4: "ERROR_CODE_VALIDATION_FAILED",
            5: "ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED",
            6: "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED",
            7: "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED",
            8: "ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE",
            9: "ERROR_CODE_TA_CV_INCOMPATIBLE",
            10: "ERROR_CODE_EOS_CV_INCOMPATIBLE",
            11: "ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED",
            12: "ERROR_CODE_EOS_SUPPORT_REMOVED",
            13: "ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE",
            14: "ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE",
            15: "ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE",
            16: "ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE",
            17: "ERROR_CODE_ARCH_UNSUPPORTED",
            18: "ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "ERROR_CODE_UNSPECIFIED": 0,
            "ERROR_CODE_SUPPORT_NOT_INTRODUCED": 1,
            "ERROR_CODE_SUPPORT_REMOVED": 2,
            "ERROR_CODE_DEVICE_UNREACHABLE": 3,
            "ERROR_CODE_VALIDATION_FAILED": 4,
            "ERROR_CODE_GET_PROPOSED_IMAGE_INFO_FAILED": 5,
            "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_ACTIVE_SUPERVISOR_FAILED": 6,
            "ERROR_CODE_GET_RUNNING_IMAGE_INFO_FROM_PEER_SUPERVISOR_FAILED": 7,
            "ERROR_CODE_EOS_TA_ARCHITECTURE_INCOMPATIBLE": 8,
            "ERROR_CODE_TA_CV_INCOMPATIBLE": 9,
            "ERROR_CODE_EOS_CV_INCOMPATIBLE": 10,
            "ERROR_CODE_EOS_SUPPORT_NOT_INTRODUCED": 11,
            "ERROR_CODE_EOS_SUPPORT_REMOVED": 12,
            "ERROR_CODE_PHYSICAL_DEVICE_EOS_INCOMPATIBLE": 13,
            "ERROR_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE": 14,
            "ERROR_CODE_DEVICE_EOS_2GB_INCOMPATIBLE": 15,
            "ERROR_CODE_EOS_EXTENSION_VERSION_INCOMPATIBLE": 16,
            "ERROR_CODE_ARCH_UNSUPPORTED": 17,
            "ERROR_CODE_EOS_EXTENSION_ARCHITECTURE_INCOMPATIBLE": 18,
        }


class ExtensionInstallStatus(aristaproto.Enum):
    """
    ExtensionInstallStatus indicates whether an extension is installed, not installed
    or force installed.
    """

    UNSPECIFIED = 0
    """
    EXTENSION_INSTALL_STATUS_UNSPECIFIED indicates extensions install status is unspecified.
    """

    NOT_INSTALLED = 1
    """
    EXTENSION_INSTALL_STATUS_NOT_INSTALLED indicates extension is not installed on the device.
    """

    INSTALLED = 2
    """
    EXTENSION_INSTALL_STATUS_INSTALLED indicates extension is installed on the device.
    """

    FORCE_INSTALLED = 3
    """
    EXTENSION_INSTALL_STATUS_FORCE_INSTALLED indicates extension is force installed on
    device.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "EXTENSION_INSTALL_STATUS_UNSPECIFIED",
            1: "EXTENSION_INSTALL_STATUS_NOT_INSTALLED",
            2: "EXTENSION_INSTALL_STATUS_INSTALLED",
            3: "EXTENSION_INSTALL_STATUS_FORCE_INSTALLED",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "EXTENSION_INSTALL_STATUS_UNSPECIFIED": 0,
            "EXTENSION_INSTALL_STATUS_NOT_INSTALLED": 1,
            "EXTENSION_INSTALL_STATUS_INSTALLED": 2,
            "EXTENSION_INSTALL_STATUS_FORCE_INSTALLED": 3,
        }


class ImageSource(aristaproto.Enum):
    """
    ImageSource indicates the source type for the image configuration.
    """

    UNSPECIFIED = 0
    """
    IMAGE_SOURCE_UNSPECIFIED uninitialized value
    """

    STUDIO = 1
    """
    IMAGE_SOURCE_STUDIO - image configured from studio
    """

    NETWORK_PROVISIONING = 2
    """
    IMAGE_SOURCE_NETWORK_PROVISIONING - image configured from
    network provisioning workflow
    """

    HIERARCHY = 3
    """
    IMAGE_SOURCE_HIERARCHY - image configured from hierarchy workflow
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "IMAGE_SOURCE_UNSPECIFIED",
            1: "IMAGE_SOURCE_STUDIO",
            2: "IMAGE_SOURCE_NETWORK_PROVISIONING",
            3: "IMAGE_SOURCE_HIERARCHY",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "IMAGE_SOURCE_UNSPECIFIED": 0,
            "IMAGE_SOURCE_STUDIO": 1,
            "IMAGE_SOURCE_NETWORK_PROVISIONING": 2,
            "IMAGE_SOURCE_HIERARCHY": 3,
        }


class InfoCode(aristaproto.Enum):
    """
    InfoCode indicates info messages produced during image validations.
    """

    UNSPECIFIED = 0
    """
    INFO_CODE_UNSPECIFIED indicates info code is unspecified.
    """

    NEWER_VERSION_AVAILABLE = 1
    """
    INFO_CODE_NEWER_VERSION_AVAILABLE represents cases where a newer EOS maintainance
    release is available for download.
    """

    UNIVERSAL_IMAGE_ARCH_APPLIED = 2
    """
    INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED represents cases where a specific architecture is
    picked for a Universal (multiarch) EOS image.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "INFO_CODE_UNSPECIFIED",
            1: "INFO_CODE_NEWER_VERSION_AVAILABLE",
            2: "INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "INFO_CODE_UNSPECIFIED": 0,
            "INFO_CODE_NEWER_VERSION_AVAILABLE": 1,
            "INFO_CODE_UNIVERSAL_IMAGE_ARCH_APPLIED": 2,
        }


class SoftwareComplianceCode(aristaproto.Enum):
    """
    SoftwareComplianceCode indicates possible compliance status.
    """

    UNSPECIFIED = 0
    """
    SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED indicates compliance code is unspecified.
    """

    IN_SYNC = 1
    """
    SOFTWARE_COMPLIANCE_CODE_IN_SYNC indicates designed and running images/extensions
    are identical.
    """

    OUT_OF_SYNC = 2
    """
    SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC indicates designed and running images/extensions
    are not identical.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED",
            1: "SOFTWARE_COMPLIANCE_CODE_IN_SYNC",
            2: "SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "SOFTWARE_COMPLIANCE_CODE_UNSPECIFIED": 0,
            "SOFTWARE_COMPLIANCE_CODE_IN_SYNC": 1,
            "SOFTWARE_COMPLIANCE_CODE_OUT_OF_SYNC": 2,
        }


class WarningCode(aristaproto.Enum):
    """
    WarningCode indicates warnings produced during image validations.
    """

    UNSPECIFIED = 0
    """
    WARNING_CODE_UNSPECIFIED indicates warning code is unspecified.
    """

    NOT_APPLICABLE = 1
    """
    WARNING_CODE_NOT_APPLICABLE represents cases where EOS < - > SKU/TA compatibility
    is not applicable for non physical switches like vEos.
    """

    SKUINFO_UNAVAILABLE = 2
    """
    WARNING_CODE_SKUINFO_UNAVAILABLE represents case where
    information about certain skus is missing.
    """

    DEVICE_SKU_UNAVAILABLE = 3
    """
    WARNING_CODE_DEVICE_SKU_UNAVAILABLE represents unavailability of skus for an EOS Device.
    """

    SWI_UNKNOWN = 4
    """
    WARNING_CODE_SWI_UNKNOWN represents cases where EOS version is not found in release database.
    """

    TA_EOS_INCOMPATIBLE = 5
    """
    WARNING_CODE_TA_EOS_INCOMPATIBLE represents cases where TA and EOS are not compatible.
    TA is lower than embedded TA in swi or given TA is unsupported by the EOS.
    """

    TA_CV_INCOMPATIBLE = 6
    """
    WARNING_CODE_TA_CV_INCOMPATIBLE represents cases where TA is lower than CV's minimum
    supported version for SMS assignments.
    """

    EOS_CV_INCOMPATIBLE = 7
    """
    WARNING_CODE_EOS_CV_INCOMPATIBLE represents the case where EOS is not supported by CV.
    The given EOS exceeds CV's maximum supported EOS version or for SMS assignments, the given
    EOS is below CV's minimum supported EOS version.
    """

    EOS_ARCH_UNKNOWN = 8
    """
    WARNING_CODE_EOS_ARCH_UNKNOWN represents cases where the specified architecture is
    not valid for EOS.
    """

    TA_EMBEDDEDEXT_INCOMPATIBLE = 9
    """
    WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE represents cases where TA extension is lower
    in version than embedded TA in SWI.
    """

    ARCH_INCOMPATIBLE = 10
    """
    WARNING_CODE_ARCH_INCOMPATIBLE represents cases where EOS arch and TA arch are
    different. Deprecated.
    """

    EOS_END_OF_LIFE_DATE_PASSED = 11
    """
    WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED represents cases where the given EOS has passed
    its end of life date.
    """

    SUPPORT_NOT_INTRODUCED = 12
    """
    WARNING_CODE_SUPPORT_NOT_INTRODUCED represents cases where the given EOS version does
    not support the SKUs.
    """

    SUPPORT_REMOVED = 13
    """
    WARNING_CODE_SUPPORT_REMOVED represents cases where the given EOS version no longer
    supports the SKUs.
    """

    RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION = 14
    """
    WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION represents cases where the running
    TerminAttr version is below CloudVision's minimum supported version.
    """

    TA_STUDIO_INCOMPATIBLE = 15
    """
    WARNING_CODE_TA_STUDIO_INCOMPATIBLE represents cases where the TerminAttr is incompatible
    with Software Management Studio.
    """

    BUGALERTS_DATA_MISSING = 16
    """
    WARNING_CODE_BUGALERTS_DATA_MISSING represents cases where some of the BugAlerts data
    under Aeris analytics dataset is missing.
    """

    @classmethod
    def aristaproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "WARNING_CODE_UNSPECIFIED",
            1: "WARNING_CODE_NOT_APPLICABLE",
            2: "WARNING_CODE_SKUINFO_UNAVAILABLE",
            3: "WARNING_CODE_DEVICE_SKU_UNAVAILABLE",
            4: "WARNING_CODE_SWI_UNKNOWN",
            5: "WARNING_CODE_TA_EOS_INCOMPATIBLE",
            6: "WARNING_CODE_TA_CV_INCOMPATIBLE",
            7: "WARNING_CODE_EOS_CV_INCOMPATIBLE",
            8: "WARNING_CODE_EOS_ARCH_UNKNOWN",
            9: "WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE",
            10: "WARNING_CODE_ARCH_INCOMPATIBLE",
            11: "WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED",
            12: "WARNING_CODE_SUPPORT_NOT_INTRODUCED",
            13: "WARNING_CODE_SUPPORT_REMOVED",
            14: "WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION",
            15: "WARNING_CODE_TA_STUDIO_INCOMPATIBLE",
            16: "WARNING_CODE_BUGALERTS_DATA_MISSING",
        }

    @classmethod
    def aristaproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "WARNING_CODE_UNSPECIFIED": 0,
            "WARNING_CODE_NOT_APPLICABLE": 1,
            "WARNING_CODE_SKUINFO_UNAVAILABLE": 2,
            "WARNING_CODE_DEVICE_SKU_UNAVAILABLE": 3,
            "WARNING_CODE_SWI_UNKNOWN": 4,
            "WARNING_CODE_TA_EOS_INCOMPATIBLE": 5,
            "WARNING_CODE_TA_CV_INCOMPATIBLE": 6,
            "WARNING_CODE_EOS_CV_INCOMPATIBLE": 7,
            "WARNING_CODE_EOS_ARCH_UNKNOWN": 8,
            "WARNING_CODE_TA_EMBEDDEDEXT_INCOMPATIBLE": 9,
            "WARNING_CODE_ARCH_INCOMPATIBLE": 10,
            "WARNING_CODE_EOS_END_OF_LIFE_DATE_PASSED": 11,
            "WARNING_CODE_SUPPORT_NOT_INTRODUCED": 12,
            "WARNING_CODE_SUPPORT_REMOVED": 13,
            "WARNING_CODE_RUNNING_TA_BELOW_MIN_SUPPORTED_VERSION": 14,
            "WARNING_CODE_TA_STUDIO_INCOMPATIBLE": 15,
            "WARNING_CODE_BUGALERTS_DATA_MISSING": 16,
        }


@dataclass(eq=False, repr=False)
class ComplianceStatus(aristaproto.Message):
    """
    ComplianceStatus indicates compliance status for software image, terminattr
    and extensions.
    """

    software_image_compliance_code: "SoftwareComplianceCode" = aristaproto.field(1, aristaproto.TYPE_ENUM, default_factory=lambda: SoftwareComplianceCode(0))
    """
    software_image_compliance_code is the compliance code for images.
    """

    terminattr_compliance_code: "SoftwareComplianceCode" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: SoftwareComplianceCode(0))
    """
    terminattr_compliance_code is the compliance code for TerminAttr.
    """

    extensions_compliance_code: "SoftwareComplianceCode" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: SoftwareComplianceCode(0))
    """
    extensions_compliance_code is the compliance code for extensions.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ComplianceStatus", ComplianceStatus)


@dataclass(eq=False, repr=False)
class ComplianceStatusBySup(aristaproto.Message):
    """
    ComplianceStatusBySup is a map that indicates the compliance code for each
    supervisor.
    """

    values: "dict[str, ComplianceStatus]" = aristaproto.field(
        1, aristaproto.TYPE_MAP, map_meta=aristaproto.map_meta(aristaproto.TYPE_STRING, aristaproto.TYPE_MESSAGE)
    )
    """
    values is the mapping of supervisor type to compliance code.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ComplianceStatusBySup", ComplianceStatusBySup)


@dataclass(eq=False, repr=False)
class Extension(aristaproto.Message):
    """
    Extension provides information of the running/designed extensions.
    """

    name: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    name is the name of the extension.
    """

    version: "str | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    version is the version of the extension.
    """

    reboot_required: "bool | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    reboot_required indicates whether applying/deleting this extension
    would result in a reboot.
    """

    present: "bool | None" = aristaproto.field(4, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    present indicates whether the extension is present in the device
    or not.
    """

    installed: "ExtensionInstallStatus" = aristaproto.field(5, aristaproto.TYPE_ENUM, default_factory=lambda: ExtensionInstallStatus(0))
    """
    installed indicates whether the extension is installed, not
    installed or force installed.
    """

    status_detail: "str | None" = aristaproto.field(6, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    status_detail gives the details behind installation of the extension.
    """

    is_embedded: "bool | None" = aristaproto.field(7, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    is_embedded indicates whether the extension is embedded in the EOS swi
    or not.
    """

    arch: "str | None" = aristaproto.field(8, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    arch is architecture type of the extension.
    """


default_message_pool.register_message("arista.imagestatus.v1", "Extension", Extension)


@dataclass(eq=False, repr=False)
class ExtensionDiff(aristaproto.Message):
    """
    ExtensionDiff is the diff for the running/designed extensions.
    """

    code: "DiffOp" = aristaproto.field(1, aristaproto.TYPE_ENUM, default_factory=lambda: DiffOp(0))
    """
    code indicates the operation performed to get from one side of the diff
    to the other.
    """

    a: "Extension | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, optional=True)
    """
    a is the extension on the a side (left hand side).
    """

    b: "Extension | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    b is the extension on the b side (right hand side).
    """

    text_code: "DiffOp" = aristaproto.field(4, aristaproto.TYPE_ENUM, default_factory=lambda: DiffOp(0))
    """
    text_code is the color in the diff view page.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ExtensionDiff", ExtensionDiff)


@dataclass(eq=False, repr=False)
class ExtensionDiffs(aristaproto.Message):
    """
    ExtensionDiffs is a list of extension diff information in the order they
    will be applied.
    """

    values: "list[ExtensionDiff]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    values is an ordered list of extension diffs applied to the device.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ExtensionDiffs", ExtensionDiffs)


@dataclass(eq=False, repr=False)
class ExtensionDiffsBySup(aristaproto.Message):
    """
    ExtensionDiffsBySup is the extension diff information for each supervisor.
    """

    values: "dict[str, ExtensionDiffs]" = aristaproto.field(
        1, aristaproto.TYPE_MAP, map_meta=aristaproto.map_meta(aristaproto.TYPE_STRING, aristaproto.TYPE_MESSAGE)
    )
    """
    values is the mapping of supervisor type to extension diff.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ExtensionDiffsBySup", ExtensionDiffsBySup)


@dataclass(eq=False, repr=False)
class Extensions(aristaproto.Message):
    """
    Extensions provides an ordered list of running/designed extensions.
    """

    values: "list[Extension]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    values represents extension information.
    """


default_message_pool.register_message("arista.imagestatus.v1", "Extensions", Extensions)


@dataclass(eq=False, repr=False)
class ImageError(aristaproto.Message):
    """
    ImageError wraps `ErrorCode` enum with a reason string.
    """

    sku: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    sku represents the name of the sku.
    """

    error_code: "ErrorCode" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: ErrorCode(0))
    """
    error_code is the error code.
    """

    error_msg: "str | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    error_msg provides a description of the error.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageError", ImageError)


@dataclass(eq=False, repr=False)
class ImageErrors(aristaproto.Message):
    """
    ImageErrors is the list of errors reported by CVP when handling image
    validations.
    """

    values: "list[ImageError]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    values is a list of image errors.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageErrors", ImageErrors)


@dataclass(eq=False, repr=False)
class ImageInfo(aristaproto.Message):
    """
    ImageInfo wraps `InfoCode` enum with a reason string.
    """

    sku: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    sku represents the name of the sku.
    """

    info_code: "InfoCode" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: InfoCode(0))
    """
    info_code is the info code.
    """

    info_msg: "str | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    info_msg provides a description of the info.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageInfo", ImageInfo)


@dataclass(eq=False, repr=False)
class ImageInfos(aristaproto.Message):
    """
    ImageInfos is the list of info messages reported by CVP when handling image validations.
    """

    values: "list[ImageInfo]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    values is a list of image infos.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageInfos", ImageInfos)


@dataclass(eq=False, repr=False)
class ImageMetadata(aristaproto.Message):
    """
    ImageMetadata provides information regarding the software image.
    """

    version: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    version is the version of the EOS image.
    """

    release: "str | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    release is the release name of the EOS image.
    """

    flavor: "str | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    flavor is the flavor information of the EOS image.
    default flavor is DEFAULT. Other flavors can be DPE, 2GB, etc.
    """

    variant: "str | None" = aristaproto.field(4, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    variant is the variant information of the EOS image.
    possible values: INT or US.
    """

    arch: "str | None" = aristaproto.field(5, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    arch is the architecture of the EOS image.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageMetadata", ImageMetadata)


@dataclass(eq=False, repr=False)
class ImageSummary(aristaproto.Message):
    """
    ImageSummary represents device image summary.
    """

    sku: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    sku indicates the top-level sku or model number.
    """

    running_image_update_time: "datetime.datetime | None" = aristaproto.field(
        2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True
    )
    """
    running_image_update_time is the most recent timestamp at which one of
    running image side properties is updated.
    """

    designed_image_update_time: "datetime.datetime | None" = aristaproto.field(
        3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True
    )
    """
    designed_image_update_time is the most recent timestamp at which one of
    designed image side properties is updated.
    """

    dual_sup: "bool | None" = aristaproto.field(4, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    dual_sup indicates if a device is a dual supervisor.
    """

    active_slot: "int | None" = aristaproto.field(5, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Int32Value, optional=True)
    """
    active_slot indicates the physical slot number for the the active
    supervisor.
    """

    standby_slot: "int | None" = aristaproto.field(6, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Int32Value, optional=True)
    """
    standby_slot indicates the physical slot number for the standby
    supervisor.
    """

    software_image_diff: "SoftwareImageDiffsBySup | None" = aristaproto.field(7, aristaproto.TYPE_MESSAGE, optional=True)
    """
    software_image_diff indicates the image diff for each supervisor.
    """

    terminattr_diff: "TerminAttrDiffsBySup | None" = aristaproto.field(8, aristaproto.TYPE_MESSAGE, optional=True)
    """
    terminattr_diff indicates the terminattr diff for each supervisor.
    """

    extensions_diff: "ExtensionDiffsBySup | None" = aristaproto.field(9, aristaproto.TYPE_MESSAGE, optional=True)
    """
    extensions_diff indicates the extension diff for each supervisor.
    """

    compliance_status: "SoftwareComplianceCode" = aristaproto.field(10, aristaproto.TYPE_ENUM, default_factory=lambda: SoftwareComplianceCode(0))
    """
    compliance_status is the aggregated compliance status (including both
    active/standby and image/TA/extension compliance).
    """

    compliance: "ComplianceStatusBySup | None" = aristaproto.field(11, aristaproto.TYPE_MESSAGE, optional=True)
    """
    compliance provides compliance information for each supervisor.
    """

    reboot_required: "RebootRequired | None" = aristaproto.field(12, aristaproto.TYPE_MESSAGE, optional=True)
    """
    reboot_required indicates whether a reboot is required if the designed
    image is pushed to the device.
    """

    digest: "str | None" = aristaproto.field(13, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    digest is the digest of the image summary. It can use SHA-256 hash
    algorithm for example. It is computed by stringifying the
    software_image_diff, terminattr_diff and extensions_diff and computing the
    hash.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageSummary", ImageSummary)


@dataclass(eq=False, repr=False)
class ImageWarning(aristaproto.Message):
    """
    ImageWarning wraps `WarningCode` enum with a reason string.
    """

    sku: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    sku represents the name of the sku.
    """

    warning_code: "WarningCode" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: WarningCode(0))
    """
    warning_code is the warning code.
    """

    warning_msg: "str | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    warning_msg provides a description of the warning.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageWarning", ImageWarning)


@dataclass(eq=False, repr=False)
class ImageWarnings(aristaproto.Message):
    """
    ImageWarnings is the list of warnings reported by CVP when handling image
    validations.
    """

    values: "list[ImageWarning]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    values is a list of image warnings.
    """


default_message_pool.register_message("arista.imagestatus.v1", "ImageWarnings", ImageWarnings)


@dataclass(eq=False, repr=False)
class MetaResponse(aristaproto.Message):
    time: "datetime.datetime | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of the last item included in the metadata calculation.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(2, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """

    count: "int | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.UInt32Value, optional=True)
    """
    Count is the number of items present under the conditions of the request.
    """


default_message_pool.register_message("arista.imagestatus.v1", "MetaResponse", MetaResponse)


@dataclass(eq=False, repr=False)
class RebootRequired(aristaproto.Message):
    """
    RebootRequired indicates the reboot information per software image,
    terminattr and extension for the switch as a whole.
    """

    software_image_reboot_required: "bool | None" = aristaproto.field(
        1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True
    )
    """
    software_image_reboot_required indicates whether reboot is required
    for the software image being applied.
    """

    terminattr_reboot_required: "bool | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    terminattr_reboot_required indicates whether reboot is required
    for the terminattr being applied/deleted.
    """

    extension_reboot_required: "bool | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.BoolValue, optional=True)
    """
    extension_reboot_required indicates whether reboot is required
    for the extensions being applied/deleted.
    """


default_message_pool.register_message("arista.imagestatus.v1", "RebootRequired", RebootRequired)


@dataclass(eq=False, repr=False)
class SoftwareImage(aristaproto.Message):
    """
    SoftwareImage provides information of the running/designed EOS image.
    """

    name: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    name is the name of the EOS image.
    """

    version: "str | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    version is the version of the EOS image.
    """

    metadata: "ImageMetadata | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    metadata  is the metadata of EOS image.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SoftwareImage", SoftwareImage)


@dataclass(eq=False, repr=False)
class SoftwareImageDiff(aristaproto.Message):
    """
    SoftwareImageDiff is the diff for the running/designed images.
    """

    code: "DiffOp" = aristaproto.field(1, aristaproto.TYPE_ENUM, default_factory=lambda: DiffOp(0))
    """
    code indicates the operation performed to get from one side of the diff
    to the other.
    """

    a: "SoftwareImage | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, optional=True)
    """
    a is the software image on the a side (left hand side).
    """

    b: "SoftwareImage | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    b is the software image on the b side (right hand side).
    """

    text_code: "DiffOp" = aristaproto.field(4, aristaproto.TYPE_ENUM, default_factory=lambda: DiffOp(0))
    """
    text_code is the color in the diff view page.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SoftwareImageDiff", SoftwareImageDiff)


@dataclass(eq=False, repr=False)
class SoftwareImageDiffsBySup(aristaproto.Message):
    """
    SoftwareImageDiffsBySup is software image diff information for each
    supervisor.
    """

    values: "dict[str, SoftwareImageDiff]" = aristaproto.field(
        1, aristaproto.TYPE_MAP, map_meta=aristaproto.map_meta(aristaproto.TYPE_STRING, aristaproto.TYPE_MESSAGE)
    )
    """
    values is the mapping of supervisor type to image diff.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SoftwareImageDiffsBySup", SoftwareImageDiffsBySup)


@dataclass(eq=False, repr=False)
class Summary(aristaproto.Message):
    """
    Summary represents the device image summary.
    """

    key: "SummaryKey | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    key represents the image summary key.
    """

    summary: "ImageSummary | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, optional=True)
    """
    summary is the image diff summary.
    """

    errors: "ImageErrors | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    errors are the image errors encountered while validating the image. These are
    displayed on the workspace build results page.
    """

    warnings: "ImageWarnings | None" = aristaproto.field(4, aristaproto.TYPE_MESSAGE, optional=True)
    """
    warnings are the image warnings encountered while validating the image. These are
    displayed on the workspace build results page.
    """

    infos: "ImageInfos | None" = aristaproto.field(5, aristaproto.TYPE_MESSAGE, optional=True)
    """
    infos are the image infos encountered while validating the image. These are
    displayed on the workspace build results page.
    """


default_message_pool.register_message("arista.imagestatus.v1", "Summary", Summary)


@dataclass(eq=False, repr=False)
class SummaryBatchedStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[Summary]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each Summary at end.
        * Each Summary response is fully-specified (all fields set).
      * start: Returns the state of each Summary at start, followed by updates until now.
        * Each Summary response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each Summary at start, followed by updates
        until end.
        * Each Summary response at start is fully-specified, but updates until end may
          be partial.
    """

    max_messages: "int | None" = aristaproto.field(4, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.UInt32Value, optional=True)
    """
    MaxMessages limits the maximum number of messages that can be contained in one batch.
    MaxMessages is required to be at least 1.
    The maximum number of messages in a batch is min(max_messages, INTERNAL_BATCH_LIMIT)
    INTERNAL_BATCH_LIMIT is set based on the maximum message size.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryBatchedStreamRequest", SummaryBatchedStreamRequest)


@dataclass(eq=False, repr=False)
class SummaryBatchedStreamResponse(aristaproto.Message):
    responses: "list[SummaryStreamResponse]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    Values are the values deemed relevant to the initiating request.
    The length of this structure is guaranteed to be between (inclusive) 1 and
    min(req.max_messages, INTERNAL_BATCH_LIMIT).
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryBatchedStreamResponse", SummaryBatchedStreamResponse)


@dataclass(eq=False, repr=False)
class SummaryKey(aristaproto.Message):
    """
    SummaryKey uniquely identifies a device summary request.
    """

    device_id: "str | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    device_id is the serial number of the device
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryKey", SummaryKey)


@dataclass(eq=False, repr=False)
class SummaryRequest(aristaproto.Message):
    key: "SummaryKey | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Key uniquely identifies a Summary instance to retrieve.
    This value must be populated.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryRequest", SummaryRequest)


@dataclass(eq=False, repr=False)
class SummaryResponse(aristaproto.Message):
    value: "Summary | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    Summary instance in this response.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryResponse", SummaryResponse)


@dataclass(eq=False, repr=False)
class SummarySomeRequest(aristaproto.Message):
    keys: "list[SummaryKey]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time indicates the time for which you are interested in the data.
    If no time is given, the server will use the time at which it makes the request.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummarySomeRequest", SummarySomeRequest)


@dataclass(eq=False, repr=False)
class SummarySomeResponse(aristaproto.Message):
    value: "Summary | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is the value requested.
    This structure will be fully-populated as it exists in the datastore. If
    optional fields were not given at creation, these fields will be empty or
    set to default values.
    """

    error: "str | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.StringValue, optional=True)
    """
    Error is an optional field.
    It should be filled when there is an error in the GetSome process.
    """

    time: "datetime.datetime | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time carries the (UTC) timestamp of the last-modification of the
    Summary instance in this response.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummarySomeResponse", SummarySomeResponse)


@dataclass(eq=False, repr=False)
class SummaryStreamRequest(aristaproto.Message):
    partial_eq_filter: "list[Summary]" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, repeated=True)
    """
    PartialEqFilter provides a way to server-side filter a GetAll/Subscribe.
    This requires all provided fields to be equal to the response.

    While transparent to users, this field also allows services to optimize internal
    subscriptions if filter(s) are sufficiently specific.
    """

    time: "__time__.TimeBounds | None" = aristaproto.field(3, aristaproto.TYPE_MESSAGE, optional=True)
    """
    TimeRange allows limiting response data to within a specified time window.
    If this field is populated, at least one of the two time fields are required.

    For GetAll, the fields start and end can be used as follows:

      * end: Returns the state of each Summary at end.
        * Each Summary response is fully-specified (all fields set).
      * start: Returns the state of each Summary at start, followed by updates until now.
        * Each Summary response at start is fully-specified, but updates may be partial.
      * start and end: Returns the state of each Summary at start, followed by updates
        until end.
        * Each Summary response at start is fully-specified, but updates until end may
          be partial.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryStreamRequest", SummaryStreamRequest)


@dataclass(eq=False, repr=False)
class SummaryStreamResponse(aristaproto.Message):
    value: "Summary | None" = aristaproto.field(1, aristaproto.TYPE_MESSAGE, optional=True)
    """
    Value is a value deemed relevant to the initiating request.
    This structure will always have its key-field populated. Which other fields are
    populated, and why, depends on the value of Operation and what triggered this notification.
    """

    time: "datetime.datetime | None" = aristaproto.field(2, aristaproto.TYPE_MESSAGE, unwrap=lambda: ___google__protobuf__.Timestamp, optional=True)
    """
    Time holds the timestamp of this Summary's last modification.
    """

    type: "__subscriptions__.Operation" = aristaproto.field(3, aristaproto.TYPE_ENUM, default_factory=lambda: __subscriptions__.Operation(0))
    """
    Operation indicates how the Summary value in this response should be considered.
    Under non-subscribe requests, this value should always be INITIAL. In a subscription,
    once all initial data is streamed and the client begins to receive modification updates,
    you should not see INITIAL again.
    """


default_message_pool.register_message("arista.imagestatus.v1", "SummaryStreamResponse", SummaryStreamResponse)


@dataclass(eq=False, repr=False)
class TerminAttrDiffsBySup(aristaproto.Message):
    """
    TerminAttrDiffsBySup is the terminattr diff information for each supervisor.
    """

    values: "dict[str, ExtensionDiff]" = aristaproto.field(
        1, aristaproto.TYPE_MAP, map_meta=aristaproto.map_meta(aristaproto.TYPE_STRING, aristaproto.TYPE_MESSAGE)
    )
    """
    values is the mapping of supervisor type to terminattr diff.
    """


default_message_pool.register_message("arista.imagestatus.v1", "TerminAttrDiffsBySup", TerminAttrDiffsBySup)


class SummaryServiceStub(aristaproto_grpcio.ServiceStub):
    async def get_one(
        self,
        message: "SummaryRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "SummaryResponse":

        return await self._unary_unary(
            "/arista.imagestatus.v1.SummaryService/GetOne",
            message,
            SummaryResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def get_some(
        self,
        message: "SummarySomeRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[SummarySomeResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/GetSome",
            message,
            SummarySomeResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def get_all(
        self,
        message: "SummaryStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[SummaryStreamResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/GetAll",
            message,
            SummaryStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe(
        self,
        message: "SummaryStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[SummaryStreamResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/Subscribe",
            message,
            SummaryStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def get_meta(
        self,
        message: "SummaryStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "MetaResponse":

        return await self._unary_unary(
            "/arista.imagestatus.v1.SummaryService/GetMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        )

    async def subscribe_meta(
        self,
        message: "SummaryStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[MetaResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/SubscribeMeta",
            message,
            MetaResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def get_all_batched(
        self,
        message: "SummaryBatchedStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[SummaryBatchedStreamResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/GetAllBatched",
            message,
            SummaryBatchedStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response

    async def subscribe_batched(
        self,
        message: "SummaryBatchedStreamRequest",
        *,
        timeout: "float | None" = None,
        metadata: "MetadataLike | None" = None,
        credentials: "grpc.CallCredentials | None" = None,
        wait_for_ready: "bool | None" = None,
    ) -> "AsyncIterator[SummaryBatchedStreamResponse]":

        async for response in self._unary_stream(
            "/arista.imagestatus.v1.SummaryService/SubscribeBatched",
            message,
            SummaryBatchedStreamResponse,
            timeout=timeout,
            metadata=metadata,
            credentials=credentials,
            wait_for_ready=wait_for_ready,
        ):
            yield response


from ....google import protobuf as ___google__protobuf__
from ... import subscriptions as __subscriptions__
from ... import time as __time__
