all:
  children:
    IGNORE_IN_PYTEST:
      hosts:
        host_ansible_only:
    EOS_DESIGNS_DEPRECATED_VARS:
      hosts:
        host1:
        host_ansible_only:
    TENANTS:
      children:
        EOS_DESIGNS_DEPRECATED_VARS:
