port_channel:
  load_balance_trident:
    udf_eth_type:
      ipv4:
        header:
          inner:
            l3:
              - offset: 30
                mask: "0x01"
              - offset: 10
                mask: "0xff"
              - offset: 2
            l4:
              - offset: 20
                mask: "0x02"
              - offset: 22
          outer:
            l2:
              - offset: 2
                mask: "0xff"
              - offset: 5
                mask: "0x02"
              - offset: 35
            l3:
              - offset: 3
                mask: "0x01"
              - offset: 5
            l4:
              - offset: 50
                mask: "0x04"
              - offset: 30
                mask: "0xff"
              - offset: 27
      ipv6:
        header:
          inner:
            l3:
              - offset: 30
                mask: "0x01"
              - offset: 10
                mask: "0xff"
            l4:
              - offset: 20
                mask: "0x02"
              - offset: 2
          outer:
            l2:
              - offset: 2
                mask: "0xff"
              - offset: 5
                mask: "0x02"
              - offset: 25
            l3:
              - offset: 3
                mask: "0x01"
            l4:
              - offset: 50
                mask: "0x04"
              - offset: 30
                mask: "0xff"
              - offset: 28
