port_channel:
  load_balance_trident_udf:
    - eth_type: ipv4
      ip_protocol: gre
      header: inner_l3
      offset: 30
      mask: "0x01"
    - eth_type: ipv4
      header: inner_l3
      offset: 10
      mask: "0xff"
    - eth_type: ipv4
      header: inner_l4
      offset: 2
    - eth_type: ipv4
      ip_protocol: 10
      header: inner_l4
      offset: 20
      mask: "0x02"
    - eth_type: ipv4
      header: inner_l3
      offset: 22
    - eth_type: ipv4
      header: outer_l2
      offset: 39
      ip_protocol: sctp
    - eth_type: ipv6
      header: outer_l3
      offset: 30
      mask: "0x01"
    - eth_type: ipv6
      header: inner_l3
      offset: 20
    - eth_type: ipv6
      ip_protocol: tcp
      header: outer_l4
      offset: 20
    - eth_type: ipv6
      ip_protocol: 2
      header: inner_l4
      offset: 10
      mask: "0x02"
