---
# Spine Switches
spine:
  defaults:
    platform: cEOSLab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    uplink_switches: [dc1-ss1, dc1-ss2] # Where the spine uplinks go
    uplink_ipv4_pool: 192.168.103.0/24 # For the p2p interfaces to chopped up into /31s
    evpn_route_servers: [dc1-ss1, dc1-ss2]
  nodes:
    - name: dc1-spine1
      id: 11
      mgmt_ip: 172.16.1.11/24
      uplink_switch_interfaces: [Ethernet1, Ethernet1]
    - name: dc1-spine2
      id: 12
      mgmt_ip: 172.16.1.12/24
      uplink_switch_interfaces: [Ethernet2, Ethernet2]

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65100-65199 # Gives a range which will be auto-assigned
    platform: cEOSLab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.102.0/24 # This is loopback1 (VTEP)
    uplink_switches: [dc1-spine1, dc1-spine2] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.103.0/24 # For the p2p interfaces, /31s
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_settings:
      mode: mstp # Spanning Tree is still enabled even in EVPN setups
      priority: 16384

  node_groups:
    - group: dc1-leaf1
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.21/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.22/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
