---
### group_vars/DC1.yml

# Default gateway used for the management interface
mgmt_gateway: 172.16.1.1

devices:
  # Name of the node to be defined (must be consistent with definition in inventory)
  - name: dc1-spine1
    profile: dc1-spine
    # Device ID definition. An integer number used for internal calculations (ie. IPv4 address of the loopback_ipv4_pool among others)
    id: 1
    # Management IP to be assigned to the management interface
    mgmt_ip: 172.16.1.11/24

  - name: dc1-spine2
    profile: dc1-spine
    id: 2
    mgmt_ip: 172.16.1.12/24

device_profiles:
  - name: dc1-spine
    role: spine
    # Set the relevant platform as each platform has different default values in AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # ASN to be used by BGP
    bgp_as: 65100

  - name: dc1-l3leaf
    role: l3leaf
    # Set the relevant platform as each platform has different default values in AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.0.0/27
    # Offset all assigned loopback IP addresses.
    # Required when the < loopback_ipv4_pool > is same for 2 different node_types (like spine and l3leaf) to avoid over-lapping IPs.
    # For example, set the minimum offset l3leaf.defaults.loopback_ipv4_offset: < total # spine switches > or vice versa.
    loopback_ipv4_offset: 2
    # Definition of pool of IPs to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    # Name of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: [dc1-spine1, dc1-spine2]
    # Definition of pool of IPs to be used in P2P links
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  - name: DC1_L3_LEAF2
    parent_profile: dc1-l3leaf
    mlag_group: DC1_L3_LEAF2
    bgp_as: 65102
    evpn_gateway:
      # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
      evpn_l2:
        enabled: true
      evpn_l3:
        enabled: true
        inter_domain: true

  - name: dc1-l2leaf
    role: l2leaf
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    spanning_tree_mode: mstp

# match_devices:
#   - hostname_pattern: dc1-leaf1[ab]
#     profile: dc1-l3leaf
#     mlag_group: DC1_L3_LEAF1
#     # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
#     bgp_as: 65101
