---
### group_vars/DC2.yml

mgmt_gateway: 172.16.1.1 # (1)!

spine:
  defaults:
    platform: vEOS-lab # (2)!
    loopback_ipv4_pool: 10.255.128.0/27 # (3)!
    bgp_as: 65200 # (4)!

  nodes: # (5)!
    - name: dc2-spine1
      id: 11 # (6)!
      mgmt_ip: 172.16.1.21/24 # (7)!

    - name: dc2-spine2
      id: 12
      mgmt_ip: 172.16.1.22/24

l3leaf:
  defaults:
    platform: vEOS-lab # (8)!
    loopback_ipv4_pool: 10.255.128.0/27 # (9)!
    loopback_ipv4_offset: 2 (10)!
    vtep_loopback_ipv4_pool: 10.255.129.0/27 # (11)!
    uplink_switches: [dc2-spine1, dc2-spine2] # (12)!
    uplink_ipv4_pool: 10.255.255.64/26 # (13)!
    mlag_peer_ipv4_pool: 10.255.129.64/27 # (14)!
    mlag_peer_l3_ipv4_pool: 10.255.129.96/27 # (15)!
    virtual_router_mac_address: 00:1c:73:00:00:99 # (16)!
    spanning_tree_priority: 4096 # (17)!
    spanning_tree_mode: mstp # (18)!

  node_groups: # (19)!
    - group: DC2_L3_LEAF1
      bgp_as: 65201 # (20)!
      nodes:
        - name: dc2-leaf1a
          id: 11
          mgmt_ip: 172.16.1.111/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: dc2-leaf1b
          id: 12
          mgmt_ip: 172.16.1.112/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]

    - group: DC2_L3_LEAF2
      bgp_as: 65202
      evpn_gateway: # (21)!
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: dc2-leaf2a
          id: 13
          mgmt_ip: 172.16.1.113/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
          evpn_gateway:
            remote_peers: # (22)!
              - hostname: dc1-leaf2a
        - name: dc2-leaf2b
          id: 14
          mgmt_ip: 172.16.1.114/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
          evpn_gateway:
            remote_peers:
              - hostname: dc1-leaf2b

l2leaf:
  defaults:
    platform: vEOS-lab
    spanning_tree_mode: mstp

  node_groups:
    - group: DC2_L2_LEAF1
      uplink_switches: [dc2-leaf1a, dc2-leaf1b]
      nodes:
        - name: dc2-leaf1c
          id: 11
          mgmt_ip: 172.16.1.161/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]

    - group: DC2_L2_LEAF2
      uplink_switches: [dc2-leaf2a, dc2-leaf2b]
      nodes:
        - name: dc2-leaf2c
          id: 12
          mgmt_ip: 172.16.1.162/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8]
