---
### group_vars/DC2_SPINES.yml

type: spine

spine:
  defaults:
    platform: cEOSLab # (1)!
    loopback_ipv4_pool: 10.255.128.0/27 # (2)!
    bgp_as: 65200 # (3)!

  nodes: # (4)!
    - name: dc2-spine1
      id: 1 # (5)!
      mgmt_ip: 172.16.1.21/24 # (6)!

    - name: dc2-spine2
      id: 2
      mgmt_ip: 172.16.1.22/24
