aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 192.168.1.12:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvsourceintf: Management1
  cvvrf: MGMT
  disable_aaa: true
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet1
  description: L2_htns-l3-leaf1_Ethernet8
  shutdown: false
  channel_group:
    id: 1
    mode: active
  metadata:
    peer: htns-l3-leaf1
    peer_interface: Ethernet8
    peer_type: l3leaf
- name: Ethernet2
  description: SERVER_webserver1_NIC1
  shutdown: false
  metadata:
    peer: webserver1
    peer_interface: NIC1
    peer_type: server
    peer_key: servers
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 100-101
hostname: htns-l2-leaf1
ip_domain_lookup:
  source_interfaces:
  - name: Management1
    vrf: MGMT
ip_igmp_snooping:
  globally_enabled: true
ip_name_server:
  vrfs:
  - name: MGMT
    servers:
    - ip_address: 192.168.1.1
local_users:
- name: admin
  privilege: 15
  role: network-admin
  no_password: true
- name: arista
  privilege: 15
  role: network-admin
  sha512_password: $6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1.
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 172.16.1.251/24
  type: oob
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: FABRIC
  validate_hardware:
    enabled: false
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.pool.ntp.org
    preferred: true
  vrf: MGMT
port_channel_interfaces:
- name: Port-Channel1
  description: L2_HTNS_L3_LEAFS_Port-Channel8
  shutdown: false
  switchport:
    enabled: true
    mode: trunk
    trunk:
      allowed_vlan: 100-101
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 100
  name: Production_App1
  metadata:
    tenants:
    - TENANT1
- id: 101
  name: Production_DB
  metadata:
    tenants:
    - TENANT1
vrfs:
- name: MGMT
  ip_routing: false
