---
- name: "{{ test_id | upper }} Converge - Configuration deployment with CVP using manifest alongside regular deployment"
  hosts: SITE1_FABRIC
  connection: local
  gather_facts: false
  vars:
    cv_server: "{{ lookup('env', 'CV_SERVER') }}"
    cv_token: "{{ lookup('env', 'CV_ACCESS_TOKEN') }}"
    proxy_host: "{{ lookup('env', 'CV_PROXY_HOST') | default('', true) }}"
    proxy_port: "{{ lookup('env', 'CV_PROXY_PORT') | default(3128, true) | int }}"
    proxy_username: "{{ lookup('env', 'CV_PROXY_USERNAME') | default('', true) }}"
    proxy_password: "{{ lookup('env', 'CV_PROXY_PASSWORD') | default('', true) }}"
    cv_verify_certs: "{{ lookup('env', 'CV_VERIFY_CERTS') | default(true, true) | bool }}"
    cv_skip_missing_devices: true
    eos_config_dir: "{{ playbook_dir }}/intended/configs/test_configs"
    structured_dir: "{{ playbook_dir }}/intended/structured_configs/test_configs"
    test_id: "manifest-with-regular"
    cv_common_pattern: "avd_cv-deploy_{{ test_id }}"

  tasks:
    - name: "{{ test_id | upper }} Banner"
      tags: ["{{ test_id }}"]
      run_once: true
      ansible.builtin.debug:
        msg:
          - "{{ ('#' * (31 + test_id | length))[:100] }}"
          - "### STARTING MOLECULE TEST {{ test_id[:69] | upper }} ###"
          - "{{ ('#' * (31 + test_id | length))[:100] }}"

    - name: "{{ test_id | upper }} {{ 'Read' if lookup('env', 'MOLECULE_EXECUTION_ID') else 'Generate' }} molecule execution ID"
      tags: ["{{ test_id }}"]
      run_once: true
      ansible.builtin.set_fact:
        r: "{{ lookup('env', 'MOLECULE_EXECUTION_ID') or lookup('password', '/dev/null chars=ascii_lowercase,digits length=4') }}"

    - name: "{{ test_id | upper }} Code block to provision CVP with AVD configuration and manifest"
      tags: ["{{ test_id }}"]
      run_once: true
      delegate_to: localhost

      block:

        - name: "(BLOCK) {{ test_id | upper }} Banner"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.debug:
            msg:
              - "### ENGAGE CV_DEPLOY ROLE WITH MANIFEST AND REGULAR DEPLOYMENT FOR {{ test_id[:69] | upper }} ###"

        - name: "(BLOCK) {{ test_id | upper }} Provision CVP with AVD configuration and manifest"
          tags: ["{{ test_id }}"]
          run_once: true
          delegate_to: localhost
          ansible.builtin.import_role:
            name: arista.avd.cv_deploy
          vars:
            cv_workspace_name: "{{ cv_common_pattern }}_{{ r }}_converge"
            cv_workspace_description: "{{ (cv_common_pattern + '_' + r + '_converge') | upper }}"
            cv_change_control_name: "{{ cv_common_pattern }}_{{ r }}_converge"
            cv_change_control_description: "{{ (cv_common_pattern + '_' + r + '_converge') | upper }}"
            cv_register_detailed_results: true
            cv_submit_workspace_force: true
            cv_run_change_control: true
            cv_static_config_manifest:
              configlets:
                - name: "TEST-MANIFEST-ALIAS"
                  file: "{{ playbook_dir }}/intended/configlets/test_manifest_alias.txt"
                - name: "TEST-MANIFEST-ACCESS-LISTS"
                  file: "{{ playbook_dir }}/intended/configlets/test_manifest_access_lists.txt"
              containers:
                - name: "AVD-MANIFEST-ROOT"
                  description: "Root container for AVD manifest deployment"
                  # Tag query to match avd-ci-leaf1 (device tag is a part of the base configuration)
                  tag_query: "dummy_name:dummy_val"
                  sub_containers:
                    - name: "AVD-MANIFEST-CHILD"
                      description: "Child container for AVD manifest deployment"
                      tag_query: "device:avd-ci-leaf1"
                      configlets:
                        - name: "TEST-MANIFEST-ACCESS-LISTS"

        - name: "(BLOCK) {{ test_id | upper }} Check CVP returns"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.assert:
            that:
              # workspace
              - cv_deploy_results.workspace.name == cv_workspace_name
              - cv_deploy_results.workspace.state == "submitted"
              - cv_deploy_results.workspace.description == cv_workspace_description
              # errors and warnings
              - cv_deploy_results.errors == []
              - cv_deploy_results.warnings | default([]) | length == 0
              # tags
              - cv_deploy_results.deployed_device_tags != []
              - cv_deploy_results.deployed_interface_tags != []
              # Change control
              - cv_deploy_results.change_control.name == cv_change_control_name
              - cv_deploy_results.change_control.description == cv_change_control_description
              - cv_deploy_results.change_control.requested_state == "completed"
              - cv_deploy_results.change_control.state == "completed"
          vars:
            cv_workspace_name: "{{ cv_common_pattern }}_{{ r }}_converge"
            cv_workspace_description: "{{ (cv_common_pattern + '_' + r + '_converge') | upper }}"
            cv_change_control_name: "{{ cv_common_pattern }}_{{ r }}_converge"
            cv_change_control_description: "{{ (cv_common_pattern + '_' + r + '_converge') | upper }}"

        - name: "(BLOCK) {{ test_id | upper }} Verify manifest configlets were deployed"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.assert:
            that:
              - cv_deploy_results.deployed_static_config_configlets is defined
              - "'TEST-MANIFEST-ACCESS-LISTS' in cv_deploy_results.deployed_static_config_configlets | map(attribute='name') | list"
              - "'TEST-MANIFEST-ALIAS' in cv_deploy_results.deployed_static_config_configlets | map(attribute='name') | list"

        - name: "(BLOCK) {{ test_id | upper }} Verify manifest containers were deployed"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.assert:
            that:
              - cv_deploy_results.deployed_static_config_containers is defined
              - cv_deploy_results.deployed_static_config_containers | length == 1
              # AVD-MANIFEST-ROOT (root container)
              - (cv_deploy_results.deployed_static_config_containers | selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).configlets | length == 0
              - >
                (cv_deploy_results.deployed_static_config_containers | selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).description ==
                'Root container for AVD manifest deployment'
              - (cv_deploy_results.deployed_static_config_containers | selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).match_policy == 'match_all'
              - (cv_deploy_results.deployed_static_config_containers | selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | length == 1
              - >
                (cv_deploy_results.deployed_static_config_containers | selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).tag_query ==
                'dummy_name:dummy_val'
              # AVD-MANIFEST-CHILD (nested sub-container)
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).configlets | length == 1
              - >
                'TEST-MANIFEST-ACCESS-LISTS' in
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).configlets
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).description ==
                'Child container for AVD manifest deployment'
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).match_policy == 'match_all'
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).name == 'AVD-MANIFEST-CHILD'
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).sub_containers | length == 0
              - >
                ((cv_deploy_results.deployed_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-ROOT') | first).sub_containers | first).tag_query == 'device:avd-ci-leaf1'
              # AVD-MANIFEST-CHILD (standalone container) is not "pushed" because cleanup only deletes container
              # but not assignment and reference to the configlets
              - cv_deploy_results.skipped_static_config_containers is defined
              - cv_deploy_results.skipped_static_config_containers | length == 1
              - >
                (cv_deploy_results.skipped_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-CHILD') | first).configlets | first == 'TEST-MANIFEST-ACCESS-LISTS'
              - >
                (cv_deploy_results.skipped_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-CHILD') | first).description == 'Child container for AVD manifest deployment'
              - >
                (cv_deploy_results.skipped_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-CHILD') | first).match_policy == 'match_all'
              - >
                (cv_deploy_results.skipped_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-CHILD') | first).sub_containers | length == 0
              - >
                (cv_deploy_results.skipped_static_config_containers |
                selectattr('name', 'eq', 'AVD-MANIFEST-CHILD') | first).tag_query == 'device:avd-ci-leaf1'

        - name: "(BLOCK) {{ test_id | upper }} Verify regular AVD device configs were deployed"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.assert:
            that:
              - cv_deploy_results.deployed_configs is defined
              - cv_deploy_results.deployed_configs | length > 0
              # Assert that device targeted by manifest got AVD configlet deployed
              - "'AVD-avd-ci-leaf1' in cv_deploy_results.deployed_configs | map(attribute='configlet_name') | list"
              # Assert that at least one device not targeted by manifest got AVD configlet deployed
              - "'AVD-avd-ci-leaf2' in cv_deploy_results.deployed_configs | map(attribute='configlet_name') | list"

      always:

        - name: "(ALWAYS) {{ test_id | upper }} Display CVP detailed result"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.debug:
            var: cv_deploy_results

        - name: "(ALWAYS) {{ test_id | upper }} Banner"
          tags: ["{{ test_id }}"]
          run_once: true
          ansible.builtin.debug:
            msg:
              - "### ENGAGE CV_DEPLOY ROLE TO CLEANUP AFTER {{ test_id[:69] | upper }} ###"

        - name: "(ALWAYS) {{ test_id | upper }} Cleanup manifest with regular configlets"
          tags: ["{{ test_id }}"]
          run_once: true
          delegate_to: localhost
          ansible.builtin.import_role:
            name: arista.avd.cv_deploy
          vars:
            cv_workspace_name: "{{ cv_common_pattern }}_{{ r }}_cleanup"
            cv_workspace_description: "{{ (cv_common_pattern + '_' + r + '_cleanup') | upper }}"
            cv_change_control_name: "{{ cv_common_pattern }}_{{ r }}_cleanup"
            cv_change_control_description: "{{ (cv_common_pattern + '_' + r + '_cleanup') | upper }}"
            cv_register_detailed_results: true
            cv_devices: "{{ ansible_play_hosts_all }}"
            eos_config_dir: "{{ playbook_dir }}/intended/configs/base_configs"
            structured_dir: "{{ playbook_dir }}/intended/structured_configs/base_configs"
            cv_submit_workspace_force: true
            cv_run_change_control: true
            cv_static_config_manifest:
              containers:
                - name: "AVD-MANIFEST-ROOT"
                  tag_query: "dummy_name:dummy_val"
