aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
ethernet_interfaces:
- name: Ethernet6
  description: P2P_digital-twin-ethernet-ports-1_Ethernet6
  shutdown: false
  mtu: 9214
  ip_address: 192.168.3.113/31
  metadata:
    peer: digital-twin-ethernet-ports-1
    peer_interface: Ethernet6
    peer_type: l3leaf
  switchport:
    enabled: false
hostname: digital-twin-ethernet-ports-3
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 192.168.3.129/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 192.168.3.145/32
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.169.3.3/32
  type: oob
metadata:
  is_deployed: true
  platform: custom-platform
  fabric_name: DIGITAL_TWIN
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.3.128/28 eq 32
  - sequence: 20
    action: permit 192.168.3.144/28 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65001'
  router_id: 192.168.3.129
  maximum_paths:
    paths: 4
  updates:
    wait_install: true
  bgp:
    default:
      ipv4_unicast: false
  peer_groups:
  - name: IPv4-UNDERLAY-PEERS
    metadata:
      type: ipv4
    send_community: all
    maximum_routes: 256000
  neighbors:
  - ip_address: 192.168.3.112
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65001'
    metadata:
      peer: digital-twin-ethernet-ports-1
    description: digital-twin-ethernet-ports-1_Ethernet6
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
  address_family_ipv4:
    peer_groups:
    - name: IPv4-UNDERLAY-PEERS
      activate: true
  vrfs:
  - name: TENANT_A_VRF_A
    rd: 192.168.3.129:1025
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 1025:1025
      export:
      - address_family: evpn
        route_targets:
        - 1025:1025
    router_id: 192.168.3.129
    redistribute:
      connected:
        enabled: true
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan1
  description: TENANT_A_VRF_A_SVI_A
  shutdown: false
  vrf: TENANT_A_VRF_A
  metadata:
    tenants:
    - TENANT_A
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 1
  name: TENANT_A_VRF_A_SVI_A
  metadata:
    tenants:
    - TENANT_A
vrfs:
- name: MGMT
  ip_routing: false
- name: TENANT_A_VRF_A
  ip_routing: true
  metadata:
    tenants:
    - TENANT_A
vxlan_interface:
  vxlan1:
    description: digital-twin-ethernet-ports-3_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
      vrfs:
      - name: TENANT_A_VRF_A
        vni: 1025
