---
# --8<-- [start:endpoints]
# Servers connected to the L2 ring. With `filter.only_vlans_in_use: true` on a
# ring node, AVD only configures VLANs that have an endpoint on this node *or*
# are needed by a downstream ring member declared via `uplink_switches`.
servers:
  - name: server-leaf2
    adapters:
      - switches: [htl2r-l2leaf2]
        switch_ports: [Ethernet10]
        endpoint_ports: [nic1]
        vlans: 100,200
        mode: trunk
  - name: server-leaf3
    adapters:
      - switches: [htl2r-l2leaf3]
        switch_ports: [Ethernet10]
        endpoint_ports: [nic1]
        vlans: 101,200
        mode: trunk
# --8<-- [end:endpoints]
