# Custom router ospf structured_config to test
custom_structured_configuration_router_ospf:
  process_ids:
  - id: 16
    vrf: Tenant_A_OSPF
    passive_interface_default: true
    router_id: 10.255.11.10
    no_passive_interfaces:
    - Ethernet22
    - Ethernet23
