# Custom vxlan structured_config to validate that the vxlan interface is skipped when using ipv6 encapsulation in combination with dps source interface
custom_structured_configuration_vxlan_interface:
  vxlan1:
    description: dc1-leaf1c_VTEP
    vxlan:
      source_interface: Dps1
      udp_port: 4789
      encapsulations:
        ipv6: true
      vlans:
      - id: 11
        vni: 10011
      vrfs:
      - name: VRF10
        vni: 10

custom_structured_configuration_dps_interfaces:
- name: Dps1
  description: DPS Interface
  mtu: 9194
  ip_address: 10.255.1.1/32
