---
all:
  children:
    DIGITAL_TWIN_CONTAINERLAB_UNSUPPORTED_MGMT_IP:
      children:
        DIGITAL_TWIN_CONTAINERLAB_UNSUPPORTED_MGMT_IP_DHCP:
          hosts:
            containerlab-dhcp-mgmt:
              ansible_host: containerlab-dhcp-mgmt
        DIGITAL_TWIN_CONTAINERLAB_UNSUPPORTED_MGMT_IP_EMPTY:
          hosts:
            containerlab-empty-mgmt:
              ansible_host: containerlab-empty-mgmt
        DIGITAL_TWIN_CONTAINERLAB_UNSUPPORTED_MGMT_IP_NULL:
          hosts:
            containerlab-null-mgmt:
              ansible_host: containerlab-null-mgmt
    DIGITAL_TWIN_CONTAINERLAB_MULTIPLE_MGMT_SUBNETS:
      hosts:
        containerlab-subnet-a:
          ansible_host: containerlab-subnet-a
        containerlab-subnet-b:
          ansible_host: containerlab-subnet-b
