[build-system]
requires = ["setuptools", "setuptools-rust>=1.12.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyavd-utils"
version = "0.0.1"

[dependency-groups]
pytest = ["pytest"]
coverage = ["coverage[toml]"]

[tool.distutils.bdist_wheel]
py-limited-api = "cp310"

[tool.setuptools.packages.find]
include = ["pyavd_utils"]

[tool.setuptools.package-data]
"pyavd_utils" = ["*.pyi"]

[[tool.setuptools-rust.ext-modules]]
target = "pyavd_utils.passwords"
path = "rust/pypasswords/Cargo.toml"
binding = "PyO3"

[[tool.setuptools-rust.ext-modules]]
target = "pyavd_utils.validation"
path = "rust/pyvalidation/Cargo.toml"
binding = "PyO3"

[tool.pytest.ini_options]
testpaths = "tests"
