---
### Errdisable ###

errdisable:
  detect:
    causes:
      - "acl"
      - "arp-inspection"
      - "dot1x-coa"
      - "dot1x-phone-classification"
      - "dot1x-session-replace"
      - "link-change"
      - "stp-no-portid"
      - "tapagg"
  recovery:
    causes:
      - name: bpduguard
        interval: 400
      - name: dot1x-session-replace
        interval: 500
      - name: hitless-reload-down
      - name: stp-no-portid
      - name: link-flap
      - name: no-internal-vlan
      - name: tapagg
      - name: uplink-failure-detection
      - name: arp-inspection
      - name: acl
      - name: dot1x-coa
      - name: dot1x-phone-classification
    interval: 300
