---
### IP TACACS source interface ###
avd_design_future:
  ip_tacacs_source_interface_setting: true
ip_tacacs:
  source_interface: Loopback10
  vrfs:
  - name: TEST1
    source_interface: Loopback3
  - name: default
    source_interface: Loopback1
