---
## IP TELNET CLIENT SOURCE INTERFACES ##

ip_telnet_client:
  vrfs:
    - source_interface: Loopback0
      name: data
    - name: MGMT
      source_interface: Management0
  source_interface: Ethernet10
