---
### Management Security ###
management_security:
  auto_certificate:
    profiles:
      - name: AVD_AUTO_CERTIFICATE_PROFILE
        digest: sha512
        key: SSL_KEY
        protocol_instance_name: AVD_EST_PROTOCOL_token
        parameters:
          distinguished_name:
            common_name: 00:1c:73:ff:ff:ff
            country: US
            email: noreply@arista.com
            locality: Santa Clara
            organization: Arista Networks
            organization_unit: AVD
            serial_number: 123abc
            state: CA
          subject_alternative_name:
            dns:
              - bbb.arista.com
              - avd.arista.com
            email:
              - support@arista.com
              - noreply@arista.com
            ip:
              - 198.51.100.43
              - 198.51.100.42
            uri:
              - https://bbb.arista.com/
              - https://avd.arista.com/
      - name: AVD_AUTO_CERTIFICATE_PROFILE_system
        key: SSL_KEY
        protocol_instance_name: AVD_EST_PROTOCOL_secret
        renewal: 86400
        parameters:
          distinguished_name:
            common_name: 00:1c:73:aa:aa:aa
            country: US
            email: noreply@arista.com
            locality: Santa Clara
            organization: Arista Networks
            organization_unit: AVD
            serial_number: system
            state: CA
    protocols:
      - name: AVD_EST_PROTOCOL_token
        protocol: est
        connection_retry:
          interval: 30
          exponential_backoff: true
          count: 100
        server:
          url: https://test_est.example.com/test
          vrf: MGMT
          ssl_profile: SSL_PROFILE
        credentials:
          enroll:
            # token_type defaults to "7"
            token: 03175E08140A35735D0C1A171206341F012939213C
          re_enroll:
            # token_type defaults to "7"
            token: 03175E08140A35735D0C1A171206341F012939213C
      - name: AVD_EST_PROTOCOL_non_user
        protocol: est
        credentials:
          enroll:
            secret: 00171605165E1F
            secret_type: "7"
          re_enroll:
            secret: 00171605165E1F
            secret_type: "0"
      - name: AVD_EST_PROTOCOL_secret
        protocol: est
        server:
          url: https://test_est.example.com/test1
          ssl_profile: SSL_PROFILE
        connection_retry:
          count: 100
        credentials:
          enroll:
            username: est_authentication
            secret: 00171605165E1F
            secret_type: "7"
          re_enroll:
            username: est_authentication
            secret: 00171605165E1F
            secret_type: "0"
      - name: AVD_EST_PROTOCOL_both
        protocol: est
        disabled: true
        connection_retry:
          interval: 30
          exponential_backoff: false
          count: 100
        server:
          url: https://test_est.example.com/test2
          vrf: MGMT
          ssl_profile: SSL_PROFILE
        credentials:
          enroll:
            # token should take precedence; token_type "0" tested here
            username: est_authentication
            secret: 00171605165E1F
            token: 03175E08140A35735D0C1A171206341F012939213C
            token_type: "0"
  entropy_sources:
    hardware: true
    haveged: true
    cpu_jitter: true
    hardware_exclusive: true
  password:
    minimum_length: 17
    encryption_key_common: true
    encryption_reversible: aes-256-gcm
    policies:
      - name: AVD_POLICY
        minimum:
          digits: 1
          length: 2
          lower: 3
          special: 4
          upper: 5
        maximum:
          repetitive: 6
          sequential: 7
  signature_verification:
    enabled: true
    ssl_profile: cipher-v1.0-v1.3
  ssl_profiles:
    - name: SSL_PROFILE
      fips_restrictions: true
      tls_versions: 1.1 1.2
      certificate:
        file: SSL_CERT
        key: SSL_KEY
    - name: tls-versions-profile
      fips_restrictions: true
      tls_versions: "1.0 1.1"
    - name: cipher-list-profile
      fips_restrictions: false
      cipher_list: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384
    - name: certificate-profile
      fips_restrictions: false
      certificate:
        file: eAPI.crt
        key: eAPI.key
      certificate_revocation_lists:
        - intermediate.crl
        - ca.crl
    - name: tls-single-version-profile-as-string
      tls_versions: "1.1"
    - name: tls-single-version-profile-as-float
      tls_versions: 1.0
    - name: test1-trust-cert
      trust_certificate:
        certificates:
          - test-trust1.crt
          - test-trust2.crt
        requirement:
          basic_constraint_ca: true
        policy_expiry_date_ignore: true
    - name: test1-chain-cert
      chain_certificate:
        certificates:
          - test-chain-cert1.crt
          - test-chain-cert2.crt
        requirement:
          basic_constraint_ca: true
    - name: test2-trust-cert
      trust_certificate:
        requirement:
          hostname_fqdn: true
        system: true
    - name: test2-chain-cert
      chain_certificate:
        requirement:
          include_root_ca: true
  shared_secret_profiles:
    - profile: profile0
      secrets:
        - name: Secret1
          secret: $1c$mNvaIXPetcQ3hy7oUnTU3w==
          receive_lifetime:
            start_date_time: 12/20/2024 10:00:00
            end_date_time: 12/20/2025 10:00:00
          transmit_lifetime:
            infinite: true
          local_time: true
        - name: Secret2
          secret: $1c$mNvaIXPetcSA2UnFwIaxwA==
          secret_type: "7"
          receive_lifetime:
            infinite: true
          transmit_lifetime:
            infinite: true
    - profile: profile1
      secrets:
        - name: Secret3
          secret: $Ra3am9YZlbg5d65txucxTg==$DMoPxa9Wu5elK39pofFgaw==$zgEBfv+w/AIr1FnW
          secret_type: "8a"
          receive_lifetime:
            start_date_time: "2024-12-20 10:00:00"
            end_date_time: "2025-12-20 10:00:00"
          transmit_lifetime:
            start_date_time: "12/20/2024 10:00:00"
            end_date_time: "12/10/2025 10:00:00"
    - profile: profile2
      secrets:
        - name: Secret4
          secret: name1_secret
          secret_type: "0"
          receive_lifetime:
            start_date_time: "2024-12-20 10:00:00"
            end_date_time: "2025-12-20 10:00:00"
          transmit_lifetime:
            start_date_time: "2024-12-20 10:00:00"
            end_date_time: "2025-12-20 10:00:00"
