---
## Radius Servers
radius_server:
  deadtime: 10
  attribute_32_include_in_access_req:
    hostname: true
  dynamic_authorization:
    port: 1700
    tls_ssl_profile: SSL_PROFILE
  tls_ssl_profile: GLOBAL_RADIUS_SSL_PROFILE
  servers:
    - host: 10.10.10.158
      key: 071B245F5A
      timeout: 1
      retransmit: 1
    - host: 10.10.11.156
      timeout: 1
      retransmit: 1
      key: 071B245F5A
      tls:
        enabled: true
        port: 1700
    - host: 10.10.11.156
      timeout: 34
      retransmit: 45
      key: 071B245F5A
    - host: 10.10.11.156
      tls:
        enabled: true
        port: 345
    - host: 10.10.10.249
      key: secret
      key_type: 0
      timeout: 1
      retransmit: 1
    - host: 10.10.10.249
      key: $kUVyoj7FVQ//yw9D2lbqjA==$kxxohBiofI46IX3pw18KYQ==$DOOM0l9uU4TrQt2kyA7XCKtjUA==
      key_type: 8a
      timeout: 1
      retransmit: 1
  vrfs:
    - name: mgt
      servers:
        - host: 10.10.10.157
          key: 071B245F5A
          timeout: 1
          retransmit: 1
        - host: 10.10.11.159
          retransmit: 1
          key: 071B245F5A
        - host: 10.10.11.160
          timeout: 1
          key: $kUVyoj7FVQ//yw9D2lbqjA==$kxxohBiofI46IX3pw18KYQ==$DOOM0l9uU4TrQt2kyA7XCKtjUA==
          key_type: 8a
        - host: 10.10.11.248
          key: Secret
          key_type: 0
        - host: 10.10.11.155
          timeout: 1
          retransmit: 1
          tls:
            enabled: true
            ssl_profile: HOST_SSL_PROFILE
            port: 2083
          key: 071B245F5B
        - host: 10.10.11.158
          tls:
            enabled: true
            ssl_profile: SSL_PROFILE
