# Copyright (c) 2023-2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  avd_eos_cli_config_gen_input_dir:
    type: str
    documentation_options:
      table: role-settings
    description: |
      When running `eos_cli_config_gen` in standalone mode (not as part of `eos_designs` workflow),
      this variable can be used to point to a directory containing the structured configuration files to use as input.
