---
# Copyright (c) 2024-2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  eos_cli_config_gen_validate_inputs_batch_size:
    documentation_options:
      table: role-settings
    type: int
    default: 10
    description: |-
      The number of hosts to process in each batch when validating inputs.
      Depending on your inventory size and the available resources, you may want to adjust this number.
