---
all:
  children:
    DIGITAL_TWIN:
      children:
        DIGITAL_TWIN_DEFAULT_INTERFACES:
          hosts:
            digital-twin-default-interfaces-original-platform:
              type: l2leaf
            digital-twin-default-interfaces-digital-twin-platform:
              type: l2spine
              digital_twin:
                fabric: {}
                use_default_interfaces_of_digital_twin_platform: true
        CLEAN_UNIT_TESTS: # Single Devices testing one specific case and only using hostvars
          hosts:
            digital-twin-enforce-eapi-1:
              type: l2leaf
            digital-twin-enforce-eapi-2:
              type: l2leaf
            digital-twin-enforce-eapi-3:
              type: l2leaf
            digital-twin-enforce-eapi-4:
              type: l2leaf
            digital-twin-adjust-oob-mgmt-1:
              type: l2leaf
            digital-twin-adjust-oob-mgmt-2:
              type: l2leaf
            digital-twin-adjust-oob-mgmt-3:
              type: l2leaf
            digital-twin-adjust-oob-mgmt-4:
              type: l2leaf
