---
all:
  children:
    DIGITAL_TWIN:
      children:
        DIGITAL_TWIN_DEFAULT_INTERFACES:
          hosts:
            DIGITAL_TWIN_DEFAULT_INTERFACES_ORIGINAL_PLATFORM:
              type: l2leaf
            DIGITAL_TWIN_DEFAULT_INTERFACES_DIGITAL_TWIN_PLATFORM:
              type: l2spine
              digital_twin:
                fabric: {}
                use_default_interfaces_of_digital_twin_platform: true
