aaa_root:
  disabled: true
config_end: true
daemon_terminattr:
  cvaddrs:
  - 10.20.30.40:9910
  cvauth:
    method: token
    token_file: /tmp/token
  cvsourceintf: Management1
  cvvrf: MGMT
  disable_aaa: false
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
enable_password:
  disabled: true
hostname: digital-twin-cv-instance-1
ip_igmp_snooping:
  globally_enabled: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.10/32
  type: oob
  gateway: 192.168.1.254
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: DIGITAL_TWIN
  validate_hardware:
    enabled: false
  digital_twin:
    environment: act
    node_type: veos
    ip_addr: 192.168.1.10/32
    version: 4.33.1.1F
    username: cvpadmin
    password: cvp123!
    cv_instance: 10.20.30.40:9910
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.pool.ntp.org
    preferred: true
  vrf: MGMT
service_routing_protocols_model: multi-agent
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 192.168.1.254
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
