aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: digital-twin-adjust-oob-mgmt-3
ip_igmp_snooping:
  globally_enabled: true
management_api_http:
  enable_https: true
  enable_vrfs:
  - name: INBAND_MGMT
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: DIGITAL_TWIN
  validate_hardware:
    enabled: false
  digital_twin:
    environment: act
    node_type: veos
    ip_addr: 192.168.1.3/32
    version: 4.33.1.1F
    username: cvpadmin
    password: cvp123!
service_routing_protocols_model: multi-agent
tcam_profile: null
transceiver_qsfp_default_mode_4x10: true
vlan_interfaces:
- name: Vlan4092
  description: Inband Management
  shutdown: false
  vrf: INBAND_MGMT
  ip_address: 192.168.1.3/32
  mtu: 1500
  metadata:
    type: inband_mgmt
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vlans:
- id: 4092
  name: INBAND_MGMT
  metadata:
    tenants:
    - system
vrfs:
- name: MGMT
  ip_routing: false
- name: INBAND_MGMT
