aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: device-profile-infinite-inheritance
ip_igmp_snooping:
  globally_enabled: true
ip_routing: true
ip_virtual_router_mac_address: 00:1c:73:00:00:99
loopback_interfaces:
- name: Loopback0
  description: ROUTER_ID
  shutdown: false
  ip_address: 10.255.0.3/32
- name: Loopback1
  description: VXLAN_TUNNEL_SOURCE
  shutdown: false
  ip_address: 10.255.1.3/32
metadata:
  is_deployed: true
  platform: vEOS-lab
  fabric_name: FABRIC_DEVICE_PROFILE_INFINITE_INHERITANCE
  validate_hardware:
    enabled: false
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 10.255.0.0/27 eq 32
  - sequence: 20
    action: permit 10.255.1.0/27 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_bgp:
  as: '65101'
  router_id: 10.255.0.3
  maximum_paths:
    paths: 4
  bgp:
    default:
      ipv4_unicast: false
  redistribute:
    connected:
      enabled: true
      route_map: RM-CONN-2-BGP
service_routing_protocols_model: multi-agent
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 4096
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
vxlan_interface:
  vxlan1:
    description: device-profile-infinite-inheritance_VTEP
    vxlan:
      source_interface: Loopback1
      udp_port: 4789
