aaa_root:
  disabled: true
aaa_server_groups:
- name: tacacs+
  type: tacacs+
  servers:
  - server: agni.arista.com
    vrf: MGMT
config_end: true
enable_password:
  disabled: true
hostname: invalid-aaa-settings-tacacs-group
ip_igmp_snooping:
  globally_enabled: true
ip_tacacs_source_interfaces:
- name: Management1
  vrf: MGMT
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.0.2/24
  type: oob
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_FAILURES
service_routing_protocols_model: multi-agent
tacacs_servers:
  hosts:
  - host: agni.arista.com
    vrf: MGMT
    key: 1404071B09166738212B2130365E0C131A
  policy_unknown_mandatory_attribute_ignore: false
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
