aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: invalid-vlan-id-on-port-channel-subinterface
ip_igmp_snooping:
  globally_enabled: true
link_tracking_groups:
- name: LT_GROUP1
  recovery_delay: 300
management_interfaces:
- name: Management1
  description: OOB_MANAGEMENT
  shutdown: false
  vrf: MGMT
  ip_address: 192.168.1.2
  type: oob
metadata:
  is_deployed: true
  platform: 720XP
  fabric_name: EOS_DESIGNS_FAILURES
service_routing_protocols_model: multi-agent
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
