aaa_root:
  disabled: true
config_end: true
enable_password:
  disabled: true
hostname: missing-access-list-ipv4-in-catalog
ip_igmp_snooping:
  globally_enabled: true
metadata:
  is_deployed: true
  fabric_name: EOS_DESIGNS_FAILURES
service_routing_protocols_model: multi-agent
snmp_server:
  contact: example@example.com
  communities:
  - name: SNMP-COMMUNITY-1
    access: ro
    access_list_ipv4:
      name: acl-not-present-in-catalog
static_routes:
- vrf: MGMT
  prefix: 0.0.0.0/0
  next_hop: 10.10.10.1
transceiver_qsfp_default_mode_4x10: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
