type: l2leaf

l2leaf:
  nodes:
    - name: host3
      mgmt_ip: 192.168.0./24
      spanning_tree_mode: mstp
      spanning_tree_priority: 8192
      spanning_tree_port_id_allocation_port_channel_range:
        minimum: 201
        maximum: 2001
      spanning_tree_root_super: true
      spanning_tree_mst_pvst_boundary: true
