---
fabric_name: DIGITAL_TWIN_CONTAINERLAB_UNSUPPORTED_MGMT_IP_DHCP

management_eapi:
  enabled: true

eos_designs_documentation:
  enable: false
  topology_csv: false
  p2p_links_csv: false

digital_twin:
  environment: containerlab
  # TODO: remove `fabric` once #5649 is ready
  fabric: {}

type: spine

spine:
  defaults:
    platform: cEOSLab
    loopback_ipv4_pool: 10.255.0.0/27
    bgp_as: 65100
  nodes:
    - name: containerlab-dhcp-mgmt
      id: 1
      mgmt_ip: dhcp

expected_error_message: >-
  Containerlab Digital Twin is unsupported for nodes without a static management IPv4 address.
  Found unsupported management IPv4 address settings: containerlab-dhcp-mgmt.
