---
all:
  children:
    test_hosts:
      children:
        IGNORE_IN_PYTEST:
          hosts:
            # TODO: Remove once pytest coverage of Molecule inventories can handle schema conversions like convert_to_lower_case.
            host-convert-to-lower-case:
            host-inline-jinja:
      hosts:
        host1:
        host2:
        host3:
        host4:
        host5:
        host6:
        host-convert-to-lower-case:
        host-inline-jinja:
