all:
  children:
    test_hosts:
      children:
        IGNORE_IN_PYTEST:
          hosts:
            host_inline_jinja:
      hosts:
        host1:
        host2:
        host3:
        host4:
        host5:
        host6:
        host_inline_jinja:
