---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=../cv_deploy/inventory/
  env:
    ANSIBLE_FORCE_COLOR: true
  cfg:
    defaults:
      gathering: explicit
scenario:
  converge_sequence:
    - syntax
    - converge
  test_sequence:
    - syntax
    - converge
    - cleanup
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
  enabled: false
verifier:
  name: ansible
