---
type: l3leaf
default_mgmt_method: none

default_interfaces:
  - types: [ l3leaf ]
    platforms: [ default ]
    uplink_interfaces: [ Ethernet1-10 ]
    mlag_interfaces: [ Ethernet11-20 ]
    downlink_interfaces: [ Ethernet21-30 ]

cvp_instance_ips:
  - apiserver

name_servers:
  - 1.1.1.1
  - 8.8.8.8

ntp_settings:
  servers:
    - name: pool.ntp.org

l3leaf:
  defaults:
    loopback_ipv4_pool: 10.0.255.0/24
    vtep_loopback_ipv4_pool: 10.0.254.0/24
    virtual_router_mac_address: 00:1c:73:00:dc:01
    bgp_as: 65000-65100
    filter:
      # Ensuring that the inband management vlan is correctly configured even when only_vlans_in_use is set
      only_vlans_in_use: true
  nodes:
    - name: missing-valid-ipv4-address-ntp-servers-leaf
      id: 1
      inband_ztp: true
      uplink_switches: [missing-valid-ipv4-address-ntp-servers-spine]
      uplink_ipv4_pool: 172.16.255.0/24
