---
type: l3leaf
l3leaf:
  defaults:
    mlag_dual_primary_detection: true
    mlag_peer_ipv4_pool: 10.10.255.0/24
    mlag_peer_l3_ipv4_pool: 10.10.224.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 32
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    platform: vEOS-LAB
    mlag_interfaces: [Ethernet5, Ethernet6]
  node_groups:
    - group: missing_mgmt_ip_mlag_dual_primary_detection
      bgp_as: 923
      nodes:
        - name: missing_mgmt_ip_mlag_dual_primary_detection1
          id: 3
        - name: duplicate-interfaces-core-interfaces
          id: 4
          mgmt_ip: 192.168.201.116/24

expected_error_message: >-
  'mlag_dual_primary_detection' is enabled but 'mgmt_ip' is not configured on missing_mgmt_ip_mlag_dual_primary_detection1 or its peer
