# Copyright (c) 2025 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  cv_settings:
    documentation_options:
      table: cloudvision-settings
    type: dict
    description: |-
      Settings for CloudVision telemetry streaming and provisioning.
    keys:
      cvaas:
        type: list
        description: CloudVision-as-a-Service.
        primary_key: name
        items:
          type: dict
          keys:
            name:
              type: str
              description: |-
                Short name for the CVaaS cluster. Used when configuring multiple clusters.
              pattern: "^[a-zA-Z1-9-_]+$"
            fqdn:
              type: str
              required: true
              pattern: "^[a-z1-9\\.-]+\\.arista\\.io$"
              description: CVaaS FQDN like 'apiserver.arista.io' or 'apiserver.cv-prod-euwest-2.arista.io'.
            vrf:
              type: str
              default: use_default_mgmt_method_vrf
              convert_types:
                - int
              description: |-
                The VRF used to connect to CloudVision.
                The value will be interpreted according to these rules:
                - `use_mgmt_interface_vrf` will configure the VRF set with `mgmt_interface_vrf` and configure the `mgmt_interface` as the source interface.
                  An error will be raised if `mgmt_ip` or `ipv6_mgmt_ip` are not configured for the device.
                - `use_inband_mgmt_vrf` will configure the VRF set with `inband_mgmt_vrf` and configure the `inband_mgmt_interface` as the source interface.
                  An error will be raised if inband management is not configured for the device.
                - `use_default_mgmt_method_vrf` will configure the VRF and source-interface for one of the two options above depending on the value of `default_mgmt_method`.
                - Any other string will be used directly as the VRF name.
            token_file:
              type: str
              description: |-
                Path to the onboarding token used for certificate based authentication.
                The path is on the EOS device and the token file must be copied to the device first.
              default: "/tmp/cv-onboarding-token"
            source_interface:
              type: str
              description: |-
                Source-interface used to connect to CloudVision.
                If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
      onprem_clusters:
        type: list
        description: On-premise CloudVision clusters.
        primary_key: name
        items:
          type: dict
          description: |-
            Unless `key` is set, TerminAttr will be configured with certificate based authentication.
            The default token path is '/tmp/token', and the token must be copied to the device first.
          keys:
            name:
              type: str
              description: |-
                Short name for the cluster. Used when configuring multiple clusters.
            servers:
              type: list
              required: true
              min_length: 1
              max_length: 3
              primary_key: name
              description: CloudVision servers that makes up one cluster.
              items:
                type: dict
                keys:
                  name:
                    type: str
                    description: Server FQDN or IP address.
                  port:
                    type: int
                    convert_types:
                      - str
                    default: 9910
            vrf:
              type: str
              default: use_default_mgmt_method_vrf
              convert_types:
                - int
              description: |-
                The VRF used to connect to CloudVision.
                The value will be interpreted according to these rules:
                - `use_mgmt_interface_vrf` will configure the VRF set with `mgmt_interface_vrf` and configure the `mgmt_interface` as the source interface.
                  An error will be raised if `mgmt_ip` or `ipv6_mgmt_ip` are not configured for the device.
                - `use_inband_mgmt_vrf` will configure the VRF set with `inband_mgmt_vrf` and configure the `inband_mgmt_interface` as the source interface.
                  An error will be raised if inband management is not configured for the device.
                - `use_default_mgmt_method_vrf` will configure the VRF and source-interface for one of the two options above depending on the value of `default_mgmt_method`.
                - Any other string will be used directly as the VRF name.
            token_file:
              type: str
              description: |-
                Path to the onboarding token used for certificate based authentication.
                The path is on the EOS device and the token file must be copied to the device first.
              default: "/tmp/token"
            source_interface:
              type: str
              description: |-
                Source-interface used to connect to CloudVision.
                If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
      terminattr_ingestexclude:
        type: str
        description: Exclude paths from Sysdb on the ingest side.
        default: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
      terminattr_smashexcludes:
        type: str
        description: Exclude paths from the shared memory table.
        default: "ale,flexCounter,hardware,kni,pulse,strata"
      terminattr_disable_aaa:
        type: bool
        description: |-
          Disable AAA authorization and accounting.
          When setting this flag, all commands pushed from CloudVision are applied directly to the CLI without authorization
        default: false
      set_source_interfaces:
        type: bool
        description: |-
           Automatically set source interface when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
           Can be set to `false` to avoid changes when migrating from old `cv_instances` model.
        default: true
