# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  digital_twin_custom_structured_configuration_prefix:
    documentation_options:
      table: custom-structured-configuration
    type: list
    items:
      type: str
    description: |
      PREVIEW: This option is marked as "preview", while we refactor the code to conform to the described behavior.
      Custom EOS Structured Configuration keys that will be only applied to the fabric nodes in the Digital Twin mode.
    default: ["digital_twin_custom_structured_configuration_"]
