# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  general_settings:
    type: dict
    documentation_options:
      table: system-settings
    keys:
      interface_defaults:
        type: dict
        keys:
          ethernet_shutdown:
            type: bool
            default: false
            description: Shutdown Ethernet interfaces by default unless they are explicitly enabled.
      arp:
        type: dict
        keys:
          persistent:
            type: dict
            $ref: "eos_cli_config_gen#/keys/arp/keys/persistent"
          aging:
            type: dict
            $ref: "eos_cli_config_gen#/keys/arp/keys/aging"
      ip_icmp_redirect:
        type: bool
        $ref: "eos_cli_config_gen#/keys/ip_icmp_redirect"
      # TODO: Revisit for default values in AVD 7.0
      dhcp_relay:
        type: dict
        keys:
          information_option:
            type: bool
            description: Enables the insertion of DHCP Relay Agent Information (Option 82).
            default: false
          tunnel_requests_disabled:
            type: bool
            description: |-
              Blocks DHCP relay for packets received over VXLAN tunnels.
              This is a VTEP-specific optimization and should not be configured on non-VXLAN termination nodes.
            default: false
          mlag_peerlink_requests_disabled:
            type: bool
            description: |-
              Blocks DHCP relay for packets arriving via the MLAG peer-link.
              This should only be configured on devices acting as both an MLAG node and a VXLAN VTEP.
            default: false
