# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  ssh_settings:
    type: dict
    keys:
      vrfs:
        type: list
        items:
          type: dict
          keys:
            name:
              type: str
              description: VRF name.
            enabled:
              type: bool
              required: true
            ipv4_acl:
              type: str
            ipv6_acl:
              type: str
      idle_timeout:
        type: int
        $ref: "eos_cli_config_gen#/keys/management_ssh/keys/idle_timeout"
