type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: duplicate-tacacs-server
      mgmt_ip: 192.168.0.2/24

aaa_settings:
  tacacs:
    servers:
      - host: 10.10.10.11
        vrf: MGMT1
        key: 071B245F5A
        groups:
          - TACACS1

      - host: 10.10.10.11
        vrf: MGMT1
        key: 071B245F5A
        groups:
          - TACACS1

expected_error_message: >-
  Duplicate TACACS server found: Host '10.10.10.11' is already defined for VRF 'MGMT1'.
