type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: duplicate-radius-server
      mgmt_ip: 192.168.0.2/24

aaa_settings:
  radius:
    servers:
      - host: 10.10.10.11
        vrf: MGMT1
        key: 071B245F5A
        groups:
          - RADIUS

      - host: 10.10.10.11
        vrf: MGMT1
        key: 071B245F5A
        groups:
          - RADIUS

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for RADIUS servers.
  {'host': '10.10.10.11', 'groups': ['RADIUS'], 'vrf': 'MGMT1', 'key': '071B245F5A'} conflicts with
  {'host': '10.10.10.11', 'groups': ['RADIUS'], 'vrf': 'MGMT1', 'key': '071B245F5A'}.
