# Test when 
type: l3leaf

node_type_keys:
  - key: l3leaf
    type: l3leaf
    underlay_router: true
    network_services:
      l2: true
      l3: true
    vtep: true

fabric_evpn_encapsulation: mpls
overlay_routing_protocol: ibgp
evpn_overlay_bgp_rtc: true

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 8
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    mpls_route_reflectors: [isis-system-id-format-missing-node-id]
  nodes:
    - name: duplicate-neighbors-evpn-ovelray-mpls
      id: 101
      bgp_as: 101
      evpn_services_l2_only: true
      mgmt_ip: 192.168.0.101/24
      evpn_role: client
      mpls_overlay_role: server

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for Neighbors.
  {'ip_address': '172.28.4.1', 'peer_group': 'RR-OVERLAY-PEERS', 'peer': 'isis-system-id-format-missing-node-id',
  'description': 'isis-system-id-format-missing-node-id_Loopback0'}
  conflicts with
  {'ip_address': '172.28.4.1', 'peer_group': 'MPLS-OVERLAY-PEERS', 'peer': 'isis-system-id-format-missing-node-id',
  'description': 'isis-system-id-format-missing-node-id_Loopback0'}.
