fabric_name: FABRIC_INBAND_MANAGEMENT

default_node_types:
  - match_hostnames:
      - inband_mgmt_missing_id_with_subnet
    node_type: l2leaf

default_interfaces:
  - types: [ l3leaf, l2leaf ]
    platforms: [ default ]

default_mgmt_method: none

cvp_instance_ips:
  - apiserver.arista.io

name_servers:
  - 1.1.1.1
  - 8.8.8.8

type: l2leaf

l2leaf:
  defaults:
    filter:
      # Ensuring that the inband management vlan is correctly configured even when only_vlans_in_use is set
      only_vlans_in_use: true
  nodes:
    - name: inband_mgmt_missing_id_with_subnet
      inband_mgmt_vlan: 108
      inband_mgmt_subnet: 192.168.102.0/24
      uplink_type: port-channel

expected_error_message: >-
  'id' is not set on 'inband_mgmt_missing_id_with_subnet' and is required to set inband_mgmt_ip from
  inband_mgmt_subnet for host 'inband_mgmt_missing_id_with_subnet'.
