fabric_name: FABRIC_INBAND_MANAGEMENT_IPV6

underlay_l2_ethernet_description: "{peer!u}_{peer_interface}"
underlay_l2_port_channel_description: "{peer_node_group_or_uppercase_peer}_Po{peer_port_channel_id}"

default_node_types:
  - match_hostnames:
      - inband_mgmt_missing_id_with_ipv6subnet
    node_type: l2leaf

default_interfaces:
  - types: [ l3leaf, l2leaf ]
    platforms: [ default ]

default_mgmt_method: none

cvp_instance_ips:
  - apiserver.arista.io

name_servers:
  - 1.1.1.1
  - 8.8.8.8

custom_platform_settings:
  - feature_support:
      per_interface_mtu: false
    platforms: ['default']

type: l2leaf

l2leaf:
  defaults:
    filter:
      only_vlans_in_use: true
  nodes:
    - name: inband_mgmt_missing_id_with_ipv6subnet
      inband_mgmt_vlan: 109
      inband_mgmt_ipv6_subnet: 2a00:104::/64
      # uplink_type: port-channel

expected_error_message: >-
  'id' is not set on 'inband_mgmt_missing_id_with_ipv6subnet' and is required to set inband_mgmt_ipv6_address from
  inband_mgmt_ipv6_subnet for host 'inband_mgmt_missing_id_with_ipv6subnet'.
