type: l2leaf
l2leaf:
  defaults:
  nodes:
    - name: invalid-enable-password
      mgmt_ip: 192.168.0.2/24

# Invalid enable_password hash
aaa_settings:
  enable_password:
    password: "this-is-not-a-valid-sha512-hash"

expected_error_message: >-
  Invalid SHA512 hash for 'aaa_settings.enable_password.password': this-is-not-a-valid-sha512-hash
