---
type: wan_router
wan_mode: cv-pathfinder
underlay_routing_protocol: ebgp

ipv4_prefix_list_catalog:
  - name: ALLOW-DEFAULT
    sequence_numbers:
      - sequence: 10
        action: permit 0.0.0.0/0
  - name: PL2
    sequence_numbers:
      - sequence: 10
        action: permit 5.0.0.0/0
      - sequence: 20
        action: deny 10.0.0.0/24

cv_pathfinder_regions:
  - name: AVD_Land_East
    id: 43
    description: AVD Region
    sites:
      - name: Site511
        id: 511
        location: Miami

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.142.0/24
      - 192.168.143.0/24

wan_stun_dtls_profile_name: profileA

wan_ipsec_profiles:
  control_plane:
    shared_key: ABCDEF1234567890
  data_plane:
    shared_key: ABCDEF1234567890666

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 192.168.142.0/24
    filter:
      always_include_vrfs_in_tenants: [TenantA]
    uplink_ipv4_pool: 172.17.0.0/16
    bgp_as: 65000
  node_groups:
    - group: Site511
      uplink_type: p2p-vrfs
      uplink_interfaces: [Ethernet52]
      cv_pathfinder_region: AVD_Land_East
      cv_pathfinder_site: Site511
      wan_ha:
        enabled: false
      nodes:
        - name: ipv4-acls-zscaler-internet-exit-access-lists
          id: 2
          uplink_switch_interfaces: [Ethernet2]
          l3_interfaces:
            - name: Ethernet2
              wan_carrier: AWS-1
              wan_circuit_id: 212
              dhcp_accept_default_route: true
              ip_address: dhcp
              connected_to_pathfinder: false
              receive_bandwidth: 34
              transmit_bandwidth: 412
            - name: Ethernet3
              wan_carrier: ATT
              wan_circuit_id: 404
              dhcp_accept_default_route: true
              ip_address: dhcp
              peer_ip: 172.31.0.1
              dhcp_ip: 10.0.0.145
              cv_pathfinder_internet_exit:
                policies:
                  - name: ZSCALER-EXIT-POLICY-1
                    tunnel_interface_numbers: 100-102
                  - name: ZSCALER-EXIT-POLICY-2
                    tunnel_interface_numbers: 110-112
            - name: Ethernet4
              dhcp_accept_default_route: true
              ip_address: dhcp
              peer_ip: 172.29.0.13
              bgp:
                peer_as: 64520
                ipv4_prefix_list_in: PL2
                ipv4_prefix_list_out: ALLOW-DEFAULT
            - name: Ethernet5
              dhcp_accept_default_route: true
              ip_address: dhcp
              peer_ip: 172.28.0.14
              bgp:
                peer_as: 64520
                ipv4_prefix_list_out: PL2
          l3_port_channels:
            - # Port-Channel with 2 member ports
              name: Port-Channel1
              mode: active
              member_interfaces:
                - name: Ethernet6
                  peer: peerDevice1
                  peer_interface: PeerDevIntf1
                  speed: "forced 10000full"
                - # peer, peer_interface not set, use peer from parent L3 Port-Channel
                  name: Ethernet7
                  speed: "forced 10000full"
              ip_address: 172.15.5.7/31
              # Using peer_ip same as the one specified for Ethernet3 under l3_interfaces above.
              # This will cause identical nexthop for Zscaler tunnel destinations to be configured via ip route.
              # instead of multiple routes to same Zscaler destination via different nexthops.
              peer: peerDeviceA
              peer_ip: 172.31.0.1
              peer_port_channel: Port-Channel2
              wan_carrier: ATT
              wan_circuit_id: 404
              static_routes:
                - prefix: 172.16.0.0/16
              bgp:
                peer_as: 64520
                ipv4_prefix_list_in: PL2
                ipv4_prefix_list_out: ALLOW-DEFAULT
              flow_tracking:
                enabled: true
            - # Port-Channel with 1 member ports
              name: Port-Channel450
              mode: "on"
              member_interfaces:
                - name: Ethernet1/10
                  speed: "forced 10000full"
              ip_address: 172.15.5.8/31
              peer: peerDevice10
              peer_ip: 172.31.0.10
              peer_port_channel: Port-Channel455
              wan_carrier: Orange
              connected_to_pathfinder: false
              static_routes:
                - prefix: 172.17.0.0/16
              bgp:
                peer_as: 64520
                ipv4_prefix_list_in: PL2
              flow_tracking:
                enabled: false
            - # Port-Channel with 3 member ports
              name: Port-Channel540
              # use default mode
              member_interfaces:
                - name: Ethernet1/16
                  speed: "auto 10000full"
                - name: Ethernet1/17
                  # interface speed not specified
                - name: Ethernet1/18
                  speed: "1000full"
              ip_address: 172.15.6.9/31
              public_ip: 10.36.36.100
              peer: peerDevice11
              peer_ip: 172.31.0.11
              peer_port_channel: Port-Channel545
              wan_carrier: Comcast
              connected_to_pathfinder: true
              static_routes:
                - prefix: 172.18.0.0/16

wan_path_groups:
  - name: MPLS
    ipsec:
      static_peers: false
      dynamic_peers: false
    # TODO remove one once auto-id is implemented - for now required in schema
    id: 100
    dps_keepalive:
      interval: 300
  - name: INET
    id: 101
  - name: LTE
    id: 102
    # The expectation here is that LTE shouldn't be present in the default lb policy.
    excluded_from_default_policy: true
    dps_keepalive:
      interval: 100
      failure_threshold: 12
  - name: Equinix
    id: 103
    default_preference: alternate
  - name: Satellite
    id: 104
    default_preference: alternate
    dps_keepalive:
      interval: auto
  - name: AWS
    id: 105

wan_carriers:
  - name: Comcast
    path_group: INET
    trusted: true
  - name: ATT
    path_group: INET
    trusted: true
  - name: Bouygues_Telecom
    path_group: INET
    trusted: true
  - name: SFR
    path_group: INET
    trusted: true
  - name: Orange
    path_group: INET
    trusted: true
  - name: Another-ISP
    path_group: INET
    trusted: true
  - name: Colt
    path_group: MPLS
    trusted: true
  - name: ATT-MPLS
    path_group: MPLS
    trusted: true
  - name: Comcast-5G
    path_group: LTE
    trusted: true
  # Testing a not trusted carrier
  - name: Inmrasat
    path_group: Satellite
  - name: AWS-1
    path_group: AWS
    trusted: true

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
      wan_vni: 1
    - name: PROD
      policy: PROD-AVT-POLICY
      wan_vni: 42
    # Testing reusing the same policy as default VRF
    - name: IT
      policy: DEFAULT-AVT-POLICY
      wan_vni: 100
    # Testing a VRF only on transit and not edge
    - name: TRANSIT
      policy: TRANSIT-AVT-POLICY
      wan_vni: 66
    - name: ATTRACTED-VRF-FROM-UPLINK
      wan_vni: 166
    - name: WAN-VRF-NO-AF
      # Using PROD policy to avoid extra noise
      policy: PROD-AVT-POLICY
      wan_vni: 200
  policies:
    - name: PROD-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          lowest_hop_count: true
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            jitter: 42
          internet_exit:
            policy: ZSCALER-EXIT-POLICY-1
          id: 2
        - application_profile: VIDEO
          path_groups:
            - names: [MPLS, LTE]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            loss_rate: 42.0
          internet_exit:
            policy: ZSCALER-EXIT-POLICY-2
          id: 4
        # This will not be rendered on devices without MPLS except if their HA
        # peer have MPLS.
        - application_profile: MPLS-ONLY
          path_groups:
            - names: [MPLS]
              preference: preferred
          id: 5
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          # No preference to check the default.
          - names: [INET, Equinix]
          - names: [MPLS]
            preference: 4223
      application_virtual_topologies:
        - application_profile: VIDEO
          path_groups:
            # The expectation here is that Equinix will be configured with priority 1/preferred,
            # since we are overriding the default_preference value (2/alternate).
            - names: [MPLS, INET, Equinix]
              preference: preferred
          internet_exit:
            policy: ZSCALER-EXIT-POLICY-1
          id: 3
    - name: TRANSIT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          name: CUSTOM-VOICE-PROFILE-NAME
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          internet_exit:
            policy: ZSCALER-EXIT-POLICY-2
          id: 42

application_classification:
  application_profiles:
    - name: VIDEO
      # Testing categories filtering
      categories:
        - name: VIDEO1
      applications:
        # Testing applications in application-profiles filtering
        - name: CUSTOM-APPLICATION-1
        # Builtin application that should not raise
        - name: skype
      # application transport to also be covered by the profile
      application_transports:
        - rtp

  categories:
    - name: VIDEO1
      applications:
        # Testing applications in categories filtering
        - name: CUSTOM-APPLICATION-2

  applications:
    ipv4_applications:
      # This should not be rendered in any device
      - name: CUSTOM-APPLICATION-1
        protocols: [tcp]
        # Testing filtering of prefixes
        src_prefix_set_name: CUSTOM-SRC-PREFIX-1
        dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
      - name: CUSTOM-APPLICATION-2
        protocols: [tcp]
        tcp_src_port_set_name: TCP-SRC-2
        tcp_dest_port_set_name: TCP-DEST-2
      - name: CUSTOM-voice-APPLICATION
        protocols: [udp]
        udp_src_port_set_name: UDP-SRC-VOICE
        udp_dest_port_set_name: UDP-DEST-VOICE
      - name: CUSTOM-DSCP-APPLICATION
        dscp_ranges:
          - ef
          - 12-14
          - cs6
          - 42
  field_sets:
    ipv4_prefixes:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: CUSTOM-SRC-PREFIX-1
        prefix_values:
          - 42.42.42.0/24
      - name: CUSTOM-DEST-PREFIX-1
        prefix_values:
          - 6.6.6.0/24
    l4_ports:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: TCP-SRC-2
        port_values:
          - 42
      - name: TCP-DEST-2
        port_values:
          - 666
          - 777
      - name: UDP-SRC-VOICE
        port_values:
          - 42000-42999
      - name: UDP-DEST-VOICE
        port_values:
          - 30000-30100
          - 31000-31100

cv_pathfinder_internet_exit_policies:
  - name: ZSCALER-EXIT-POLICY-1
    type: zscaler
    zscaler:
      domain_name: test.local
      ipsec_key_salt: THIS_SHOULD_BE_VAULTED
  - name: ZSCALER-EXIT-POLICY-2
    fallback_to_system_default: false
    type: zscaler
    zscaler:
      domain_name: test.local
      ipsec_key_salt: THIS_SHOULD_BE_VAULTED

zscaler_endpoints:
  cloud_name: zscalerbeta
  device_location:
    city: Santa Clara, CA
    country: United States
  primary:
    city: Fremont, CA
    datacenter: FMT1
    country: United States
    region: us-west1
    latitude: 37
    longitude: -121
    ip_address: 10.37.121.1 # Not the correct address
  secondary:
    city: Washington, DC
    datacenter: WAS1
    country: United States
    region: us-east1
    latitude: 39
    longitude: -77
    ip_address: 10.39.77.1 # Not the correct address
  tertiary:
    city: Frankfurt
    datacenter: FRA4
    country: Germany
    region: eu-west1
    latitude: 50
    longitude: 9
    ip_address: 10.50.9.1 # Not the correct address

ipv4_acls:
  - name: ACL-NAT-IE-ZSCALER
    entries:
      - sequence: 10
        action: permit
        protocol: ip
        source: any
        destination: 10.0.0.0/24
      - sequence: 20
        action: deny
        protocol: ip
        source: interface_ip
        destination: any

expected_error_message: >-
  ipv4_acls[name=ACL-NAT-IE-ZSCALER] field substitution is not supported for internet exit access lists
