---
# Role defaults - main

# Global timeout for the ANTA runner.
anta_runner_timeout: 30

# ANTA runner batch size. This controls the number of devices that will be processed in parallel. 5-10 is a good starting point.
anta_runner_batch_size: 5

# Run ANTA in dry-run mode. This will generate the tests but not execute them.
anta_runner_dry_run: false
