---
# Role defaults - main

# Run ANTA for these devices.
# Defaults to all hosts in the play.
# This means the role must be imported/included in a play targeting only the relevant EOS devices - *not* CloudVision.
anta_devices: "{{ ansible_play_hosts }}"

# Enable AVD catalogs generation.
avd_catalogs_enabled: true

# Disable used-defined catalogs generation.
user_catalogs_enabled: false

# Generate extra fabric-wide validation tests (e.g., reachability and routing tests).
# This can generate many additional test inputs in the catalogs, and validation may take longer on large fabrics.
avd_catalogs_extra_fabric_validation: false

# Global timeout for the ANTA runner.
anta_runner_timeout: 30

# ANTA runner batch size. This controls the number of devices that will be processed in parallel. 5-10 is a good starting point.
anta_runner_batch_size: 5

# Run ANTA in dry-run mode. This will generate the tests but not execute them.
anta_runner_dry_run: false

# Structured configuration file format. Supported formats: yml, yaml, json.
avd_structured_config_file_format: "yml"

# ANTA runner reports sorting settings.
# `anta_report_status_priority` defines the primary grouping order of the results by test status.
# Unlisted statuses appear at the bottom, grouped alphabetically.
# Within each status group, tests are sub-sorted using the attributes defined in `anta_report_sort_fields`.
anta_report_status_priority: ["error", "failure", "skipped", "success", "unset"]
anta_report_sort_fields: ["device", "categories", "test", "description", "custom_field"]

# Controls the granularity of the Markdown report. When enabled, test entries
# are expanded to show the individual status of every check performed.
anta_report_expand_results: false

# Controls whether the `custom_field` column is generated in the Markdown report.
anta_report_custom_field: false
