---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/../../../examples/campus-fabric/inventory.yml
  env:
    ANSIBLE_FORCE_COLOR: true
  cfg:
    defaults:
      gathering: explicit
  playbooks:
    converge: '${MOLECULE_SCENARIO_DIRECTORY}/../../../examples/campus-fabric/build.yml'
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - converge
    - idempotence
  cleanup_sequence:
    - destroy
dependency:
  name: galaxy
  enabled: false
verifier:
  name: ansible
