#!/usr/bin/env python3

# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
"""Generate a reviewable inventory to prevent unintended files from shipping in the Ansible collection."""

from __future__ import annotations

import os
import sys
import tarfile
from pathlib import Path
from tempfile import TemporaryDirectory

REPOSITORY_ROOT = Path(__file__).parent.parent
COLLECTION_PATH = REPOSITORY_ROOT / "ansible_collections/arista/avd"
COLLECTION_FILES_PATH = COLLECTION_PATH / "collection-files.txt"
GENERATED_HEADER = (
    "# This file is @generated by tools/generate_collection_files.py.\n"
    "# It records every file shipped in the arista.avd collection.\n"
    "# Review changes to ensure unintended files are not included in the collection.\n"
    "# Regenerate with: pre-commit run collection-files --all-files\n"
    "# Do not edit manually.\n"
)


def build_collection(output_path: Path) -> Path:
    """Build the Ansible collection and return the generated artifact path."""
    # Ansible reads this setting while importing, so point it at the existing temporary directory first.
    os.environ["ANSIBLE_LOCAL_TEMP"] = str(output_path)

    from ansible.galaxy.collection import build_collection as ansible_build_collection

    return Path(ansible_build_collection(str(COLLECTION_PATH), str(output_path), force=True))


def get_collection_files(artifact_path: Path) -> list[str]:
    """Return sorted file paths from the collection artifact."""
    with tarfile.open(artifact_path, mode="r:gz") as artifact:
        return sorted(member.name for member in artifact.getmembers() if not member.isdir())


def main() -> int:
    """Generate the review inventory of files shipped in the Ansible collection."""
    with TemporaryDirectory(prefix="avd-collection-files-") as temporary_directory:
        artifact_path = build_collection(Path(temporary_directory))
        collection_files = get_collection_files(artifact_path)

    content = GENERATED_HEADER + "\n".join(collection_files) + "\n"
    if COLLECTION_FILES_PATH.exists() and COLLECTION_FILES_PATH.read_text(encoding="UTF-8") == content:
        return 0

    COLLECTION_FILES_PATH.write_text(content, encoding="UTF-8")
    print(f"Updated {COLLECTION_FILES_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
