---
### group_vars/DC1_LEAFS.yml

type: l2leaf     # Must be l2leaf

dot1x_settings:
  enabled: true

# local users
aaa_settings:
  # AAA Authorization
  authorization:
    exec:
      default: local

  local_users:
    # Username with no password configured
    - name: admin
      privilege: 15
      role: network-admin
      no_password: true

    # Username with a password
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "$6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1."

  radius:
    servers:
      - host: agni.arista.com
        cleartext_key: super-secret-key
