---
all:
  children:
    DIGITAL_TWIN:
      children:
        DIGITAL_TWIN_DEFAULT_INTERFACES:
          hosts:
            digital-twin-default-interfaces-digital-twin-platform:
              type: l2spine
              digital_twin:
                fabric: {}
                use_default_interfaces_of_digital_twin_platform: true
            digital-twin-default-interfaces-original-platform:
              type: l2leaf
        # Group to test rendering of the Ethernet ports (for veos and cloudeos nodes) in the ACT topology file.
        DIGITAL_TWIN_ETHERNET_PORTS:
          hosts:
            digital-twin-ethernet-ports-1:
              type: l3leaf
            # Testing host with dotted naming convention
            digital.twin.ethernet.ports.2:
              type: l3leaf
            # This host uses ACT node type third-party and therefore should not get any ethernet ports rendered in the ACT topology file
            digital-twin-ethernet-ports-3:
              type: l3leaf
        CLEAN_UNIT_TESTS: # Single Devices testing one specific case and only using hostvars
          hosts:
            digital-twin-adjust-oob-mgmt-1:
            digital-twin-adjust-oob-mgmt-2:
            digital-twin-adjust-oob-mgmt-3:
            digital-twin-adjust-oob-mgmt-4:
            digital-twin-enforce-eapi-1:
            digital-twin-enforce-eapi-2:
            digital-twin-enforce-eapi-3:
            digital-twin-enforce-eapi-4:
    # Test case to confirm that ACT topology file gets rendered without an empty iterable for the links
    DIGITAL_TWIN_SINGLE_SWITCH_FABRIC:
      children:
        # Ignore this host in pytest (don't use to pick variables, etc)
        IGNORE_IN_PYTEST:
          hosts:
            digital-twin-single-switch-fabric-1:
              type: l2leaf
