---

type: l3leaf

l3leaf:
  defaults:
    bgp_as: 65001
    loopback_ipv4_pool: 10.10.10.0/24
    vtep_loopback_ipv4_pool: 10.10.20.0/24
  nodes:
    - name: HARDWARE_FEATURES_VEOS_LAB
      id: 1
      platform: vEOS-lab
    - name: HARDWARE_FEATURES_CEOS_LAB
      id: 2
      platform: cEOSLab
    - name: HARDWARE_FEATURES_CLOUDEOS
      id: 3
      platform: cloudEOS
    - name: HARDWARE_FEATURES_720XP
      id: 4
      # Supports PoE
      platform: 720XP
    - name: HARDWARE_FEATURES_7280R
      id: 5
      # Supports queue-monitor length notifying
      platform: 7280R

# Test `queue-monitor`
queue_monitor_length:
  enabled: true
  notifying: true
queue_monitor_streaming:
  enable: true

# Test `PoE`
servers:
  - name: TEST_POE_SERVER
    adapters:
      - switch_ports:
          - Ethernet7
          - Ethernet7
          - Ethernet7
          - Ethernet7
          - Ethernet7
        switches:
          - HARDWARE_FEATURES_VEOS_LAB
          - HARDWARE_FEATURES_CEOS_LAB
          - HARDWARE_FEATURES_CLOUDEOS
          - HARDWARE_FEATURES_720XP
          - HARDWARE_FEATURES_7280R
        endpoint_ports:
          - ETH1_NO_POE
          - ETH2_NO_POE
          - ETH3_NO_POE
          - ETH4_WITH_POE
          - ETH5_NO_POE
        poe:
          reboot:
            action: maintain

# Test `BGP`
tenants:
  - name: TENANT1
    vrfs:
      - name: VRF10
        vrf_vni: 10
        l3_interfaces:
          - interfaces:
              - Ethernet5
              - Ethernet5
              - Ethernet5
              - Ethernet5
              - Ethernet5
            ip_addresses:
              - 10.10.40.1/24
              - 10.10.40.2/24
              - 10.10.40.3/24
              - 10.10.40.4/24
              - 10.10.40.5/24
            nodes:
              - HARDWARE_FEATURES_VEOS_LAB
              - HARDWARE_FEATURES_CEOS_LAB
              - HARDWARE_FEATURES_CLOUDEOS
              - HARDWARE_FEATURES_720XP
              - HARDWARE_FEATURES_7280R
        bgp_peers:
          - ip_address: 10.10.40.100
            remote_as: 65002
            nodes:
              - HARDWARE_FEATURES_VEOS_LAB
              - HARDWARE_FEATURES_CEOS_LAB
              - HARDWARE_FEATURES_CLOUDEOS
              - HARDWARE_FEATURES_720XP
              - HARDWARE_FEATURES_7280R

# Test `hardware speed-group`
platform_speed_groups:
  - platform: vEOS-lab
    speeds:
      - speed: 10g
        speed_groups:
          - "1"
  - platform: cEOSLab
    speeds:
      - speed: 10g
        speed_groups:
          - "1"
  - platform: cloudEOS
    speeds:
      - speed: 10g
        speed_groups:
          - "1"
  - platform: 720XP
    speeds:
      - speed: 10g
        speed_groups:
          - "1"

# Test `hardware counter feature`
hardware_counters:
  features:
    - name: acl
      direction: out
      address_type: mac
    # Expected to be filtered out for virtual platforms
    - name: gre tunnel interface
      direction: out
    # Expected to be filtered out for virtual platforms
    - name: mpls lfib
      units_packets: true
      direction: out
    - name: mpls lfib
      units_packets: false
      direction: in
    - name: mpls tunnel
    - name: nexthop
    - name: pbr
      direction: in
    - name: vni decap
    - name: vni encap
    - name: vtep decap
    - name: vtep encap
    # Expected to be filtered out for virtual platforms
    - name: segment-security
      direction: in
