---
### group_vars/HYBRID_CAMPUS_TESTS_NYC_CAMPUS_SEGMENT_MIDTOWN_FLOOR1.yml

type: l2leaf

network_ports:
  - switches:
      - NYC_CAMPUS_SEGMENT_MIDTOWN_FLOOR1_LEAFS_LEAF1[AB]
    switch_ports:
      - Ethernet1-48
    description: NYC Midtown Floor1 Standard Port configuration
