---
# Test uplink types p2p-vrfs with rfc5549 and 'overlay_routing_protocol: none'
overlay_routing_protocol: none

underlay_rfc5549: true

node_type_keys:
  # modify spine to get l3 network_services
  - key: spine
    type: spine
    default_evpn_role: server
    default_ptp_priority1: 20
    network_services:
      l3: true
  - key: l3leaf
    type: l3leaf
    connected_endpoints: true
    default_evpn_role: client
    mlag_support: true
    network_services:
      l2: true
      l3: true
    vtep: true
    default_ptp_priority1: 30
    cv_tags_topology_type: leaf

default_node_types:
  - node_type: spine
    match_hostnames:
      - ".*SPINE.*"
  - node_type: l3leaf
    match_hostnames:
      - ".*LEAF.*"

bgp_as: 65000

l3leaf:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 172.16.0.0/24
    virtual_router_mac_address: cafe:cafe:cafe
    uplink_ipv4_pool: 10.42.42.0/24
    uplink_switches: [ UPLINK_P2P_VRFS_RFC5549_TESTS_SPINE1]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    uplink_type: p2p-vrfs
    uplink_macsec:
      profile: TEST
  nodes:
    - name: UPLINK_P2P_VRFS_RFC5549_TESTS_LEAF
      # Testing RFC5549 with IPv6 overlay peers only
      bgp_as: 65106
      uplink_interfaces: ['Ethernet1', 'Ethernet2']
      loopback_ipv6_pool: 2001:1::/64
      loopback_ipv6_offset: 4
      id: 8
      mac_address: '0c:1d:c0:1d:62:01'
      uplink_switch_interfaces: [ Ethernet3, Ethernet4 ]

spine:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 192.168.42.0/24
  nodes:
    - name: UPLINK_P2P_VRFS_RFC5549_TESTS_SPINE1
      id: 1

tenants:
  - name: TenantA
    vrfs:
      # Testing VRF default is not added as subinterface.
      - name: default
        vrf_id: 1
      - name: PROD
        vrf_id: 42
      - name: IT
        vrf_id: 100
  - name: TenantB
    vrfs:
      # Testing duplicate VRF with consistent ID. Silently ignored since it leads to the same subinterface config.
      - name: PROD
        vrf_id: 42
