# Copyright (c) 2026 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
---
- name: Verify Requirements
  delegate_to: localhost
  when: avd_requirements is not defined and avd_verify_requirements | default(true)
  arista.avd.verify_requirements:
    requirements: "{{ lookup('file', requirements_path ~ '/requirements.txt').splitlines() }}"
    avd_ignore_requirements: "{{ avd_ignore_requirements | default(false) }}"
  vars:
    requirements_path: "{{ (role_path | split('/'))[0:-2] | join('/') }}"
  run_once: true
  register: avd_requirements

- name: Create required output directories if not present
  when: avd_create_directories | arista.avd.default(true)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0o775"
  loop:
    - "{{ structured_dir }}"
    - "{{ fabric_dir }}"
  delegate_to: localhost
  run_once: true

- name: Run eos_designs
  block:
    - name: Validate eos_designs inputs
      arista.avd.validate_inputs:
        tmp_dir: "{{ eos_designs_tmp_dir }}"
        batch_size: "{{ eos_designs_validate_inputs_batch_size | arista.avd.default(10) }}"
        schema_name: avd_design
        fail_on_validation_errors: true
        validation_configuration: "{{ eos_designs_validation_configuration }}"
        vault_id: "{{ avd_vault_id }}"
      delegate_to: localhost
      check_mode: false
      run_once: true

    - name: Set eos_designs facts
      arista.avd.eos_designs_facts:
        tmp_dir: "{{ eos_designs_tmp_dir }}"
        # cprofile_file: "eos_designs_facts.prof"
        template_output: true
        output_dir: "{{ output_dir }}"
        digital_twin: "{{ avd_digital_twin_mode | arista.avd.default(false) }}"
      delegate_to: localhost
      check_mode: false
      run_once: true

    - name: Generate device configuration in structured format
      when: avd_eos_designs_structured_config | arista.avd.default(true)
      arista.avd.eos_designs_structured_config:
        tmp_dir: "{{ eos_designs_tmp_dir }}"
        eos_designs_custom_templates: "{{ eos_designs_custom_templates | arista.avd.default([]) }}"
        dest: "{{ structured_dir }}/{{ inventory_hostname }}.{{ avd_structured_config_file_format }}"
        # cprofile_file: "structured-{{inventory_hostname}}.prof"
        template_output: true
        structured_config: "{{ avd_eos_designs_structured_config | arista.avd.default(true) }}"
        digital_twin: "{{ avd_digital_twin_mode | arista.avd.default(false) }}"
        return_structured_config: "{{ eos_designs_return_structured_config | arista.avd.default(false) }}"
      delegate_to: localhost
      check_mode: false
      register: structured_config

    - name: Generate fabric documentation
      when: |-
        eos_designs_documentation.enable | arista.avd.default(true)
        or eos_designs_documentation.topology_csv | arista.avd.default(false)
        or eos_designs_documentation.p2p_links_csv | arista.avd.default(false)
        or avd_digital_twin_mode | arista.avd.default(false)
      arista.avd.eos_designs_documentation:
        tmp_dir: "{{ eos_designs_tmp_dir }}"
        structured_config_dir: "{{ structured_dir }}"
        structured_config_suffix: "{{ avd_structured_config_file_format }}"
        fabric_documentation_file: "{{ fabric_dir }}/{{ fabric_name }}-documentation.md"
        fabric_documentation: "{{ eos_designs_documentation.enable | arista.avd.default(true) }}"
        include_connected_endpoints: "{{ eos_designs_documentation.connected_endpoints | arista.avd.default(false) }}"
        include_vrf_summary: "{{ eos_designs_documentation.sections.vrf_summary | arista.avd.default(false) }}"
        include_bgp_peer_groups: "{{ eos_designs_documentation.sections.bgp_peer_groups | arista.avd.default(false) }}"
        topology_csv_file: "{{ fabric_dir }}/{{ fabric_name }}-topology.csv"
        topology_csv: "{{ eos_designs_documentation.topology_csv | arista.avd.default(false) }}"
        p2p_links_csv_file: "{{ fabric_dir }}/{{ fabric_name }}-p2p-links.csv"
        p2p_links_csv: "{{ eos_designs_documentation.p2p_links_csv | arista.avd.default(false) }}"
        toc: "{{ eos_designs_documentation.toc | arista.avd.default(true) }}"
        digital_twin_file: "{{ fabric_dir }}/{{ fabric_name }}-topology.yml"
        digital_twin: "{{ avd_digital_twin_mode | arista.avd.default(false) }}"
        mode: "0o664"
      delegate_to: localhost
      check_mode: false
      run_once: true

  always:
    - name: Clean up AVD temporary directory
      when: not eos_designs_keep_tmp_files
      ansible.builtin.file:
        path: "{{ eos_designs_tmp_dir }}"
        state: absent
      delegate_to: localhost
      run_once: true
      changed_when: false
