---
# Play 1: Test hosts that must fail at validate_inputs task.
- name: Converge Negative tests - validate_inputs
  hosts: conflicting-deprecated-and-new-keys
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_cli_config_gen
      rescue:
        - name: Assert eos_cli_config_gen failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message

# Play 2: Test hosts that must fail at eos_cli_config_gen task.
- name: Converge Negative tests - eos_cli_config_gen
  hosts: router-bfd-dangerous-interval-false, router-bfd-dangerous-interval-not-set
  gather_facts: false
  connection: local
  tasks:
    - name: Run failure scenario Test
      block:
        - name: Trigger Error
          ansible.builtin.import_role:
            name: arista.avd.eos_cli_config_gen
      rescue:
        - name: Assert eos_cli_config_gen failed with the expected error message
          ansible.builtin.assert:
            that:
              - ansible_failed_result is defined
              - ansible_failed_result.msg == expected_error_message
