---
name: "PR Benchmarks"

"on":
  pull_request:
    types: [labeled]

env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

jobs:
  pr-benchmarks:
    name: PR Benchmarks (Python 3.12)
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'benchmark')
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --group dev --group benchmark --upgrade

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
          run: pytest --codspeed benchmarks
