---
name: Publish coverage to CodeCov
"on":
  workflow_call:

jobs:
  codecov:
    name: Upload coverage to CodeCov
    if: github.repository == 'aristanetworks/avd'
    runs-on: ubuntu-latest
    # These permissions are mandatory for OIDC to work
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download coverage from pytest
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: pytest-coverage

      - name: Download coverage from ansible-test units
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: ansible-test-units-coverage

      - name: Download coverage from ansible-test integration
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: ansible-test-integration-coverage

      - name: Download eos_designs compiled templates from pytest
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: pytest-eos-designs-compiled-templates
          path: python-avd/pyavd/_eos_designs/j2templates/compiled_templates/

      - name: Download eos_cli_config_gen compiled templates from pytest
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: pytest-eos-cli-config-gen-compiled-templates
          path: python-avd/pyavd/_eos_cli_config_gen/j2templates/compiled_templates/

      - name: Upload pytest coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          use_oidc: true
          fail_ci_if_error: false
          flags: pyavd
          files: ./coverage.xml

      - name: Upload ansible-test units coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          use_oidc: true
          fail_ci_if_error: false
          flags: ansible-test-units
          files: ./ansible_collections/arista/avd/units-coverage.xml

      - name: Upload ansible-test integration coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          use_oidc: true
          fail_ci_if_error: false
          flags: ansible-test-integration
          files: ./ansible_collections/arista/avd/integration-coverage.xml
