---
name: autofix.ci

"on":
  pull_request:
  push:
    branches:
      - devel

concurrency:
  group: autofix-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  autofix:
    name: Run pre-commit and commit back any changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        continue-on-error: true
        with:
          extra_args: markdownlint-cli2 --all-files

      - name: Commit back any git diff
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
