---
name: "Release"

"on":
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  publish_pyavd:
    name: Publish PyAVD package
    if: github.repository == 'aristanetworks/avd'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-pyavd.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
